### ISSUE TITLE
As a plugin user, I should have documentation for the official 0.7 release of this plugin

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1035]
AC1: Ensure plugin features are documented in this repo's Wiki.
AC2: Ensure plugin changelog is appropriately documented, outlining major and minor changes from the 0.6 to 0.7 releases.

**Comment by ThierryA** [comment]
FYI, some useful info regarding comments in 0.7 from @westonruter [here](https://wordpress.org/support/topic/displaying-wp-comments/#post-10104789).

**Comment by kienstra** [comment]
Also see internal ticket [AP2-20](https://xwp-co.atlassian.net/browse/AP2-20).

**Comment by kienstra** [comment]
**Request For Review**

Hi @ThierryA,
Could you please review the wiki pages listed on [AP2-20](https://xwp-co.atlassian.net/browse/AP2-20)? 

For the public record, that ticket has these changes to the wiki pages:


*New*
* [Adding Theme Support](https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support)
* [Commenting](https://github.com/Automattic/amp-wp/wiki/Commenting) (intended as a sub-page of "Core Feature Support")

*Updated*
* [Legacy Template And Customization](https://github.com/Automattic/amp-wp/wiki/Legacy-Templating-And-Customization): Title changed, and first 2 sentences added to describe "Native AMP" and "Paired Mode," changed "AMP Customizer" to [Customizer Panel](https://github.com/Automattic/amp-wp/wiki/Legacy-Templating-And-Customization#customizer-panel).
* [General FAQ's and Common Issues](https://github.com/Automattic/amp-wp/wiki/General-FAQ's-and-Common-Issues): Updated answer to [How do I customize the AMP output for my site?](https://github.com/Automattic/amp-wp/wiki/General-FAQ's-and-Common-Issues#how-do-i-customize-the-amp-output-for-my-site)

**Comment by westonruter** [comment]
Some more things that would probably be worthwhile to add docs for:

* How to add shortcodes and widgets, including the use of `is_amp_endpoint()` inside the render function to switch between the two versions when required.
* Make sure that any GitHub links include the full permalink (with the commit hash) so that they don't become invalid when the plugin evolves.
* Add a section regarding enqueueing scripts and how they will be blocked from being output. Maybe include here a section regarding `amp-bind` to introduce the topic and how it is the alternative to including custom scripts, such as those included in Underscores.
* Show how to create a form that takes a POST request. Note the requirement about doing `wp_redirect()`. Mention also here that the AMP component scripts for forms and for any other components will be automatically included, so you don't have to do so manually. (I added a note related to this under the discussion of `amp-live-list`.) You could also mention here that you can implement forms that use templates to show the results without doing full redirects by using the `action-xhr` attribute instead of `action`.

I pushed up some edits for other things I thought should be added.

Otherwise, I think it's good for the v0.7 release.

**Comment by ThierryA** [comment]
Thanks @kienstra, things are looking good!

I think an area that could still be explain further is the post-processor actions when the AMP theme support is declared, basically what does the post-processor do and how it could be an issue in some cases. That said, this is really much related to the Validation Status details so we can hold on to 1.0 to provide more details about it.

**Comment by kienstra** [comment]
**Thanks**

Hi @ThierryA,
Thanks, that's a good idea to explain the post-processor in `1.0`.

I added these new [wiki](https://github.com/Automattic/amp-wp/wiki/) pages:

<img width="673" alt="new-wiki-pages" src="https://user-images.githubusercontent.com/4063887/39384925-09cd6c0e-4a34-11e8-95a0-374497b4c743.png">
