### ISSUE TITLE
AMP 0.6 : Broken Support for Custom Post Type Archives

### ISSUE THREAD

**Issue by mdbitz** [Automattic/amp-wp#1051]
https://github.com/Automattic/amp-wp/wiki/Custom-Post-Type-Support

Previous to version 0.6.* The AMP plugin did not perform a Queried Object check to determine if rendering of the AMP template was necessary. This allowed pre 0.6. custom archive pages to render AMP versions. 

With the addition of: https://github.com/Automattic/amp-wp/commit/18ab955daee5be27dd2415b23adb9ddea3df805c#diff-4805c837d3390517773926fb26726bcd existing amp rendered pages were broken since on custom archives their is no `get_queried_object()` which causes `amp_render` to exit. To get around this restriction developers can explicitly set the queried object in their code:

```
global $wp_query;
$wp_query->queried_object = new WP_Post( new StdClass() );
```

Is there a specific reason the queried object check was added for rending of AMP Pages? Is there any AMP specific logic that relies on the Queried Object being defined?

**Comment by westonruter** [comment]
@mdbitz I'm surprised that custom archive pages could be rendered since `AMP_Post_Template` requires a `WP_Post` to work. Please share details on how the custom archive pages are implemented and that will help clarify how the code should change to accommodate. Nevertheless, even so I don't think we should necessarily be trying to support the use of `AMP_Post_Template` for anything but posts. With 0.7 and beyond themes should be using the `amp` theme support instead to serve singular post templates and archive templates alike.

**Comment by westonruter** [comment]
We can re-open if we get more info.
