### ISSUE TITLE
Sanitizer removes fonts that omit the scheme from the URL

### ISSUE THREAD

**Issue by douglyuckling** [Automattic/amp-wp#1072]
When my theme enqueues a font like this:
```php
wp_enqueue_style( 'hemingway_googleFonts', '//fonts.googleapis.com/css?family=Raleway' );
```
the sanitizer strips it out. Adding the `https:` scheme to the URL fixes the problem, so I think the sanitizer maybe needs to be a little more tolerant with the URL.

(If this behavior is actually intentional, then I think the error message could use improvement. The error message I got was misleading: "Skipped stylesheet which does not have recognized CSS file extension (//fonts.googleapis.com/css).")

**Comment by westonruter** [comment]
Great catch. Yes, for fonts the logic here needs to be improved:

https://github.com/Automattic/amp-wp/blob/a8afc7550e2e31903badfee3f6d05c371a5477e6/includes/sanitizers/class-amp-style-sanitizer.php#L338-L341

For example, maybe the `preg_match` call could be changed to simply make sure the checked:

```php
$normalized_font_href = preg_replace( '#^(http:)?(?=//)#', 'https:', $href );
if ( $this->allowed_font_src_regex && preg_match( $this->allowed_font_src_regex, $normalized_font_href ) ) {
    if ( $href !== $normalized_font_href ) {
        $element->setAttribute( 'href', $normalized_font_href );
    }
    return;
}
```

@douglyuckling Could you give that change a try?

**Comment by westonruter** [comment]
The logic around the “Skipped stylesheet which does not have recognized CSS file extension” error message could be improved as well:

https://github.com/Automattic/amp-wp/blob/a8afc7550e2e31903badfee3f6d05c371a5477e6/includes/sanitizers/class-amp-style-sanitizer.php#L261-L264

This method is trying to make sure that it doesn't expose any path traversal attack vectors, so by limiting the files checked to just local static CSS files then it is safer than allowing any file to be looked for. Also, since this method requires that the URL actually be a filesystem path then it stands to reason there should be an actual file that has an extension. There shouldn't be an actual file in a WP theme/plugin that is just called plainly `css`, as in the case of the Google Font URL example.

**Comment by westonruter** [comment]
@douglyuckling would you give #1077 a try?

**Comment by kienstra** [comment]
**Moving To "Ready For Merging"**

Hi @westonruter,
If it's alright, I'm moving this from "Ready for QA" to "Ready for Merging." I don't think it needs functional testing, and douglyuckling and I tested this in #1077.
