### ISSUE TITLE
Images unexpectedly expand to fill containers

### ISSUE THREAD

**Issue by kienstra** [Automattic/amp-wp#1104]
As @westonruter pointed out, images can sometimes appear horizontally stretched.

This issue sometimes appears when images have less width than their container. 

<img width="1291" alt="layout-intrinsic-example" src="https://user-images.githubusercontent.com/4063887/39452231-1bca4a0c-4c97-11e8-8fb1-fa62e829da3c.png">

**Appears on**
* Paired Mode child themes of Twenty Ten, Twenty Fifteen, Twenty Sixteen, and Twenty Seventeen
* Native AMP [child theme of Twenty Fifteen](https://amp-make-xwp.pantheonsite.io/2016/07/24/dependently-contextual-customizer-controls/)
* Legacy Templating ([screenshot](https://cloudup.com/c00IeqnePhu))

**Steps To Reproduce**

1. Checkout the `0.7` branch of this plugin
2. Activate a Paired Mode child theme of Twenty Fifteen (update: or simply use any core theme, not a child theme)
3. Create a new post
4. Add an image that's less wide than `600px`, like [this image](https://cloudup.com/cQZwaa4TeRd) (update: and center-align the image)
5. Save the post, and visit the front-end on a desktop display (appending `/amp` or `?amp=1` to the URL)
Expected: it appears at its natural dimensions (300x232 for the example above)
Actual: it appears stretched (see image above)

This may be related to #937.

**Comment by kienstra** [comment]
**Initial Findings**

So far, this looks to be related to the `aligncenter` class. 

That has the style rule `display: block;`
```css
.aligncenter {
    clear: both;
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```
And that seems to override the rule that AMP has for `layout="intrinsic"`
```css
.i-amphtml-layout-intrinsic {
    display: inline-block;
    ...
}
```

<img width="1286" alt="align-center" src="https://user-images.githubusercontent.com/4063887/39454324-387f55bc-4ca0-11e8-9b61-f60ea98609e4.png">

**Comment by postphotos** [comment]
Hi @kienstra, Thanks for hopping in and thanks @westonruter for reporting! I added a user story/AC here.

**Comment by westonruter** [comment]
The `margin` on the `.amp-wp-enforced-sizes` also seems to be a problem, since it is blowing away the `auto` margins:

![image](https://user-images.githubusercontent.com/134745/39455637-6ed5788a-4c96-11e8-982d-181687d9663b.png)

The issue can be seen in 1.0-alpha as well on https://amp-make-xwp.pantheonsite.io/2016/07/24/dependently-contextual-customizer-controls/

**Comment by kienstra** [comment]
**Simplest Way To See Bug**

The simplest way to see this bug is to add the class `aligncenter` to any `<amp-img>` on a "legacy template" page [like this](https://make.xwp.co/2018/02/28/my-thoughts-on-leadership/amp/).

**Comment by kienstra** [comment]
**Legacy Templating: Images Used To Be Centered**

A related issue is that in the previous version, `0.6` (see branch `0.6`), the "legacy template" images were all centered:

https://ryankienstra.wordpress.com/2018/05/01/test-page/amp/
<img width="1289" alt="legacy-templating-06" src="https://user-images.githubusercontent.com/4063887/39459155-17e6d4f0-4cbf-11e8-871b-2c9646807b1e.png">

This style rule used to center all of the images:
```css
.amp-wp-article-content amp-img {
    margin: 0 auto;
}
```

In `0.7`, the `<amp-img>` has a `layout` of `intrinsic`, which seems to be a much better layout. But it seems to have a side effect of overriding the style rule above with:
```css
.i-amphtml-layout-intrinsic {
    display: inline-block;
    ...
}
```

As I understand it, applying left and right margins of `auto` doesn't center elements that have a `display` of `inline-block`.

For example, [this post](https://make.xwp.co/2018/02/28/my-thoughts-on-leadership/amp/) uses the plugin version `0.7`, and the images aren't centered.

**Comment by westonruter** [comment]
> But it seems to have a side effect of overriding the style rule

And it is illegal to add our own style rules that include `i-amphtml-*` classes.

**Comment by delawski** [comment]
As I've looked into the issue, I've noticed that there's no problem with images having captions:

![screenshot 2018-05-02 20 35 04](https://user-images.githubusercontent.com/478735/39542241-50942eb2-4e48-11e8-9b86-05c38be32994.png)

It turns out that when you add a wrapper element that has a defined width and the `aligncenter` class applied, the inner `amp-img` with `layout="intrinsic"` is centered properly and not stretched.

We've investigated the issue with @kienstra and came up to such solution:

1. Remove `aligncenter` class from the `amp-img`.
2. Wrap the `amp-img` with a block element (e.g. `figure`) having the width defined and `alingcenter` class applied, i.e.:

```
<figure class="aligncenter" style="width: ...px; max-width: 100%"><amp-img ...></amp-img></div>
```

Thanks to that the image should not get stretched horizontally, it should be centered and in case it's wider than the container, it won't overflow.

**Comment by westonruter** [comment]
Fixed by #1109. Thanks @delawski!

**Comment by mustafauysal** [comment]
Hi,

Unfortunately, inline styles are not supported by AMP. Could we reconsider this?

**Comment by westonruter** [comment]
@mustafauysal You're right that inline styles aren't allowed by AMP, but the AMP plugin does support them by converting them into CSS style rules via selectors with generated CSS class names.

**Comment by mustafauysal** [comment]
@westonruter Oh! I see now. We are using custom sanitizers, that's why I've looked to the wrong place at first. Thanks for the clarification.

**Comment by westonruter** [comment]
This is being revisited in #2036. Please test.
