### ISSUE TITLE
amp plugin causing inability to view posts

### ISSUE THREAD

**Issue by ppcguyorlando** [Automattic/amp-wp#1130]
When I click on edit link of post, I am taken to blank screen. We have deactivated the plugin..any resolution. when deactivated, we can see blog post contents...when activated, see this image.
![screen shot 2018-05-07 at 12 23 19 pm](https://user-images.githubusercontent.com/18334412/39720616-fc356a86-520a-11e8-83d4-3eef37f5f25a.png)

**Comment by westonruter** [comment]
There may be a PHP error occurring. Can you share your PHP error log? Otherwise, can you add `define( 'WP_DEBUG', true );` to your `wp-config.php`?

If I had to guess, I would say that the the issue may be coming from these lines:

https://github.com/Automattic/amp-wp/blob/0.7.0/includes/utils/class-amp-validation-utils.php#L555-L567

Specifically, the `process_markup` does `apply_filters( 'the_content', ... )`:

https://github.com/Automattic/amp-wp/blob/0.7.0/includes/utils/class-amp-validation-utils.php#L378

So you could have a plugin that is not liking this.

Please also share the list of plugins you have active. In particular, share any plugin or theme that has mentions `the_content`.

**Comment by westonruter** [comment]
@ppcguyorlando based on the hunch of `the_content` filter, I've opened a PR to rework that. Would you be able to test the build? See #1132. To test:

```
git clone --recursive https://github.com/Automattic/amp-wp.git amp
cd amp
npm install
composer install
npm run build
```

This will create an `amp.zip` file that you can install on your site. Note you'll have to first deactivate and uninstall the v0.7.0 AMP plugin before you can upload and activate this ZIP on the plugins admin screen. Ideally you could test this on a staging site.

**Comment by westonruter** [comment]
This should be fixed now.
