### ISSUE TITLE
Add `built` branch

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#1167]
Many sites, including those hosted on VIP, prefer to submodule plugins directly from GItHub. Because the AMP plugin requires an extra build step before use, this is no longer possible.

It would be nice if we can set up an autogenerated `built` branch (using Travis or another CI service) that runs the necessary build steps and pushes a runnable version of the plugin.

Jetpack is one example plugin that provides this: https://github.com/Automattic/jetpack/tree/branch-6.1-built

**Comment by westonruter** [comment]
Good idea. What do you think about using a tag for this instead of a branch? I have a concern about using a branch with a new build commit made for every source commit on a corresponding branch: it can cause the repo size to balloon bigly, especially when JS is built. But if there were build tags created for each release branch (e.g. `develop-built`, `0.7-built`), and each release tag (e.g. `0.7.0-built`, `1.0-beta1-built`), with each new build for the tag/branch causing a the built tag to be rewritten.

**Comment by mjangda** [comment]
> What do you think about using a tag for this instead of a branch?

Yep, a tag seems fine.

**Comment by westonruter** [comment]
I've created the first built tag for 0.7.1: https://github.com/Automattic/amp-wp/releases/tag/0.7.1-built

I linked to it from the [0.7.1 release](https://github.com/Automattic/amp-wp/releases/tag/0.7.1).

Here are the commands I used to create the release:

```bash
tag=0.7.1
git checkout $tag
npm run build
mkdir built
git clone . built/
cd built
git checkout $tag
git rm -r $(git ls-files)
rsync -avz ../build/ ./
git add -A .
git commit -m "Build $tag" --no-verify
git tag $tag-built
git push origin $tag-built
cd ..
git push origin $tag-built
rm -rf built
```

**Comment by westonruter** [comment]
Also created built tag for 1.0-alpha1: https://github.com/Automattic/amp-wp/releases/tag/1.0-alpha1
