### ISSUE TITLE
Monster Widget plugin triggers notices

### ISSUE THREAD

**Issue by mor10** [Automattic/amp-wp#1178]
Adding `add_theme_support( 'amp' )` to a theme (tested on Twenty Seventeen out of the box) causes odd behavior including images not loading and errors around the widgets:

>Notice: the_widget was called incorrectly. Widgets need to be registered using register_widget(), before they can be displayed. Please see Debugging in WordPress for more information. (This message was added in version 4.9.0.) in (...)/wp-includes/functions.php on line 4320

**Comment by mor10** [comment]
@westonruter

**Comment by westonruter** [comment]
I can't seem to reproduce the issue. If you have a vanilla install why is there a call to `the_widget()`? This doesn't occur in any Twenty Seventeen templates. Is it being called by a plugin you have active?

**Comment by mor10** [comment]
It appears this problem is caused by the [Monster Widget](https://wordpress.org/plugins/monster-widget/) plugin. The question is if other plugins behave similarly to this one or if it's a unique case.

**Comment by westonruter** [comment]
@mor10 I think this is a problem specifically with Monster Widget. It has hard-coded list of core widgets in `\Monster_Widget::get_widget_config()`. The AMP plugin swaps out core widgets with subclasses of these same widgets when `amp` theme support is present:

https://github.com/Automattic/amp-wp/blob/888ac10fd8a9ffa81c5baa558b6e11998b80e198/includes/class-amp-theme-support.php#L546-L567

So instead of `WP_Widget_Categories` being registered, instead `AMP_Widget_Categories` is registered. This pattern of extending a core widget is somewhat standard I think. The Monster Widget plugin should be updated to locate registered widget subclasses of the core widgets.
