### ISSUE TITLE
Add the ability to suppress AMP notices on the classic post editor & Gutenberg

### ISSUE THREAD

**Issue by devignerforhire** [Automattic/amp-wp#1197]
Hi guys,

I'm testing out compatibility with Gutenberg this week and so far it's going great. The only nitpick I have is that the AMP notice bar is displayed on every single save, which gets annoying pretty quickly. Especially since the issues mentioned are not related to the post content anyways. It would be great if there was a way to suppress these on the editor, possibly via the Settings page Weston mentioned.

On another note, I also noticed something weird where the AMP notice bar was getting output inside one of the blocks. See the screenie below to see the issue in action.

<img width="1440" alt="screen shot 2018-06-04 at 17 20 58" src="https://user-images.githubusercontent.com/109826/40965609-7cb5ea50-68ae-11e8-9760-9df672706892.png">

Cheers,
Chris

**Comment by westonruter** [comment]
Hey Chris, the notice _inside_ the block should be because there are validation errors regarding just that block. The global notice at the top includes mention of those as well as issues outside the content as a whole. The global notice is dismissible but the block-level notice is not, at least not presently. 

The behavior currently should be that the global notice on the top appears after a saving when there is some change to the validation status of the URL. For example, if I add a Custom HTML block and it has some invalid `script` tag then the first time I save I see:

> ![image](https://user-images.githubusercontent.com/134745/40995826-1be32a6a-68b5-11e8-82cb-ed7431435d73.png)

If I then edit another block to not cause a new validation error to appear, then I see this:

> ![image](https://user-images.githubusercontent.com/134745/40995889-4575b078-68b5-11e8-8079-b2c4575d27cc.png)

Notice the Custom HTML block still has the validation warning notice, but that the global notification is not restored.

But if I then modify the Custom HTML block to edit the `script` tag and then re-save then I see the global notice again:

> ![image](https://user-images.githubusercontent.com/134745/40995943-7224e684-68b5-11e8-810f-c5fee8efd16d.png)

In any case, what you should do is click the Review Issues link in the initial notice to be taken to this screen and then Accept the validation error so it can be sanitized:

> ![image](https://user-images.githubusercontent.com/134745/40996002-97d93344-68b5-11e8-91c0-7cb08a49772e.png)

Once that is done, then the warnings at the block level and global levels will both be omitted:

> ![image](https://user-images.githubusercontent.com/134745/40996042-b6e3d672-68b5-11e8-8142-68774d0122f8.png)

Does this clarify the behavior? Is it not what you're seeing?

**Comment by devignerforhire** [comment]
Hi Weston,

That does clarify the behavior - thanks :) 

I'm not seeing the updated validation details screen, with the option to Accept/Reject validation issues, so guessing that isn't in the build I'm using yet. We did update the test site a while back, with the css tree-shaking, but I don't see any changes to the validation screen in that version either.

I'll ask Thierry for the latest build and see if that helps.

Cheers,
Chris

**Comment by westonruter** [comment]
Here too are instructions for building the plugin yourself: https://github.com/Automattic/amp-wp/blob/develop/contributing.md#creating-a-plugin-build

**Comment by devignerforhire** [comment]
Thanks Weston :) I just went through the steps and was able to create a new build. I tested the update on our dev install and it seems to work as expected now.
