### ISSUE TITLE
Polldaddy embed not working

### ISSUE THREAD

**Issue by vigneshsmarther** [Automattic/amp-wp#1214]
Polldaddy embed not works with amp plugin.

**Comment by westonruter** [comment]
@vigneshsmarther if I'm not mistaken, the embed currently renders as just a link to go take the poll, correct? Would you share the URL to an example on your site? I recall the issue is that the poll depends on JavaScript which is not allowed in AMP, so the link is a fallback. Maybe there would be a way for us to use an `amp-iframe` here.

**Comment by westonruter** [comment]
What is the snippet you're using to embed the poll? You should be using the `[polldaddy poll="..."]` shortcode as provided by the Polldaddy plugin, or else use the oEmbed URL.

**Comment by vigneshsmarther** [comment]
I have used oEmbed URL as follows: 

<script type="text/javascript" charset="utf-8" src="https://secure.polldaddy.com/p/10035026.js"></script>
<noscript><a href="https://polldaddy.com/poll/10035026/">Test</a></noscript>

**Comment by vigneshsmarther** [comment]
Can you please help me out for display this script using amp-iframe

**Comment by westonruter** [comment]
> <script type="text/javascript" charset="utf-8" src="https://secure.polldaddy.com/p/10035026.js"></script>

This is not an oEmbed URL. Try instead to put the bare URL as a paragraph in your content:

```
https://polldaddy.com/poll/10035026/
```

Or use the shortcode:

```
[polldaddy poll="10035026"]
```

You then should get at least a link to the poll.
