### ISSUE TITLE
Post Option Greyed Out

### ISSUE THREAD

**Issue by e11productions** [Automattic/amp-wp#1267]
I just noticed that the post option under AMP/General is greyed out. Is there any reason for this?

**Comment by postphotos** [comment]
Hi @e11productions - can you share a screenshot/your URL of where you're seeing this?

**Comment by e11productions** [comment]
In the first image, you can see that the "post" selection is greyed out, and in the second image, you can see that amp is enabled but there is nowhere to add content.

![1](https://user-images.githubusercontent.com/8783239/42952799-326ff1e6-8b47-11e8-9ad4-9c651bff7752.png)
![2](https://user-images.githubusercontent.com/8783239/42952800-327ba7e8-8b47-11e8-801e-0ba9ca26a508.png)

**Comment by westonruter** [comment]
> In the first image, you can see that the "post" selection is greyed out

It is greyed out because the checkbox is disabled. It is forcibly-enabled. This will change as of 1.0, however. In 1.0 you will be able to disable AMP for generic posts, though I don't know why this would done.

> and in the second image, you can see that amp is enabled but there is nowhere to add content.

There is no separate content field. When serving an AMP it uses the same content as the non-AMP page, but with some transformations to be valid AMP.
