### ISSUE TITLE
Playlist shortcode support

### ISSUE THREAD

**Issue by philipjohn** [Automattic/amp-wp#1279]
Although support for the core playlist shortcode was added in #954 I'm seeing a fairly unattractive implementation that doesn't match with what I see in that PR.

On a vanilla WP install I have a post with the following content:

```
[playlist ids="1709,1708,821"]
```

Which is rendered like so in twentyseventeen:

![rendered-playlist](https://user-images.githubusercontent.com/136342/43132716-808348f6-8f34-11e8-94b0-894fde2313fb.png)

The AMP (paired) playlist is rendered like so:

![amp-rendered-playlist](https://user-images.githubusercontent.com/136342/43132749-a0b10884-8f34-11e8-8832-9705e3ac6597.png)

It looks like maybe the styles are missing - snipped out by the transformer maybe?

**Comment by westonruter** [comment]
@philipjohn It looks like in this case the legacy templates are being used? I believe the support depends on AMP theme support because the MediaElement CSS needs to be enqueued. If you enable AMP theme support does it tender better? To add support for the legacy templates then the CSS from the external stylesheet would need to get fetched and output.
