### ISSUE TITLE
Pages Not possible to see AMP page  - but Posts is Ok.

### ISSUE THREAD

**Issue by mountin** [Automattic/amp-wp#1326]
Hello
I'm using Wordpress 4.8.9 and 4.9.0
I just tried your beautiful plugin Version 0.7.2 . But i had an issue.
I turned on All links to **domain/Post_name/amp/**

Pages Not possible to see AMP page  - but Posts is Ok. 
**Domain/Post_name/amp/** - works Perfect but
**Domain/Page_name/amp/** - will redirect to **Domain/Post_name/**

i have tried 3 different websites  -all same problem
Fox ex.
http://seofymx.dk/asdasd/amp - Page dont work
http://seofymx.dk/ddddw/amp/ - Post works well..
Is there  somebody could help me please...
Thansk

**Comment by westonruter** [comment]
Go to the AMP settings screen in the admin. Under General settings you will find the enabled post types. Make sure that you enable Pages. Note that the `amphtml` link for pages will end in `?amp` not `/amp/`.

**Comment by hellofromtonya** [comment]
@mountin As @westonruter noted above, the URL ends in `?amp` instead of `/amp/`.  Using the URLs you provided above, note that they do render in AMP mode:

http://seofymx.dk/asdasd/amp should be [http://seofymx.dk/asdasd/?amp](http://seofymx.dk/asdasd/?amp)

http://seofymx.dk/ddddw/amp/ should be [http://seofymx.dk/ddddw/?amp](http://seofymx.dk/ddddw/?amp)

When loading each of these URLs, notice that they are rendering in AMP mode.  We can see that when inspecting in the `Console` as it says:

>Powered by AMP ⚡ HTML – Version 1533253141109 http://seofymx.dk/ddddw/?amp

and

>Powered by AMP ⚡ HTML – Version 1533253141109 http://seofymx.dk/asdasd/?amp

Check it out.

**Comment by mountin** [comment]
Hello 
@westonruter  Yes it's already sat as Pages/posts in settings to amp http://prntscr.com/kgd4rd

**Comment by westonruter** [comment]
@mountin why? Google and other AMP consumers are only going to be looking at the `amphtml` link that is in the canonical page http://seofymx.dk/asdasd/:

```php
<link rel="amphtml" href="http://seofymx.dk/asdasd/?amp"></head>
```

You should always be looking at this link to determine what the AMP URL is for a given canonical page.
