### ISSUE TITLE
Mobile menu toggles not working in Astra Theme with AMP plugin v1.0-beta

### ISSUE THREAD

**Issue by alokshukla1510** [Automattic/amp-wp#1343]
I Installed AMP Plugin Release v1.0-beta1 on my beta version website https://www.taxochamber.com.
Mobile menu toggles not working in Astra Theme. Please help me to fix this issue.

**Comment by westonruter** [comment]
I believe this is actually a theme problem. First of all, the theme should not be presenting a mobile menu (hamburger button) if JS is disabled, which it effectively in AMP since all custom scripts are removed. So it should be showing a fallback menu instead.

To implement the mobile menu button in AMP, there are instructions in https://github.com/Automattic/amp-wp/wiki/Implementing-Interactivity#hamburger-menu-toggle
