### ISSUE TITLE
Using paired mode with a standard template enqueues all scripts

### ISSUE THREAD

**Issue by zandergrin** [Automattic/amp-wp#1370]
Not sure if I'm doing something wrong. 

I've added 
`
add_theme_support( 'amp', array(
  'template_dir' => 'templates/amp-templates/'
) );
`
to my functions.php but the page then throws out a load of validation errors - it's trying to enqueue all the scripts from my theme (with are added using wp_enqueue_script) and from plugins. What have I missed?

**Comment by jukefr** [comment]
Does your response contain the AMP sanitization headers ?
![](https://s3.eu-west-3.amazonaws.com/juke-github/Selection_085.png)

If yes then your scripts must be enqueued by some function that it does not know how to dequeue or a bug somewhere.
If not then you have a configuration problem.

**Comment by zandergrin** [comment]
I don't really know how to check the first questions...  going into network>headers I can't see anything like that 

The scripts I know of are enqueued using wp_enqueue function

I'm using
`
    function dequeue_some_scripts() {
      if (function_exists('is_amp_endpoint') && is_amp_endpoint()) {
        wp_dequeue_script('cycle2');
        wp_deregister_script( 'cycle2' );
`

etc to dequeue them in my functions - which is clearing some of the errors.
As far as I can tell there's no configuration!

**Comment by jukefr** [comment]
Try a flush of your rewrites (simply save permalinks once)
Check that AMP is enabled for the content type you are checking
There should be a "visit AMP" button on the admin bar on the right side if the plugin is activated and works correctly.

**Comment by westonruter** [comment]
@zandergrin In your AMP-specific templates you still have calls to `wp_head()` and `wp_footer()`—as you should—and so the normal WordPress scripts are being output just the same as on your non-AMP templates.

> etc to dequeue them in my functions - which is clearing some of the errors.
> As far as I can tell there's no configuration!

That's right. There is no UI for configuring which scripts should be dequeued. You're absolutely correct to be doing something like (you only need to dequeue; you don't need to de-register):

```php
add_action( 'wp_enqueue_scripts', function() {
    if (function_exists('is_amp_endpoint') && is_amp_endpoint()) {
        wp_dequeue_script('cycle2');
    }
}, 1000 );
```

The validation errors you're seeing are being reported inside the plugin and not by the AMP validator, correct? Then this is all working as it should be. The plugin is warning you about markup that your theme or plugins are adding to the page which are not valid in AMP. You need to decide whether or not the markup causing the validation errors is critical to the functionality of your site. If it is not critical, then you can mark a given validation error as “accepted” so it won't complain about it any longer. Otherwise, you can fix the underlying problem by dequeueing scripts to prevent them from causing the validation error to begin with, and at the same time you can provide any AMP-specific replacement functionality at the same time. See https://github.com/Automattic/amp-wp/wiki/Implementing-Interactivity

Otherwise, if you know that your AMP templates are going to be fine with all scripts being removed then you can just enable this option on the AMP settings admin screen:

![image](https://user-images.githubusercontent.com/134745/44744368-dbe9bb80-aab9-11e8-90cd-77454a601e08.png)

You'll still get notified of the validation errors, but they won't block AMP from being served (i.e. no redirect to the non-AMP version). You can then go to the AMP validation errors screen and just bulk-update all validation errors to be accepted to prevent the plugin from warning you about them:

![image](https://user-images.githubusercontent.com/134745/44744476-105d7780-aaba-11e8-8b19-9addf4f78ea2.png)

**Comment by zandergrin** [comment]
Correct, the issues are reported in the AMP plugin, the search console error was reporting some errors  which I'm fixing... but the https://validator.ampproject.org/ shows a pass.

> As far as I can tell there's no configuration!

Was a reference to the previous commenter saying I must have a configuration error...

I'm fairly certain the errors being shown by the plugins validation system aren't causing any issues, so I'm happy to ignore them... only thing is I must be on a previous version as I can't see the **accept** option, just **move to bin** or **recheck**. If I move to bin, they appear again on a  page save, and the error appears everywhere on the site (including for editors, not just admins) without the ability to dismiss.

Thanks for your detailed reply - good to know I'm doing "pretty much" the right thing.

**Comment by westonruter** [comment]
> only thing is I must be on a previous version as I can't see the accept option, just move to bin or rechec

There should be a “Details” link as well, like so:

![image](https://user-images.githubusercontent.com/134745/44831466-8b6a7f00-abdb-11e8-9b7d-b345f285d680.png)

Actually, this is present as of 1.0-beta so if you're on 0.7 then that is probably why you don't see it.
