### ISSUE TITLE
[1.x] request: Add a "fix" option for validation errors

### ISSUE THREAD

**Issue by jukefr** [Automattic/amp-wp#1379]
The way I understand it, when you validate a page :
1. if an issue is present it will get added to the "list" with a `New` status.
2. there is an option to `Accept`, which will act as if the error is not there and proceed with displaying the AMP page even if not Google-valid.
3. `Reject` will automatically redirect to the canonical version of the page (same as `New` pretty much)

Now I have not looked at the validation function you use to automatically force-sanitize the ouput, but would there be a way to use this function in conjunction with the error-report options to automatically force fixing of only specific AMP rules ?

So a 4th option `Fix` would be present, it would apply to the entire rule (maybe the specific instance of the problem, but entire rule might be more convenient) and would simply attempt to force-sanitize said rule is ever broken.

An example of how this could be used is in Paired mode. Some plugins include scripts and you might not want to add a new rule every time by hand in your functions.php

A validation report would show the `no-script` exceptions and you could select to `Fix` these by default.

Does this seem like it would be feasible/of any use ?

**Comment by amedina** [comment]
The `Accept` case tells the validation system that it is ok for the plugin to remove the piece of markup that is causing the validation error. The result is that the generated page will be AMP valid (since the error has been removed ) but there may be some functionality or visual parity loss. For example, if  a theme has some JS handling the hamburger menu, the validation system will reports an `invalid script` error;  if we `Accept` it, the plugin will get rid of the offending `<script>` tag, the page will be valid, but the hamburger menu won't work.

The `Reject` case prevents the plugin from removing the offending markup, maintaining the functionality of the page intact, but no AMP page will be served. 

The `Fix` option you are suggesting, corresponds to the case of selecting `Reject`  and having the developer of the site to fix the functionality causing the problem. In the above example this would correspond to providing an AMP valid implementation of the hamburger menu. This [wiki page](https://github.com/Automattic/amp-wp/wiki/Implementing-Interactivity) has several examples of such kind of fixes.

**Comment by westonruter** [comment]
> The Reject case prevents the plugin from removing the offending markup, maintaining the functionality of the page intact, but no AMP page will be served.

That's right. Reject means that in paired mode, the AMP version will always redirect to the non-AMP version. When you are in native mode, however, there is no other version to redirect to so “reject” here just means “I should fix this later”. In both paired and native modes, accept means that you're fine with invalid markup being stripped from the response. The plugin never allows for invalid AMP markup to be served, so if Google Search Console _should_ no longer be raising validation errors to you because they should never occur on the frontend of your site: the plugin captures them internally so you can deal with them in the context of your themes, plugins, and content.

Work is underway to make the validation screens more intuitive, including improved labelling for new/accepted/rejected validation errors.
