### ISSUE TITLE
How to get mobile devices to call up the amp version?

### ISSUE THREAD

**Issue by jamminjames** [Automattic/amp-wp#140]
Sorry if this sounds like a dumb question, but I've installed the plugin, and don't see in the readme file how to get mobile devices (and Google Webmaster) to see and use the /amp/ version of pages.

I do have 'pretty permalinks' set up, do I need to adjust it somehow? If I add /amp/ to the end, won't that affect my page rankings? Do I have to do a redirect? How would that affect desktop viewers?

**Comment by mjangda** [comment]
Not a dumb question; this is one of the confusing aspects of how AMP is supposed to work.

The idea is that "consumers" (i.e. apps like Twitter, Pinterest) will give preference to and display AMP versions of URLs if they exist. So when you tap on a link in the Twitter app, you'll see the AMP version of that link.

As a website publisher, you could, of course, auto-redirect mobile visitors to the AMP version of the page if you feel like that provides a better experience for your users. Unfortunately, I can't comment on how that would impact the page ranking aspect as I don't really know (you could argue that it might boost it since AMP pages are fast) :)

**Comment by jamminjames** [comment]
Okay, thanks. So, clicking on a twitter link to our site, I don't see /amp/ in the url, neither on a desktop nor a mobile device. Does it not show in the url? If not, how can we be sure it's working?

**Comment by j3j5** [comment]
It isn't fully supported by everybody yet, in fact, I think Google gave the first step when adding the AMP pages to their webmaster tools. Next step will be to show the AMP versions on the mobile search results and then, *in theory*, others will follow implementing it (Twitter and others). At the moment, Google Search Console is the best (if not only) way to know if your page is ready.

**Comment by jamminjames** [comment]
When I check on Google Webmaster's Accelerated Mobile Pages (https://www.google.com/webmasters/tools/accelerated-mobile-pages), it still says "We did not find any Accelerated Mobile Pages in your site" -- does it take time for them to recognize it, or?

**Comment by mjangda** [comment]
Would you mind sharing your URL? If you'd prefer to do it privately:
mo@automattic.com

**Comment by jamminjames** [comment]
Sure... http://www.humortimes.com/

**Comment by jamminjames** [comment]
I've updated to the new WP plugin, and still Google Webmaster is not confirming it. Is there something I need to do?
