### ISSUE TITLE
Syntax error in amp-translations.php can block deployments

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1416]
The `pot-to-php` script is used to generate an `amp-translations.php` file for WordPress.org to use for translations:

https://github.com/Automattic/amp-wp/blob/b3e1b4d07dda70c5070d30f7426f849eb3a39823/package.json#L34

However, the `amp-translations.php` file has a PHP syntax error with a spurious comma on line 6:

```php
<?php
/* THIS IS A GENERATED FILE. DO NOT EDIT DIRECTLY. */
$generated_i18n_strings = array(
	/* translators: Copyright (C) 2018 WordPress.com VIP, XWP, Google, and contributors
This file is distributed under the same license as the AMP plugin. */
,

	/* Plugin Name of the plugin */
	__( 'AMP', 'amp' ),
```

This syntax error doesn't cause a problem for the purposes of translating on WordPress.org since the file isn't actually executed, but rather the gettext function calls are just extracted.

However, the presence of this syntax error causes problems when attempting to deploy a build of the plugin to a hosting environment where PHP syntax checking is part of a `pre-receive` hook, so a git push can then fail. So far this is known to be an issue on WP Engine and it would also be a problem on WordPress.com VIP.

**Comment by westonruter** [comment]
@swissspidy I recall you mentioning that there was a syntax error previously and that it was a known issue. Is there any workaround you are aware of?

**Comment by swissspidy** [comment]
You're right. I noted this syntax error in https://github.com/Automattic/amp-wp/pull/1329#issuecomment-412333755 but didn't realize it could cause issues with deployments.

We might be able to work around this by using something like `wp i18n make-pot --file-comment=""`. I'll try this out.

Otherwise we could a) strip the comma after the file generation or b) fix the underlying problem in https://github.com/WordPress/gutenberg/blob/410f78a705a8aca2ca32a225383dc48cf47e0fe4/packages/i18n/tools/pot-to-php.js
