### ISSUE TITLE
get_post_format() returns false

### ISSUE THREAD

**Issue by anteksiler** [Automattic/amp-wp#1435]
get_post_format() returns false for me on featured-image.php and single.php

**Comment by westonruter** [comment]
What does it return for you instead?

**Comment by anteksiler** [comment]
I meant "false", it should return video, etc.

**Comment by westonruter** [comment]
Probably because the global `$post` is not set. This would be an issue with the plugin's classic post templates.

Aside: if you try the new AMP theme support in 1.0-beta then this won't be a problem since it reuses your active theme's templates and stylesheets.

See:
https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support
https://github.com/Automattic/amp-wp/releases/tag/1.0-beta3

**Comment by westonruter** [comment]
@anteksiler try adding this to your theme's `functions.php` or a custom plugin:

```php
add_action( 'pre_amp_render_post', function( $post_id ) {
    global $post;
    $post = get_post( $post_id );
} );
```
