### ISSUE TITLE
Provide method of discovering AMP URLs

### ISSUE THREAD

**Issue by joshbetz** [Automattic/amp-wp#1494]
In order to discover an AMP URL for a given article, it seems you have to use Google's AMP API. We could easily remove the need for that by making AMP URLs independently discoverable with:

* An HTTP header, like X-AMP-URL
* A `<link>` element in the document's `<head>`
* Specifying the AMP URL in RSS feeds and the REST API

**Comment by westonruter** [comment]
@joshbetz actually, there is already a `link` in the `head` for URLs that have an AMP version. For example on this non-AMP page: https://weston.ruter.net/2018/04/30/remember-me-easter-egg/

There is:

```html
<link rel="amphtml" href="https://weston.ruter.net/2018/04/30/remember-me-easter-egg/?amp">
```

So the AMP version is https://weston.ruter.net/2018/04/30/remember-me-easter-egg/?amp

This implements what is specified by the AMP project for discovery: https://www.ampproject.org/docs/fundamentals/discovery

Is that what you're looking for?

**Comment by joshbetz** [comment]
Aha, cool, I missed that. It would be cool if we also included it in RSS feeds and the REST API, though I understand that may not be part of the spec.

**Comment by westonruter** [comment]
Yeah, that could be useful. At the moment the way to determine the AMP version of a URL is to:

1. Fetch the canonical URL
2. If the `html` element has an `amp` or `⚡️` attribute, then short-circuit since AMP is canonical.
3. Locate the `link[rel=amphtml]` element and use its `href` as the AMP URL.
4. Otherwise, AMP is not available for a given URL.

The fact that a canonical URL can itself be AMP complicates the usefulness of having a separate link in RSS feeds or the REST API, as if AMP is canonical would this URL just be identical to the existing link?
