### ISSUE TITLE
Should errors be shown when paired mode takes care of it?

### ISSUE THREAD

**Issue by pacifier007** [Automattic/amp-wp#1502]
I have noticed every post shows error in paired mode even when it's being taken care by sanitizer and frontend is perfectly valid.

Whenever you add/edit a post, there's the:
`There is content which fails AMP validation. Non-accepted validation errors prevent AMP from being served, and the user will be redirected to the non-AMP version.`

However, it's completely valid output in paired mode. It just confuses the publishers.

**Comment by westonruter** [comment]
Are you using 1.0-RC1?

**Comment by westonruter** [comment]
@pacifier007 I think I see what you mean. When I have the auto-accept sanitization checkbox set, I am presented with this notice:

![image](https://user-images.githubusercontent.com/134745/46754569-a5d25680-cc77-11e8-8030-cd077015ef19.png)

Even though the new validation errors are being auto-accepted, the notice doesn't really make this fact clear. It should say something to the effect of:

> There is content which fails AMP validation. However, your site is configured to automatically accept sanitization of the offending markup. You should review the issues to confirm whether or not sanitization should be accepted or rejected.

👉 Importantly, a message needs to be shown to the user even when auto-accepted sanitization is enabled because they need to be informed of when there is markup being stripped out. To hide the notice, the user just has to click “Review issues” and then moderate the validation errors to all be accepted.

This message would also apply in native mode, where auto-accepted sanitization is forced. This message would be when there are any “new accepted” validation errors but all others have been moderated as accepted. There should also be a different statement when some of the validation errors are “new rejected” (such as when they were created when the auto-accept option was not enabled) or explicitly moderated as rejected.

This message update should be applied to the Gutenberg editor of course.

Here's a half-started patch which begins to apply some of the changes:

```diff
diff --git a/includes/validation/class-amp-validation-manager.php b/includes/validation/class-amp-validation-manager.php
index aed654ed..3dbc5f17 100644
--- a/includes/validation/class-amp-validation-manager.php
+++ b/includes/validation/class-amp-validation-manager.php
@@ -812,6 +812,7 @@ class AMP_Validation_Manager {
 		// Show all validation errors which have not been explicitly acknowledged as accepted.
 		$validation_errors = array();
 		foreach ( AMP_Validated_URL_Post_Type::get_invalid_url_validation_errors( $invalid_url_post ) as $error ) {
+			// @todo We should count each of these separately, as the message should vary based on which validation errors are present.
 			$needs_moderation = (
 				AMP_Validation_Error_Taxonomy::VALIDATION_ERROR_ACK_REJECTED_STATUS === $error['status'] || // @todo Show differently since moderated?
 				AMP_Validation_Error_Taxonomy::VALIDATION_ERROR_NEW_REJECTED_STATUS === $error['status'] ||
@@ -834,8 +835,10 @@ class AMP_Validation_Manager {
 		echo ' ';
 		if ( amp_is_canonical() ) {
 			esc_html_e( 'Non-accepted validation errors prevent AMP from being served.', 'amp' );
-		} else {
+		} elseif ( ! self::is_sanitization_auto_accepted() ) {
 			esc_html_e( 'Non-accepted validation errors prevent AMP from being served, and the user will be redirected to the non-AMP version.', 'amp' );
+		} else {
+			esc_html_e( 'However, your site is configured to automatically accept sanitization of the offending markup. You should review the issues to confirm whether or not sanitization should be accepted or rejected.', 'amp' );
 		}
 		echo sprintf(
 			' <a href="%s" target="_blank">%s</a>',
```

**Comment by kienstra** [comment]
**Does the PR address your points?**

Hi @pacifier007,
Thanks for bringing up the need for better notices.

Does PR #1676 address your points here?
