### ISSUE TITLE
Featured image not used by default template

### ISSUE THREAD

**Issue by gnotaras** [Automattic/amp-wp#152]
Hello,

I noticed that the featured image is not displayed in the generated amp page by default. Searched the open and closed issues but found no information. Is this intentional or is it a bug?

If this is intentional, I assume that this question is going to be asked several times. So, maybe the readme should contain a template customization example which inserts the featured image into the amp page.

George

**Comment by mjangda** [comment]
Yep, this is intentional. Adding a readme example is a good idea.

**Comment by gnotaras** [comment]
Great! That would be nice!

**Comment by mjangda** [comment]
Just for posterity: the reason we don't include the featured image automatically is because different themes/sites handle the featured image differently (and we can't easily guess at how they're using it). In some cases, the feature image is often the same as an image included within the post (e.g. photoblogs) and that ends up with the image displayed twice which looks pretty bad.

**Comment by gnotaras** [comment]
I see. Thanks for the information and for the example. Much appreciated!
