### ISSUE TITLE
Google Webmaster says no accelerated pages found

### ISSUE THREAD

**Issue by jamminjames** [Automattic/amp-wp#154]
I've updated to the new WP plugin, and still Google Webmaster says "We did not find any Accelerated Mobile Pages in your site." Is there something I need to do? http://www.humortimes.com/ ... I flushed the cache. I use Cloudflare, would that make a difference? Tried pausing it, didn't change anything.

**Comment by mjangda** [comment]
I don't see the `<link rel="amphtml" ...` tag in the source of your posts. And the AMP template doesn't load either when I append `/amp/` to a permalink.

Have you made any modifications to the plugin? Or have you added any code that hooks in to any AMP actions?

**Comment by jamminjames** [comment]
No, no modifications or hooks.

**Comment by gnotaras** [comment]
> I've updated to the new WP plugin, and still Google Webmaster says [...]

I guess it will take much more time than the 2-3 days since the 0.2 release of amp-wp before any relevant information appears in the GWT. IIRC, when `hreflang` was introduced, it took some weeks before the changes were reflected in the GWT interface and also it had happened gradually and not in one go for all web pages.

George

**Comment by emaurin** [comment]
template loadeither when I append /amp/, but i don´t see the <link rel="amphtml" ... tag in the source of posts

http://www.venezuelasinfonica.com/la-sinfonica-municipal-ofrecio-elfinde
http://www.venezuelasinfonica.com/la-sinfonica-municipal-ofrecio-elfinde/amp
