### ISSUE TITLE
Twenty Nineteen: Featured image in post list does not appear properly

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1656]
The featured image used appearing on a post list such as at https://2019-theme.amp-wp.org/ does not render properly:

![image](https://user-images.githubusercontent.com/134745/49044879-ffd59f80-f183-11e8-97ad-86a3d844fcab.png)

There is an unexpected gap in the right side of the image.

See https://2019-theme.amp-wp.org/

**Comment by kienstra** [comment]
**Question About Multidev Site**

Hi @westonruter,
It looks like https://2019-theme.amp-wp.org/ is running `1.0-RC2`. I can't reproduce this locally with `1.0`, but it does appear with `1.0-RC2`.

Would you have access to update the plugin on the multidev site? This might have been fixed by https://github.com/Automattic/amp-wp/commit/d7de7d17bd769d55e5adf95e0b6b2723c0d4932b in https://github.com/Automattic/amp-wp/pull/1627.

**Comment by westonruter** [comment]
Sure enough! I pushed up a new build of `1.0` including changes from RC3 and I don't see the problem anymore. 😅

**Comment by kienstra** [comment]
Nice, thanks!

**Comment by westonruter** [comment]
This is being revisited in #2036.

**Comment by kienstra** [comment]
That's great!
