### ISSUE TITLE
RC3 - Structured Data Error

### ISSUE THREAD

**Issue by mddsharpp** [Automattic/amp-wp#1659]
On v1RC3 I get valid AMP but errors on structured data (SD). On the non-AMP test there is 1 entry for for article but on the AMP SD there are two article entries, one with an error and one without. Here is a URL you can test SD on on for non-AMP and AMP.

https://ccountync.com/morehead-city-used-game-consoles-for-sale-nc-xbox-nintendo-playstation-wii/

**Comment by westonruter** [comment]
It seems to be an issue with Phil Singleton's WP SEO Structured Data Plugin in that it outputs the Schema.org metadata in the footer, whereas the AMP plugin outputs it in the head. 

The AMP plugin actually tries to prevent prevent outputting its own metadata if there is already a `script` on the page, but the problem is that it currently is only looking inside the `head` for such an element:

https://github.com/Automattic/amp-wp/blob/b748977321cc3769d0476ceede56c39aa2fed267/includes/class-amp-theme-support.php#L1185-L1189

So it seems the plugin needs to be updated to look at the entire document instead.

**Comment by westonruter** [comment]
@mddsharpp See https://github.com/Automattic/amp-wp/pull/1664
