### ISSUE TITLE
Issues returning to edit AMP stories after logging out and back in

### ISSUE THREAD

**Issue by alcurrie** [Automattic/amp-wp#1688]
**Issue: Errors display in the AMP stories editor AMP stories after logging out and back in**

Once I log in and out of editing I am still getting the errors. Also the screen of the storyboard is displaying the add image in the thirds layer oddly… here are 2 screenshots. I can’t leave editing currently or else I get the error…  And upon returning to edit - the block editor is missing…  this is new
https://canddstudios.d.pr/SZIpxU
https://canddstudios.d.pr/ouIxgU

This can be tested/checked in https://amp-stories-ampconfdemo.pantheonsite.io/wp-admin/post.php?post=1190&action=edit

NB: this was reported by @cathibosco in testing today

**Comment by miina** [comment]
Fixed within #1690.

**Comment by alcurrie** [comment]
I was able to reproduce the same errors/issues in testing this evening. Try and create a more concise screenscast but this shows the overall process. https://cl.ly/579908b9652d

**Comment by miina** [comment]
@alcurrie The specific issues that Cathi reported should be fixed -- one part of the issue was related to animations and the other to block navigation not being visible.

However, there are other things that are not working properly, such as using italic and alignment with paragraph -- it would probably need thorough QA on all the features and settings and then logging those specifically depending on which feature breaks the editor, it would probably be more systematic and better to test later instead of keeping this ticket for all the issues. Thoughts?

**Comment by alcurrie** [comment]
@miina - Cathi went through a fairly extensive test process preparing the demo, and we have captured issues found in issues resolved in this project or to be tracked for consideration for a future 'beta' iteration. 

I've confirmed creating, previewing and publishing an AMP story:
https://cl.ly/40ce2a005e4b
Navigating back in to edit an AMP story it's no longer showing the error messages.
https://cl.ly/3963c21ac882
