### ISSUE TITLE
Add filters and/or templates to make altering of the output possible

### ISSUE THREAD

**Issue by mstrehse** [Automattic/amp-wp#1695]
Is it possible to add some templates or filters for e.g. the rendering of the amp-gallery-embed or the other amp tags, so that you can add captions to the images inside a amp-carousel image gallery? I think the gallery is renderes inside the *includes/embeds/class-amp-gallery-embed.php* inside the *render()* function, using the AMP_HTML_Utils. A filter to alter the rendering array would be nice. Another approach would be to do the rendering inside a template which you can overwrite in your own theme. I realy like the plugin but it would be nice to have some way to alter the functionality.

**Comment by westonruter** [comment]
Have you tried 1.0? The [RC4 pre-release](https://github.com/Automattic/amp-wp/releases/tag/1.0-RC4) is available now but we are going to release 1.0.0 later today.

If you switch to the new paired or native modes, then WordPress's own default gallery shortcode will be used.

Otherwise, you can just use the `post_gallery` filter to override the gallery to render whatever you like.
