### ISSUE TITLE
Branding PR

### ISSUE THREAD

**Issue by tlovett1** [Automattic/amp-wp#174]
Hey All,

10up is seeking an AMP plugin solution for clients. We love the simplicity and extensibility we are seeing in this project so far. However, we want whatever we recommend to clients and use to be branding agnostic and powered by the customizer so clients aren't forced into making customizations.

Would Automattic be open to PRs that does the following? If so, 10up would love to contribute to the project.
* Remove default WordPress.com styles and branding.
* Add customizer functionality for choosing basic site colors and logo for AMP views.

**Comment by mjangda** [comment]
> Remove default WordPress.com styles and branding.

Sure, open to suggestions on how we could make it more generic. We mainly wanted something in place that looks good across most blogs. We will likely end up removing the WordPress logo since that seems to be a pretty contentious thing :)

> Add customizer functionality for choosing basic site colors and logo for AMP views.

That'd be pretty great! We've been trying to avoid adding extra options and pulling from existing functionality wherever possible (e.g. Site Icon) but will likely need a few additional options. It'd be good to discuss specifically what options we're adding to make sure we have the right balance before a PR.

Let's split this off into two separate issues to discuss?

**Comment by tlovett1** [comment]
Will do! Thanks Mo.

**Comment by mjangda** [comment]
:raised_hands:
