### ISSUE TITLE
Plugin Either Poorly Planned or Still Very Early

### ISSUE THREAD

**Issue by Acebravo99** [Automattic/amp-wp#185]
It seems this plugin is either poorly planned/managed or is still in its very early stages. Is there a road map for this plugin? what would the final product look like/have?

Just by adding code to the readme file is not the way to go, there's going to be a lot of people using this plugin who don't know PHP/coding.

Please set a road map for the plugin and what is the intended final product going to be so we don't waste time waiting for it.

Probably better to create a configuration page for this plugin so people can choose options by checking/unchecking boxes, for example: is the plugin going to be used as the default BlogPosting or NewsArticles. You want to use the featured image or not etc...

**Comment by Volnus** [comment]
To be fair AMP isn't even required at this point nor does it have a ranking boost effect. While its important to adopt the latest technologies keep in mind this is the first sort of plugin like this for WordPress and that it does require time.

AMP is also something that is not meant to be drag and drop, easy for everyone that will take even  more time. AMP is finally getting pushed towards the mainstream developers so its' easy to say create a configuration page or create a roadmap while developers are sort of just now playing with AMP.

You shouldn't expect to see it widespread for a few years. So let it be patient not everyone needs AMP right now, its not a major concern and just let developers play with it for a while. 

- Sincerely, Scott

**Comment by j3j5** [comment]
@Acebravo99 You could code it yourself instead of complain and demand like you are paying for this. You like it? Use it! You don't? Don't use it! 

I don't think to come here to open an issue and make demands like if these were your clients is what open source is about. This plugin is obviously in its early stages, as is the technology which is trying to implement. 

A more mature (and productive) attitude would be to start filling your recently created github profile with some code by adding all that functionality you are missing from this plugin, or at least, not to come here with all these demands as if the people making this plugin worked exclusively for you.

**Comment by Acebravo99** [comment]
@j3j5 typical idiots "presumptions" ! 

>>like if these were your clients??? where did you learn your English??

Enough said, crawl back under your "designated" rock and keep quiet!

**Comment by j3j5** [comment]
Aha, very well, keep adding your valuable contributions to the community. Thanks to you (and the people like you) this will continue a better place to be in. You can expect many improvements as soon as you keep asking for them like this.

**Comment by mjangda** [comment]
Thanks for the feedback. The plugin definitely is in its early stages, just like the AMP project :) Our initial goal has been mostly to lay the groundwork with a good default template and a powerful developer-focused API. The neat thing is that with this API in place, we can easily add UI-based controls in the Customizer for quick and easy tweaks so you'll see those added  in the future.

Let's also keep the discussion civil and constructive, everyone.
