### ISSUE TITLE
Improve extract_by_downloading_image

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#193]
#191 does an okay job of handling dimension fetching for images. We can probably improve it using `curl` (e.g. https://github.com/willwashburn/FasterImage) and implement better tests.

**Comment by pdufour** [comment]
Hi just noticed this comment in the code https://github.com/Automattic/amp-wp/blob/6879e7d98e804924b0567baa77d9d189890a991d/includes/utils/class-amp-image-dimension-extractor.php#L105 and then found this issue.

We are having timeouts on AMP pages because of all the downloading of images that happens for older posts that don't have width & height attributes. Would you accept a PR if I create a branch to switch over to FasterImage?

**Comment by mjangda** [comment]
The main concern is that it requires PHP 5.4 so we'd need to do proper
checks to avoid fatals on older versions and keep the current library
around for those cases as well.

We also need to review fasterimage for any issues (e.g. security).

**Comment by mjangda** [comment]
@pdufour all that to say, yes, a PR would be accepted (and appreciate) as long as we still keep fastimage around for < PHP5.4.

**Comment by pdufour** [comment]
Thanks, I might be able to pick this up.
