### ISSUE TITLE
Easier Templating

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#23]
We should make it easier to swap in your own template to allow for customization of styles, layout, header/footer, etc.

**Comment by jbenton** [comment]
I understand the desire for constraint, but for those of us in publishing at least, the ability to build our own custom AMP'd templates would be a very big deal. Custom fonts, headline treatments, and such would be necessary for brand unity and adoption. My two cents!

**Comment by mjangda** [comment]
Current thinking for this:

- Switch to very simple handlebars-style templates with data passed in (`[ 'post_title' => 'Hello AMP' ]` passed to `<p>{{post_title}}</p>` will end up `<p>Hello World</p>`)
- The template file and data will be filterable

Need to think about how/where to do escaping (will be passing a bunch of unescapable / unksesable content in data).

It would be nice to support easy reuse of boilerplate code like the main amp script and opacity style block. Recursive templates? Or maybe just pass as data?

More imporantly, though, need to decide if this logic-less template approach is worth it or if we should stick to the PHP-laden ones or another alternate approach.

**Comment by jasmussen** [comment]
:+1:

**Comment by maxhartshorn** [comment]
There should be some method for including a custom template.php. I understand the desire for simplicity and compatibility, but keep in mind that AMP'd pages could (rather quickly) become the primary way users view publisher's articles on the mobile web. Publishers will want the same control over their AMP templates that they have over their themes, and I don't see how this can be achieved via a logic-less handlebars-style approach.

There is a very minimal amount of templated code that must be included, mostly in the <head>, but after that I could see almost all template.php changing in order to meet custom design needs of different publishers. This is the benefit of AMP over instant articles isn't it? That publishers have some control over the look and feel of their sites.

In any case the actual front-end AMP spec is quite limiting as is, why limit back-end development as well?

**Comment by j3j5** [comment]
I agree with @maxhartshorn . A method for custom template.php is a mandatory requirement for any serious publisher, maybe the approach of #34 or any other, but full control over the template is a must.

**Comment by j3j5** [comment]
What about a way to make the themes _amp compatible_? `amp.php` could check whether the current theme is _amp compatible_ (checking for `/amp/template.php` or something along the lines) and otherwise fallback to the plugin's template (which still could be somehow customizable through the web UI, maybe with this handlebars-like templating system proposed above). Just my 2cents, but I think full control over the template should be, at least, possible when using the plugin.
