### ISSUE TITLE
Insert featured image in single.php

### ISSUE THREAD

**Issue by overpress** [Automattic/amp-wp#259]
Hi, how can I make the featured image show in the file single.php? 

We know you can do with the file functions.php but we would like to insert the featured image in single.php.

**Comment by smhmic** [comment]
I think this functionality should be built into the plugin, since it automatically pulls the featured image into the schema markup.  According to the [AMP docs](https://github.com/ampproject/amphtml/blob/master/examples/metadata-examples/article-json-ld.amp.html):

> Some platforms that use AMP HTML [require that] the leader image referenced in the markup must appear somewhere on the AMP HTML document itself.

But for now, this would get you the url, width, and height of featured image:  `wp_get_attachment_image_src( get_post_thumbnail_id( $this->get( 'post_id' ) ), 'full' )`

**Comment by overpress** [comment]
Thanks for the reply @smhmic. And how do I enter in the file single.php?

**Comment by HammyHavoc** [comment]
Seconding adding this into the plugin itself, at least as a selectable option for those who want it.

**Comment by overpress** [comment]
I did not understand :(

**Comment by portalzine** [comment]
I added a fallback to my AMP pages, if no image was available. Used the featured image example and used wp_get_attachment_image( $attchament_id_of_fallback_image, 1280) ) to link the image.

I than extended the amp_post_template_metadata filter to include that file as well.

` if(empty($metadata['image'])){

    $metadata['image'] = array(
        '@type' => 'ImageObject',
        'url' => wp_get_attachment_url($attchament_id_of_fallback_image),
        'height' => 160,
        'width' => 1280,
    );
  }`

**Comment by mjangda** [comment]
Dupe #327
