### ISSUE TITLE
Multiple instances of a unique tag

### ISSUE THREAD

**Issue by OPPtester** [Automattic/amp-wp#311]
Not sure what to make of it, but getting this in WMT:

**Multiple instances of a unique tag:**	boilerplate (noscript) - old variant, boilerplate (js enabled) - old variant, noscript enclosure for boilerplate

**Here's what I have in the AMP page:
**
<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

**Comment by jery61007** [comment]
did you try validating your page on browser by adding #development=1  at the end of the url ?? what does the developer console say? I got so many of them before and now it is gradually going away from Webmaster Tool once I updated the custom single.php file.. most of such warning I have are successfully validated on browser console and I can see those errors going away from WMT and numbers of indexed pages increasing..   did you customize your amp page with separate single.php template file from old version of the plugin and you forgot to remove the old boilerplate style from the customized version of your single.php, which since version 0.2 the plugin adds via ''amp_post_template_head"  ??   So no longer the boilerplate style in the custom single.php file is needed .. you need to remove it... just read this article [Customize AMP for WordPress ](http://techprezz.com/2016/02/wordpress-amp-customize-accelerated-mobile-pages-add-google-analytics-adsense-code/)  ....  hopefully it helps...

**Comment by jery61007** [comment]
I think even Webmaster Tool's validation system is not that perfect either 

I have got this error for some pages  "Invalid attribute values:	type=application/ld+json, rel=canonical, src=https://cdn.ampproject.org/v0.js"

when I checked the source code of the page, there is <link > tag with rel=canonical attribute immediate above the <script > tag that with src=https://cdn.ampproject.org/v0.js"   and Webmaster Console is telling me that the rel=canonical is wrongly placed in the script tag... even though that is actually in the <link > tag ...   weird behavior... !! so  I think your problem will go away unless the issue is what mentioned above ....

**Comment by OPPtester** [comment]
Developer console is successful of course, I just thought there was something else, but it seems WMT is being picky. As we go on, I'm sure things will improve from their end as well.

**Comment by jery61007** [comment]
That is good... Then you don't need to worry about it, just flush the old caches if you use any caching plugin and  the error on Webmaster Console will gradually go away.....

**Comment by mjangda** [comment]
Can you share a URL to an AMP page?

**Comment by OPPtester** [comment]
Sure here's one:

http://www.opptrends.com/2015/07/gopro-inc-gpro-second-quarter-results-exceed-consensus-estimates/amp/

**Comment by mjangda** [comment]
Checking with the in-browser validator, things turn up fine: http://www.opptrends.com/2015/07/gopro-inc-gpro-second-quarter-results-exceed-consensus-estimates/amp/#development=1

```
AMP validation successful.
```
