### ISSUE TITLE
Missing and required - publisher logo + name missing

### ISSUE THREAD

**Issue by TR-DK** [Automattic/amp-wp#349]
After the latest update (0.3.2) 99% off all post is now reporting error in Google Console.

Using Structured Data Testing Tool:

http://www.torbenrick.eu/blog/culture/why-is-organizational-culture-change-difficult/amp/

publisher [Organization]:
logo:
missing and required
name:
missing and required

How to fix that?

AMP version - 0.3.2
Glue for Yoast SEO & AMP - 0.3.2

**Comment by jery61007** [comment]
Hey just add this to your functions.php  

`add_filter( 'amp_post_template_metadata', 'amp_modify_json_metadata', 10, 2 ); // Adding custom metadata
function amp_modify_json_metadata( $metadata, $post ) {
  
   if( 'post'=== $post->post_type  ){
  
    $metadata['@type'] = 'Article';

    $metadata['publisher']['logo'] = array(
        '@type' => 'ImageObject',
        'url' => get_stylesheet_directory_uri().'/YOUR FOLDER NAME/YOUR LOGO NAME.png',
        'height' => 60,
        'width' => 250,
    );
  
   return $metadata; 
     
  } 
}`

**Comment by TR-DK** [comment]
Thanks - But where to add that in the functions.php?

Does this solve the problem with 

publisher [Organization]:
name:
missing and required

?

**Comment by jery61007** [comment]
anywhere after <?php  in the functions.php file of your theme  and yea it should fix the problem

**Comment by TR-DK** [comment]
Done that - but a test

http://www.torbenrick.eu/blog/strategy/the-importance-of-organizational-alignment/amp/

name:
missing and required

Where to add "name" in the code? Or?

Thanks

**Comment by jery61007** [comment]
I have updated the code, just copy and paste it .. it is supposed to add the name of your blog automatically but idk what is going on....  you might not have added that on your wordpress general settings area....

**Comment by TR-DK** [comment]
WOW - BIG THANKS :-)

**Comment by ustechera** [comment]
wordpress amp logo missing (only logo) so , can u please guide me how to resolve it 

http://ustechera.com/skype-a-once-reliable-communication-tool-is-falling-from-grace/amp/

thanks in advance.

![dd](https://cloud.githubusercontent.com/assets/18269051/14257936/c4c49960-fabd-11e5-9503-4b8915c8f57b.JPG)

**Comment by KonstantinSchubert** [comment]
Won't this be overwritten by the next wordpress update?

**Comment by sadanandkasukurthi** [comment]
Super thanks to jery61007, from the last 4 days I am suffering by the issue publisher name & logo for my amp page http://www.digitalmediarole.com/monitor-major-google-analytics-reports/amp/. I have updated the above code in functions.php, now structured data tool is showing 0 errors. Thanks a lot!

**Comment by Codeeboy** [comment]
@jery61007  Hi jerry i put the above code in functions.php in theme file but still the error showing "A value for the logo field is required.", what can i do , can you help me plz.. my website is http://akshyaa.com/
thanks in advance

**Comment by waqarfakecrow** [comment]
Thanks that works cheers

**Comment by dianne92** [comment]
The height of the logo image should be exactly 60px or maximum. The thing is I added that code into the functions.php and I'm still getting the same error.  Also, as KonstantinSchubert pointed out, won't this be overwritten the next wp/theme update ?

Can anyone take a look @ my website and tell me what I am doing wrong and why I keep getting this error if I followed those steps correctly? [https://www.hlbenefits.com/health-benefits-pulses-superfood-future/amp/](https://www.hlbenefits.com/health-benefits-pulses-superfood-future/amp/)

**Comment by jery61007** [comment]
Hey guys whenever you edit your template or functions.php file, you should only do it in child theme otherwise everything will be wiped off in the next theme update. For a step by step customization, follow the link I shared in my previous comment then you have nothing to fear.. everything will work like a charm if you follow the tutorial .....   Yea you need to use earlier version of AMP plugin until you finish the customization based on the tutorial.....  then you can update the plugin..

Thanks!

**Comment by Stormdiscount** [comment]
Good day, 

Concernig Structured Data:
I have an issue that the Publisher Logo has no value set when tested with the google structured data test.

I wrote an detailed problem discription including images on https://wordpress.org/support/topic/google-structured-data-publisher-logo-no-value-set/
Press read for full problem discription.

But i did not receive a reply there. On every url i get the LOGO error. Both for regular and AMP pages

http://www.mijngps.com/2017/06/21/geofence-gps-tracker-horloge-sos/
http://www.mijngps.com/2017/06/21/geofence-gps-tracker-horloge-sos/amp/

Running Wordpress 4.8
SCHEMA: 1.6.5
AMP: 0.9.53

So any detailed sugestion on how to set the value for Publisher logo is much appriciated.

**Comment by MohammedKaludi** [comment]
Hey @Stormdiscount 

I have just checked your site (http://www.mijngps.com/2017/06/21/geofence-gps-tracker-horloge-sos/amp/) and found out that you are using AMPforWP plugin.

In AMPforWP plugin there is a separate settings panel for Structured Data. http://take.ms/dZDsL
There is also a logo uploader option, from where you can add a logo for Structured Data. 

I'm sure after setting up the proper SD details will fix all your SD issues in AMP.

Thank You,
Mohammed Kaludi
Lead Dev and Co-Founder AMPforWP

**Comment by Stormdiscount** [comment]
Good Day Mohammed,

First off, thank you very much for you reply. Indeed you where correct that i had not set the Logo for AMP.

But now that i have set the Publisher logo for AMP, the value is still empty when checked with google. Just as with non amp structured data (where i already did set the Logo). Please see the image.

![amp-structured-data](https://user-images.githubusercontent.com/29622864/27431435-d31bc9ec-574c-11e7-825d-3b9fb302b8a7.jpg)

P.s.
I cleared all cache after editing to make sure.

Your help is much appriciated

Thank you.

**Comment by Stormdiscount** [comment]
Mohammed, i did find the solution. Please read the orginal topic for the solution.

https://community.mythemeshop.com/topic/78256-point-google-structured-data-publisher-logo-error/

Thanks again for your help.

**Comment by MohammedKaludi** [comment]
Hey @Stormdiscount 

I'm glad that you found the solution. 

Thank you for using our plugin,
Mohammed Kaludi

**Comment by Nik273** [comment]
After pasting your code most of the errors and warning was resolved. Big thanks for that. But after that I received this: 
#JSON-LD  Missing '}' or object member name on * (Problem Shows Here) add_filter.

This was my complete code:


<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "6 Authentic Secret Life Rules You Should Stop Ignoring Right Now",
  "author" : {
    "@type" : "Person",
    "name" : "Nik"
  },
  "datePublished" : "2018-05-26",
  "image" : "https://2.bp.blogspot.com/-U6C1dlmerH0/WwlAOc9-QeI/AAAAAAAAK8s/4DHQaCDMoUcOF_8uQSpqSFvbOiBwbs1lwCLcBGAs/s640/MILLENIALTHING.jpg",
  "articleBody" : "Do you want to run away from your past? </SPAN><BR/>\n<SPAN style=\"font-family: inherit;\"><SPAN style=\"font-family: inherit;\">What others think about you is your prior concern?</SPAN></SPAN><BR/>\n<SPAN style=\"font-family: inherit;\"><SPAN style=\"font-family: inherit;\">How your friends are getting success in spite of putting the same effort?",
  "url" : "https://successrecepies.blogspot.in/",
  "publisher" : {
    "@type" : "Organization",
    "name" : "Success Recepies"
  },
 *(Problem Shows Here) add_filter( 'amp_post_template_metadata', 'amp_modify_json_metadata', 10, 2 ); // Adding custom metadata
function amp_modify_json_metadata( $metadata, $post ) {
   if( 'post'=== $post->post_type  ){
    $metadata['@type'] = 'Article';
   $metadata['publisher']['name'] = ' TORBEN RICK ';
    $metadata['publisher']['logo'] = array(
        '@type' => 'ImageObject',
        'url' => get_stylesheet_directory_uri().'/YOUR FOLDER NAME/YOUR LOGO NAME.png',
        'height' => 60,
        'width' => 250
    ),
   return $metadata; 
  } 
}
}
</script>
Kindly reply asap. Trying since long time :(

**Comment by Hoodlum-Z** [comment]
Is your problem the ) instead of } on the fifth line from the bottom?

**Comment by gi0mix** [comment]
`   "publisher": {
    "@type": "Organization",
    "name": "Google",
    **"logo": {
      "@type": "ImageObject",
      "url": "https://google.com/logo.jpg"**
    }
  },
`
This IS the only acceptable syntax for the Publisher structured data, note that you are missing information about the logo.

Note that you shouldn't paste php inside json. 
Try to paste the PHP code inside the function.php
in the theme editor


> After pasting your code most of the errors and warning was resolved. Big thanks for that. But after that I received this:
> 
> > #JSON-LD  Missing '}' or object member name on * (Problem Shows Here) add_filter.
> 
> This was my complete code:
> 
> ```
> 
> <script type="application/ld+json">
> {
>   "@context" : "http://schema.org",
>   "@type" : "Article",
>   "name" : "6 Authentic Secret Life Rules You Should Stop Ignoring Right Now",
>   "author" : {
>     "@type" : "Person",
>     "name" : "Nik"
>   },
>   "datePublished" : "2018-05-26",
>   "image" : "https://2.bp.blogspot.com/-U6C1dlmerH0/WwlAOc9-QeI/AAAAAAAAK8s/4DHQaCDMoUcOF_8uQSpqSFvbOiBwbs1lwCLcBGAs/s640/MILLENIALTHING.jpg",
>   "articleBody" : "Do you want to run away from your past? </SPAN><BR/>\n<SPAN style=\"font-family: inherit;\"><SPAN style=\"font-family: inherit;\">What others think about you is your prior concern?</SPAN></SPAN><BR/>\n<SPAN style=\"font-family: inherit;\"><SPAN style=\"font-family: inherit;\">How your friends are getting success in spite of putting the same effort?",
>   "url" : "https://successrecepies.blogspot.in/",
>   "publisher" : {
>     "@type" : "Organization",
>     "name" : "Success Recepies"
>   },
>  *(Problem Shows Here) add_filter( 'amp_post_template_metadata', 'amp_modify_json_metadata', 10, 2 ); // Adding custom metadata
> function amp_modify_json_metadata( $metadata, $post ) {
>    if( 'post'=== $post->post_type  ){
>     $metadata['@type'] = 'Article';
>    $metadata['publisher']['name'] = ' TORBEN RICK ';
>     $metadata['publisher']['logo'] = array(
>         '@type' => 'ImageObject',
>         'url' => get_stylesheet_directory_uri().'/YOUR FOLDER NAME/YOUR LOGO NAME.png',
>         'height' => 60,
>         'width' => 250
>     ),
>    return $metadata; 
>   } 
> }
> }
> </script>
> ```
> 
> Kindly reply asap. Trying since long time :(

**Comment by Hoodlum-Z** [comment]
`{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "6 Authentic Secret Life Rules You Should Stop Ignoring Right Now",
  "author" : {
    "@type" : "Person",
    "name" : "Nik"
  },
  "datePublished" : "2018-05-26",
  "image" : "https://2.bp.blogspot.com/-U6C1dlmerH0/WwlAOc9-QeI/AAAAAAAAK8s/4DHQaCDMoUcOF_8uQSpqSFvbOiBwbs1lwCLcBGAs/s640/MILLENIALTHING.jpg",
  "articleBody" : "Do you want to run away from your past? </SPAN><BR/>\n<SPAN style=\"font-family: inherit;\"><SPAN style=\"font-family: inherit;\">What others think about you is your prior concern?</SPAN></SPAN><BR/>\n<SPAN style=\"font-family: inherit;\"><SPAN style=\"font-family: inherit;\">How your friends are getting success in spite of putting the same effort?",
  "url" : "https://successrecepies.blogspot.in/",
  "publisher" : {
    "@type" : "Organization",
    "name" : "Success Recepies"
  }
}`


The above code is for your JSON LD. I've checked it using **https://json-ld.org/playground/**

The code below goes in your functions.php, as explained. Preferably in your child theme so it doesn't get overwritten when you update your theme.

If you haven't got a child theme - make one easily with Child Theme Configurator plugin for WordPress. 

Alternatively, use WordPress hooks for code modifications. You also need to understand comments

// this is an inline comment.

/* this is a multi-line comment
as an axample. Keep comments out of your JSON file and only use them in your php, html, etc.
*/

You can find code checkers for almost anything if you Google them - minifier, unminifier, etc.

Common problems with PHP and JSON are missing/extra brackets, commas instead of semi-colons, etc.

Add the code below to functions.php as discussed. I've checked it using **https://phpcodechecker.com/**

Hope this helps.

`add_filter( 'amp_post_template_metadata', 'amp_modify_json_metadata', 10, 2 ); // Adding custom metadata
function amp_modify_json_metadata( $metadata, $post ) {
   if( 'post'=== $post->post_type  ){
    $metadata['@type'] = 'Article';
   $metadata['publisher']['name'] = ' TORBEN RICK ';
    $metadata['publisher']['logo'] = array(
        '@type' => 'ImageObject',
        'url' => get_stylesheet_directory_uri().'/YOUR FOLDER NAME/YOUR LOGO NAME.png',
        'height' => 60,
        'width' => 250
);
   return $metadata; 
  } 
}`
