### ISSUE TITLE
img tag inside an iframe

### ISSUE THREAD

**Issue by pradeep4196** [Automattic/amp-wp#367]
img tag inside an iframe doesnt convert to amp-img and is completely removed from the page.
plz help..

**Comment by mjangda** [comment]
Why do you have an `img` inside an iframe? Trying to understand your use case.

**Comment by amedina** [comment]
Closing for now. Reopen if needed.

**Comment by danielcardoso5** [comment]
This is an issue. I have also an open issue related to this. The amp-iframe specification refers to using an amp-img inside an iframe to behave as a placeholder when the amp-iframe is loading. This is necessary to display amp-iframes on top of the document. Also, setting a <div overflow></div> is not possible using your code. This is also in the specification and allows for the user to expand the iframe if it's on the top of the document. Please check the "Iframe Resizing" part in the docs here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md.

Would like to seed this addressed since this is breaking some embed codes I'm using.
