### ISSUE TITLE
Inline text styles added by WP stripped out

### ISSUE THREAD

**Issue by ebiewald** [Automattic/amp-wp#395]
I've noticed that text in the WP content that is underlined, colored, or aligned is not appearing as such in AMP. I know this is because WP added inline styles to those tags, which isn't supported by AMP, so they're being stripped out. If the plugin could add a class to those tags in place of the inline styles, so you can still style the text as expected, that would be really awesome. 

Is there any current work around in place? Or is there any discussion of something be added to the plugin to handle all the WP wysiwyg options? If not, maybe add a disclaimer to the README? Thanks in advance for your help, it's much appreciated! 

Ellen

**Comment by mjangda** [comment]
Can you share some example HTML?

**Comment by ebiewald** [comment]
Of course. When you are writing a post in WordPress and you select text and underline it in the WYSIWYG, when you view the post WordPress has added a <span> and an inline style like this: 
`<span style="text-decoration:underline;">underlined text</span>` 
However that same text in the AMP version of the post (after running through the amp-wp sanitization) is just: 
`<span>underlined text</span>`
Same thing happens with colored or aligned text. It would be great if the inline style could be replaced with a class in those cases, something like:
`<span class="underlined">underlined text</span>`
Is that something you'd foresee being possible in the plugin? Is there something already there that I'm missing? It would be awesome if all the default WordPress text styles were maintained in the amp template via the plugin.

**Comment by mjangda** [comment]
Yeah, it's a bit annoying that WordPress does this but I guess `<u>` was deprecated for a little while.

The plugin should probably handle this. The best option seems to be to look for `<span>`s with `style="text-decoration: underline;"` and convert them to a `<u>` instead.

**Comment by mjangda** [comment]
Related: #344 -- we need to handle alignment since that uses `style` as well.

**Comment by ebiewald** [comment]
The same happens for coloring text via the WYSIWYG, it adds an inline `style="color: #{color};"`

**Comment by mjangda** [comment]
Outside of using a full-on CSS parser/extractor (which might be overkill), I guess we can probably get by with some regex?

**Comment by coreymckrill** [comment]
Since the Editor could potentially add any arbitrary CSS rules to a style attribute, it seems like we need to find a generic way to handle it, rather than trying to make tag conversions for every possible case. It also needs to happen server-side since AMP pages [can't have any author-written JS](https://www.ampproject.org/docs/reference/spec.html).

So here's one approach:

* Prior to stripping out the style atts (or maybe during):
  * Add a unique class name to each node that has a style att
  * Capture the contents of each style att
* Dump the styles and their associated class selectors into `<style amp-custom>` during render

This way, it doesn't matter what the style attribute contains, it will still get preserved in a way that will pass validation.

Thoughts, @mjangda ?

**Comment by mjangda** [comment]
That seems reasonable @coreymckrill. We probably should also set limits on which CSS rules we want to support.

**Comment by coreymckrill** [comment]
I think we could do that with `safecss_filter_attr`, although I don't know how performant that would be. Given that these styles are added by/via the WP Editor, which does its own sanitizing, is it necessary?

**Comment by mjangda** [comment]
This is fixed.
