### ISSUE TITLE
Co-authors-plus template override

### ISSUE THREAD

**Issue by jakewrfoster** [Automattic/amp-wp#397]
In reference to the PR that fixed #137:
[This action](https://github.com/Automattic/Co-Authors-Plus/blob/master/php/integrations/amp.php#L3) currently overrides the AMP custom template `/amp/meta-author.php`. In order to avoid confusion, either: 
a) [the docs](https://github.com/Automattic/amp-wp#example-override-author-template-from-theme) should be updated to reflect this, or
b) within the `verify_and_include( $file, $template_type )` method, [the AMP templating system](https://github.com/Automattic/amp-wp/blob/master/includes/class-amp-post-template.php#L377) should be called _after_ [the filter is applied](https://github.com/Automattic/amp-wp/blob/master/includes/class-amp-post-template.php#L382) .

I am happy to provide a PR for either of these options if you would let me know which you are more likely to push through.

Thanks!
Jake

EDIT: update links

**Comment by ebiewald** [comment]
Looks like this has been brought up to Co-Authors Plus too https://github.com/Automattic/Co-Authors-Plus/issues/360

**Comment by mjangda** [comment]
I think the filter should continue run after (as a "last-resort" option for other plugins/themes to integrate and modify).

I was thinking either that we:

1) add a new filter before the `locate_template` lookup; or
2) let the existing filter know that we found a theme template so that anyone that hooks in can act accordingly.

**Comment by romancandlethoughts** [comment]
@mjangda, 

Introducing a second filter to override the manual template does nothing to address the confusion that led to the creation of this issue. I would sooner deprecate the manual template construct altogether and have it _just_ be a filter rather than have any option for a filter overriding the manual templating construct. This way, theme devs would at least have absolute control (or knowledge, at least) over the priority. If there is both a filter and a manual template construct, it is very unclear as to what will take precedence (and which plugin it would be coming from). I am guessing that for a lot of theme devs, this could be something that proves very challenging/time consuming to debug. 

All confusion seems to be avoided if the filter is fired before the manual templating constuct. I can't imagine a scenario wherein a dev would introduce those template files and wonder why a third-party plugin _isn't_ affecting or overriding the output. It would also be the first place a dev would think to look if they _wanted_ to see plugin overrides. 

The only downside of this alternative is that a dev who added manual templates may not know that a plugin is attempting to modify the template output -- and they may end up coding what the plugin otherwise was going to introduce to the output. For this, I think that documentation may be sufficient... That being said, I think the risk for confusion, and ultimately time-sink, is still made greater by having both a filter override and a manual templating construct.

I am interested in knowing what you had in mind regarding "let the existing filter know that we found a theme template so that anyone that hooks in can act accordingly.". Are you worried that plugin files could fail in some way if their bundled templates are not being used? What motivates the notion that a filter _should_ override the manual templating construct? Perhaps I am taking a narrow viewpoint.

Thanks!
Jake

**Comment by mjangda** [comment]
Sorry for taking so long to follow up here, @romancandlethoughts and @ebiewald. 

The way we're approaching templates here is not too different from how the core template loader works. Simplified, here's core load order:

1) Core template compat file
2) parent theme file
3) child theme file
4) `template_include` filter

Where a higher number is given greater preference. Similarly, `amp-wp`'s load order:

1) `amp-wp` template file
2) parent theme `amp` directory file
3) child theme `amp` directory file
4) `amp_post_template_file` filter

Namely, the filter should be the last point of override.

After thinking on it a bit, I realize that neither of my suggested solutions are really workable and I agree that it can be confusing to have your theme's templates overridden by a plugin.

I think the best option here might actually be to update things on the CAP side and only override the default plugin template. Maybe something along these lines?

```
--- a/php/integrations/amp.php
+++ b/php/integrations/amp.php
@@ -22,7 +22,8 @@ function cap_update_amp_json_metadata( $metadata, $post ) {
 }

 function cap_set_amp_author_meta_template( $file, $type, $post ) {
-       if ( 'meta-author' === $type ) {
+       if ( 'meta-author' === $type
+               && dirname( $file ) === AMP__DIR__ . '/templates/' ) {
                $file = dirname( __FILE__ ) . '/amp/meta-author.php';
        }
        return $file;
```

**Comment by romancandlethoughts** [comment]
@mjangda,

In effect, the solution you offered just extends the logic I proposed above to CAP instead of amp-wp. If we expect our plugins (at least CAP, in this instance) to handle the templating logic thusly, why wouldn't we just program that it be done in the originating plugin (that is, in amp-wp)? I hate to play the same card, but I still fail to see the pragmatism or benefit (outside of the logic being similar to Core's templating logic) of having the filter override the theme files. I could probably be won over pretty easily if you were to offer some practical use-cases in favor of the filter override. Because again, I may be overlooking something -- it certainly wouldn't be the first time :)

Thanks!
Jake

**Comment by westonruter** [comment]
Per https://github.com/Automattic/amp-wp/pull/422#issuecomment-398587225:

> There are conflicts in the PR, and besides we'll be discouraging the use of the built-in classic templates in favor sites opting for full AMP theme support going forward, where the plugin will fully re-use a theme's existing templates. That being the case, Co-Authors Plus will be fully supported just the same as on the non-AMP site. So I'm closing this PR.
