### ISSUE TITLE
template_include should be used instead of template_redirect

### ISSUE THREAD

**Issue by ryanhellyer** [Automattic/amp-wp#412]
The plugin should use `template_include`, not `template_redirect` for hooking in the new template.
https://markjaquith.wordpress.com/2014/02/19/template_redirect-is-not-for-loading-templates/

The `template_redirect` hook is commonly used in the way that the AMP plugin does, but this is not correct. The `template_include` hook is the hook intended for using to load new templates. If the `template_redirect` hook is used, it can interfere with plugins and other code which redirect content or otherwise make changes immediately before the template begins to load.

I discovered this whilst working on a 404 error plugin which was glitching with the amp-wp plugin.

**Comment by mjangda** [comment]
> I discovered this whilst working on a 404 error plugin which was glitching with the amp-wp plugin.

Can you describe what specifically is breaking or conflicting with the 404 plugin?

**Comment by ryanhellyer** [comment]
In that instance, the bug was in the 404 plugin. 

But this fix is important for the AMP plugin IMO, because if someone were to use the `template_redirect` hook for actually redirecting (which is what the hook is intended for), the AMP plugin may have already loaded it's template too early. By using the `template_include` hook, the template gets loaded after the redirects should have processed.

**Comment by mjangda** [comment]
This may be a bit unpopular of a decision, but I'm going to close this as `wontfix`.

- Simply swapping hooks means we end up using `template_include` incorrectly.
 - It should return a template path, which WordPress will then include for you, not just include the template and exit
 - However, properly returning a path leads to a host of different issues because of how the plugin works (e.g. we would no longer have the `$this` context in the templates).

- The `redirect` in `template_redirect` can be interpreted in a few ways. My interpretation is that it not necessarily for HTTP redirects but rather, for `redirecting` to a different template.
 - If you go back to early days of WordPress (e.g. <a href="https://core.trac.wordpress.org/browser/trunk/wp-blog-header.php?annotate=blame&rev=2183">rev 2183</a>) around when template loading was still being worked out, you'll note that the action and the comments around it discuss "template redirection" instead of "HTTP redirection".
 - Arguably, `wp` is a better action to handle redirects since it fires right before `template_redirect`.
 - Admittedly, hook usage does change over time and they can take on a different meaning, but both use cases should be considered valid.

- One of the reasons we went with `template_redirect` is because we don't actually want to run any other templates. We know we're in an AMP context so we know we're going to end up loading our template anyway, so there's no point in going through the template loading process (even though the cost of the boolean checks is negligible, it's still a cost).

One thing we could do, however, is hook in at a later priority on `template_redirect` so that if there are other plugins that want to do stuff on `template_redirect` we give them a first shot at it. This could still end up breaking things though, like in the case of the 404 plugin noted in this thread.
