### ISSUE TITLE
Advanced Custom Field Integration

### ISSUE THREAD

**Issue by gkoscevic** [Automattic/amp-wp#440]
The posts on my wordpress blog are built using AFC and I've been trying to integrate AFC into the plugin, but have had no luck.

Is there something I'm missing? Or a way that is already built out to accomplish this?

**Comment by mjangda** [comment]
How do you integrate AFC in your regular theme?

**Comment by gkoscevic** [comment]
The theme's single.php file is using multiple the_sub_field('title') and the_sub_field('content') functions. And they are wrapped with various if statements and while loops. We're able to get the title and content outputted on the AMP pages but all the image tags being displayed are not sanitized with 'amp-img' and therefore not passing AMP's validation.

**Comment by pshoeg** [comment]
I have this exact issue. The content from ACF is outside the "post_amp_content", which apparently means, that img elements will not be changed to amp-img, making validation fail.

I have changed the AMP plugins single.php file to include `the_sub_field('recipe')`, which includes both images and text like the regular `the_content`. But the functions written in the AMP plugin only looks at `the_content` (or so it seems). How is it possible to make it convert _all_ images to amp-img elements?

**Comment by pycarlos** [comment]
I have this issue too.

**Comment by Oddrigue** [comment]
I also have this issue. I tried [ACF-AMP](https://ampforwp.com/acf-amp/) but it didn't sanitize the content in repeaters

**Comment by kevinkonrad** [comment]
Has anyone figured this out? I, too, am having issues with this. I would like to sanitize ACF WYSIWYG fields so that `<img>` tags will be converted to `<amp-img>` tags, etc.

**Comment by westonruter** [comment]
@kevinkonrad Can you share the code for how you are integrating ACF into your AMP post templates?

**Comment by nusserstudios** [comment]
@westonruter, I'm using just a <?php the_field('home_box_1_title'); ?> as a field, and I'm having the exact same issue. Hope this helps.

**Comment by nusserstudios** [comment]
@westonruter, I'm using `<?php the_field('home_box_1_title'); ?>` and I'm having the same issue everyone else is.

**Comment by Bengolino** [comment]
Also have the same issue and also use sub_fields in my content :)

**Comment by westonruter** [comment]
@Bengolino please share the steps that I can do to replicate what you are seeing on a vanilla install.

**Comment by westonruter** [comment]
ACF should be fully supported as of 1.0 since the active theme's templates are encouraged to be re-used in AMP.

**Comment by uri3000** [comment]
@westonruter What do you mean 1.0? You comment was impossible to understand... could you explain?

**Comment by westonruter** [comment]
Version 1.0 of the AMP plugin should work seamlessly with ACF due to the reuse of the active theme's normal templates.

**Comment by uri3000** [comment]
Well it doesn't.
I think it's caused by the fact that I'm using AMP ACF and in my custom
template I am rendering a field as is.
It is rendered with the <img> tag without replacing it.
Any idea how to make it work with the AMP ACF?
It looks like the output of AMP for ACF has to go through additional
processing and it doesn't.

**Comment by westonruter** [comment]
OK, so assuming you have copied the `single.php` from the plugin and are modifying it, instead of adding the above into the template itself, what you'll want to do is just add one line to the template, like so:

```php
<?php echo $this->get( 'introduction' ); ?>
```

Then you need to add a `amp_post_template_data` filter to define this `introduction` data, and you can do so by putting the following in your theme's `functions.php`:

```php
add_filter( 'amp_post_template_data', function( $data ) {
	ob_start();
	?>
	👉👉👉 PUT INTRODUCTION TEMPLATE CODE CODE HERE 👈👈👈
	<?php
	$content = ob_get_clean();

	if ( empty( $content ) ) {
		return $data;
	}

	$amp_content = new AMP_Content(
		$content,
		amp_get_content_embed_handlers( get_post() ),
		amp_get_content_sanitizers( get_post() )
	);

	$data['introduction'] = $amp_content->get_amp_content();

	$data['amp_component_scripts'] = array_merge(
		$data['amp_component_scripts'],
		$amp_content->get_amp_scripts()
	);

	$data['post_amp_stylesheets'] = array_merge(
		$data['post_amp_stylesheets'],
		$amp_content->get_amp_stylesheets()
	);

	return $data;
} );
```

**Comment by westonruter** [comment]
Again, none of this is necessary if you just use the new theme support in the plugin. You can write templates as you do normally when you write themes.

**Comment by uri3000** [comment]
Thanks Weston, but the entire code I sent is the template of the post which has multiple custom fields, some of which are lists. The template is for 'post' and it has:
- introduction
- list of "section_content"
- summary

All of these are rendered in the template which I had sent. Could you please explain again having this in mind? Thanks a lot...

What do you mean by "new theme support" - How do I use the new theme support in the ACF plugin?

**Comment by uri3000** [comment]
Especially I don't understand how to deal with the section_list inside the ob section in your walkthrough.

**Comment by westonruter** [comment]
For documentation on the new theme support in the plugin, see https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support

**Comment by uri3000** [comment]
Weston, this is not how I am using the templates.
I am creating the template using the ACF for AMP plugin (Please see attached image).
It is not stored in a duplicated single.php because I simply chose to use the plugin.

In addition, the way you suggested only takes into account the introduction custom field but my template includes many fields (the whole template needs to go through the AMP sanitizers...) 
How can I achieve this using this plugin?

Thanks

![screen shot 2018-06-27 at 18 36 03](https://user-images.githubusercontent.com/7873124/41984312-0adfc0a8-7a39-11e8-8222-f10f06ced62f.png)

**Comment by westonruter** [comment]
I do not know. I didn't know that ACF allowed you to edit PHP code. I am not familiar enough with ACF to provide further guidance.

**Comment by uri3000** [comment]
This is an extension that you guys provide on your website. Don't you
provide official support for it? I am paying for it.
