### ISSUE TITLE
Design & document the architecture of the next iteration of the plugin

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4570]
The procedural roots and their organic growth are very obvious in some parts of the plugin, and maintainability costs are non-trivial in these areas due to inflexible code, unnecessary coupling, latent bugs, and pieces of logic that are hard to reason about. This makes it either very costly or not even directly feasible to work on major structural changes to open up new use cases.

Work needs to be done to intentionally design an architecture that is streamlined for the particularities of the plugin and that get rid of all the current major pain points of the code base.

The implementation can then proceed via the Strangler pattern, extracting one subsystem at a time and refactoring it into a separate (and completely uncoupled) component (to be done in separate Epics).

**Comment by jwold** [comment]
**Notes from 2021-04-13 Meeting:**

* AS > Low hanging fruit, rewrite plugin. We already did a lot of changes since this ticket was created; we already have service based architecture where we’re moving things into services. That’s great.
* AS > While we’re doing that we’re keeping backwards compatibility mostly in tact, then at major version bumps we can get rid of more technical debt; thinking ahead, thinking about v3 or v4 of plugin and what might be far reaching goals in terms of architecture, maintenance, and what would need to happen to get to this. 
* AS > I already put up a few thoughts in ticket, it means to think about where we have most churn in code, think about biggest pain points for maintenance, and think about what modified architecture would be where those pain points are gone, and start from there. 
* AS > Not documented in a kind of listing, but good start is issues marked as `tech-debt`, that’s where we usually refactor to make something work. All those things marked as breaking changes, because something too rigid. We could have that as first list. 
* AS > **Good to have session to discuss this as team where we go about thinking about where engineer blocked the most because of the way the code is written right now.** 
* AS > We have best practices for how to solve the problem, but 50 best practices is [not ideal]. First step is where it helps the most and where to solve for these. 
* AS > More about setting priority for when we want to do it.
* AM > Add clarity to where we are, what’s been done in service architecture and other things; we need to reflect that here then prioritize what else is next step. 
* WR > We have service (?) architecture, then next step has been AMP toolbox PHP extraction for optimizer, then alongside that we’ve had the evolution of block validation error UI in editor. Moving toward react based UI.
* WR > Then we have moving of sanitizer code, document creation logic; moving it all over to toolbox repo. Then rewriting validation screens to use react instead of classic WP admin screens. That’s the end goal of where I think we’ll be when we have this done.
* AS > General idea is we want to build - it’s just a pipeline, we put something in and get more performant version of same thing out. Main building blocks are sanitization, validation, and optimizer; that’s our pipeline, and if we move these into toolbox, into library, simple fact of having them in separate package forces us to decouple code. Forcing us to decouple code means rewrite parts where coupling products latent bugs and maintenance nightmares, but decoupling we’re forced to solve all of these. Still long ways to go, there’s AMP theme support that’s benchmark of what is problematic with plugin. That is a linear mess of code where we do all sorts of stuff, closer we get to having toolbox integrated into plugin and toolbox taking over pipeline - that’s end goal where we are probably decoupled.
* AS > AMP plugin is about integrating pipeline into WP request response cycle and building admin backend around it so we can work with it; all logic should be in toolbox.
* AM > Create ticket for theme optimization to define what optimization is in terms of CWV, and everything? The document I’m preparing is about page experience tooling in general, going to be difficult to hook into WP theme right there, we could mention it but I’d like to formalize that work.
* AS > Probably something like inverse of Linter. Linter tells you all things you shouldn’t do, optimal theme is inverse. 
* AM > Yes, I just want to setup meeting with Astra CEO and say we want this. When we have that definition we can check how close they are. Probably their baseline theme already has these things. Let’s see how we can capture this into something we can deliver.
* AS > What if we have in amp plugin or smaller plugin a way to activate theme and run linter to know the ways theme is wrong or whether gets perfect score.
* AM > When you say that it points to plugin as page experience tool more general, plugin could check those things in theme that aren’t necessarily amp; and suggest things to fix. People will use plugin with their theme, so yes ideally plugin flags all those things, then in future when plugin can be used with/without amp (although that shouldn't be case since AMP provides capabilities) those should (?) be applicable. 
* WR > We have issue: https://github.com/ampproject/amp-wp/issues/5679, you’d run PIXI on your own site. Other aspect is automated installing theme by theme and checking the results to see in mass for all amp compatible themes the status for whether they satisfy linting checks. That has another issue; config of themes to make use of features they have, such as carousels. That’s complication for automation.
* AM > There are two aspects, that is theme analysis in general. That is something that I have been thinking recently and will tell you why; the other is just the plugin taking care of use case of user specifically. We can expand and incorporate page experience guide so user knows limiting aspects, this is what you have to look for in your theme, and host provider (page cache), so user knows - this is related to idea of pipeline. What is component that influences page experience. If you change theme -
* AM > Imagine leverage compatibility database project to check themes for all the factors that influence CWV, then we could tag themes: this is CWV friendly, etc. 
* AM > There are conversations now to include quality tagging into .org again, like Tide. Imagine compatibility database helps tag quality tag themes for plugin.
* AM > How do we config things to exercise functionality that could be evaluated. There’s lot of room here to do cool stuff, but we could start by identifying optimality, include into PIXI; not only PIXI, then we take it from there .
* WR > AMP compatibility database specifically for AMP, whereas Tide is general. Following Tide, almost done with rewrite to use Node; it’s part of WP.org ecosystem. For WP.org it makes more sense for that to be how that is realized, but learnings from AMP compatibility - 
* WR > Something we don’t have now in AMP compatibility database (CD)  is PIXI checks, to include for theme analysis what results are for CWV because that would be important for us to know in terms of what we list on eco page and where reach out to theme authors to improve scores. 
* AM > Yes. Tide should power wp.org, and they could borrow from us if they want. And also AMP CD should be more than just that, be analytics infrastructure to check for compatibility things and page experience. That’s going to power page experience tool we’re developing. If they want to borrow checks for CWV in Tide, then they can do that. 
* WR > I guess it’s a matter of in some ways - as I understand Tide is supposed to be framework for integrating any checks, PHP CS; ES Lint, and other checks. Lighthouse was a check, but now API for Page Speed Insights is evolution for that, and it includes CWV. Imagine going to theme directory page and you see the CWV scores, that would give idea of performance of that theme in terms of CWV. Seems cool.
* AM > Yes. We are aligned, things are coming together. AMP CD will be important role for us. 
* KM > Didn’t label this as groomed, it’s an epic and needs more issues attached to it.
