### ISSUE TITLE
Never Serve AMP Pages to Desktop

### ISSUE THREAD

**Issue by davidbhayes** [Automattic/amp-wp#4621]
## Feature description

What we're seeing is that **3-5% of "desktop" visitors are seeing the AMP pages on our website**. (Presumably being shared an AMP link to the website, but being non-mobile when they open it.) This is understood by the team as giving them a worse experience than them seeing the traditional/responsive/desktop view. **Ideally we'd see that no one on a normal/desktop browser sees the AMP version.** If they try to open the AMP version, they should be forwarded to the normal version. 

I knocked around the issues and saw some discussion both of providing links to the normal version of the article on the AMP version (please do), and of forcing _all_ mobile visitors to AMP (kind of the reverse of what I want). But I saw no discussion of this in particular in my looking.

Complexities that I think exist:

- I don't understand AMP spec very well, but I think I can't load arbitrary JS (to give us the behavior we want) on an AMP page.
- We have an Nginx reverse-proxy serving most page-loads. So I'm thinking this behavior would have to live in that layer, vs PHP we could just write to jump into the life-cycle and forward visitors hitting non-Google-cached AMP. (Unfortunately we're paying WP Engine for hosting, so I can't trivially write that Nginx rule--assuming I was good at those--and push it live.)

If the above are wrong/resolvable, I'd love to know that. At a minimum I'm hoping to have some consideration from "the AMP experts." Thanks!

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> What we're seeing is that **3-5% of "desktop" visitors are seeing the AMP pages on our website**. (Presumably being shared an AMP link to the website, but being non-mobile when they open it.) 

That could be why, but AMP versions of content can be served to desktop in other scenarios as well. For example, if you install Google News as a PWA then clicking on an article will open the news article's AMP version as a lightbox inside the window rather than opening it in a browser tab.

> This is understood by the team as giving them a worse experience than them seeing the traditional/responsive/desktop view.

This is why we have been investing in the Standard and Transitional template modes which re-use the active theme's templates for AMP pages. The big push by the AMP team is to enable sites to go “AMP-first” where AMP is just the web framework used to create the site: no separate paired AMP version of your content. See the [Standard mode showcase](https://amp-wp.org/showcases/?template_mode=native). Any design can be built in AMP, and AMP is not mobile-specific. 

> I knocked around the issues and saw some discussion both of providing links to the normal version of the article on the AMP version (please do), and of forcing all mobile visitors to AMP (kind of the reverse of what I want). But I saw no discussion of this in particular in my looking.

Yes, this is #4479.

> **Ideally we'd see that no one on a normal/desktop browser sees the AMP version.** If they try to open the AMP version, they should be forwarded to the normal version. ¶ Complexities that I think exist…

There are complexities for redirecting from non-AMP to AMP as well. To do so reliably across the various WordPress server stacks, we're settling on using a JavaScript-based method to do the redirection, as the server-side redirection method (via PHP) is not reliable (see https://github.com/ampproject/amp-wp/issues/2044#issuecomment-580552860) when caching layers are in place.

So all of this to say… 

1. Our recommendation is to try to go AMP-first if possible, as then no redirection is needed and desktop visitors will get the same speed benefits as mobile visitors.
2. Otherwise, if you want to do redirection from AMP to non-AMP for desktop visitors, the only real way to do this would be to use server-side redirects, either in Nginx or PHP, based on the user agent. You'll have to make sure you do not redirect Googlebot's user agent! You can't use JS because AMP does not allow it in this way.

**Comment by davidbhayes** [comment]
Thanks for the thoughts @westonruter :)
