### ISSUE TITLE
Preview doesn't work in reader mode on a published post

### ISSUE THREAD

**Issue by ktmn** [Automattic/amp-wp#4656]
I've got Twenty Seventeen in reader mode, editing the default "Hello world!" post in the block editor, hitting "Preview" button will display the post with it's changes, but if I hit the new AMP icon next to the preview button, then it will navigate correctly to `?preview_id=7&preview_nonce=51e7746d07&preview=true&amp=1` but the page doesn't contain the updated changes in the post content. 

If I revert the post to draft then the preview works correctly.

This wasn't an issue before AMP plugin v1.5 afaik.

Anyone able to reproduce?

**Comment by westonruter** [comment]
Yes, I can reproduce this issue. The issue seems to be that when the post is published, clicking the AMP Preview button doesn't force the post revision to be saved before the post is navigated to.

This logic seems to be incorrect:

https://github.com/ampproject/amp-wp/blob/4880f0f58daaf07685854be8574ff25d76ff583e/assets/src/block-editor/components/amp-preview.js#L206-L211

But I'm not sure why because this is the same code that core button is using:

https://github.com/WordPress/gutenberg/blob/2beb59861039c43c71f03c25256479b30c148387/packages/editor/src/components/post-preview-button/index.js#L144-L180

**Comment by ktmn** [comment]
This `$content` here doesn't contain the preview edits (while `get_the_content()` does):

https://github.com/ampproject/amp-wp/blob/90b306d5a35631a08cd7a1ec2798217bde0d6f4b/includes/templates/class-amp-post-template.php#L348-L354

The post is retrieved using `get_post()`:

https://github.com/ampproject/amp-wp/blob/90b306d5a35631a08cd7a1ec2798217bde0d6f4b/includes/templates/class-amp-post-template.php#L162-L168

but the preview content seems to be only injected for the [main query](https://github.com/WordPress/WordPress/blob/3ee9488292318153390d5631a08e2f7713ef7ac1/wp-includes/class-wp-query.php#L3125).

A fix that seems to work for me is to adapt [this core code](https://github.com/WordPress/WordPress/blob/3a333ef030345c459b9ba131b24735a3f8f635f3/wp-includes/revision.php#L553-L600) to load the preview content into the post object from `get_post()` (at [class-amp-post-template.php#L164](https://github.com/ampproject/amp-wp/blob/90b306d5a35631a08cd7a1ec2798217bde0d6f4b/includes/templates/class-amp-post-template.php#L164)):

```php
	public function __get( $name ) {
		switch ( $name ) {
			case 'post':
				if ( isset( $_GET['preview_id'] ) && isset( $_GET['preview_nonce'] ) ) {
					$id = (int) $_GET['preview_id'];
					if( wp_verify_nonce( $_GET['preview_nonce'], 'post_preview_' . $id ) ) {
						return _set_preview( get_post( $this->ID ) );
					}
				}
				return get_post( $this->ID );
		}
		return null;
	}
```

**Comment by westonruter** [comment]
Oh, good catch. I think this is something I inadvertently broke in 1.5.3 when fixing something else: #4547.

You want to open a PR with the above patch?
