### ISSUE TITLE
Menu is not sticky anymore

### ISSUE THREAD

**Issue by danyilborysenko** [Automattic/amp-wp#4676]
Hello, i got what i want, high points on pagespeed (84-99) but my menu is not sticky anymore on desktop version. Mobile version works fine.

Please, what i need to do to save high perfomance of site and back sticky meny. 
https://osvita-sk.com/

Thank you!

**Comment by westonruter** [comment]
Is the AMP plugin reporting validation errors for invalid markup? The AMP plugin removes invalid AMP markup in order to make pages valid AMP. Custom scripts, for example, are not allowed in AMP. If the sticky header is being implemented using JS, then this could be why it is not working anymore when AMP is enabled.

What you'll need to do is find a sticky header solution that is AMP-compatible.

Here's one solution: https://www.youtube.com/watch?v=kNdh0m5Mraw

Here's [another](https://stackoverflow.com/a/50832232/93579): https://amp-demos.glitch.me/sticky-header.html
