### ISSUE TITLE
Custom sanitizer not being run

### ISSUE THREAD

**Issue by adamlanningmolyneux** [Automattic/amp-wp#469]
Hi guys,

I cannot for the life of me figure out why it's not working. The code is:

```
class XYZ_AMP_Canvas_Sanitizer extends AMP_Base_Sanitizer {
    public function sanitize() {
        $body = $this->get_body_node();
        $canvas_nodes = $body->getElementsByTagName( 'canvas' );
        foreach($canvas_nodes as $canvas_node){
            $canvas_node->parentNode->removeChild( $canvas_node );
        }
    }
}
```

which is linked to by this within functions.php

```
add_filter( 'amp_content_sanitizers', function( $sanitizer_classes, $post ) {
    require_once( dirname( __FILE__ ) . '/amp/class-amp-canvas-sanitizer.php' );    
    $sanitizer_classes[ 'XYZ_AMP_Canvas_Sanitizer' ] = array(); // the array can be used to pass args to your sanitizer and accessed within the class via `$this->args`
    return $sanitizer_classes;
});
```

If I put "die();" in the second part it works, but not if I put it within the sanitize class which means it includes the file but doesn't get to the sanitize function.

Slightly unrelated issue also, I use srcset images and need the image filter to remove the sizes attribute. Once I get this filter working I'll be able to do it, but it may be a problem someone else has already solved.

Cheers for the help!

**Comment by coreymckrill** [comment]
I'm not sure why this isn't working, because from here it looks like it should. Maybe try removing the unused `$post` parameter from the anonymous function.

However, on a related note, I think you could accomplish the removal of the canvas element and the sizes attribute more easily by customizing the configuration of the Blacklist sanitizer, rather than creating a whole new sanitizer class. You can use the same `amp_content_sanitizers` filter hook to pass args to the Blacklist, and there are two args in particular ([1](https://github.com/Automattic/amp-wp/blob/0.3.3/includes/sanitizers/class-amp-blacklist-sanitizer.php#L189), [2](https://github.com/Automattic/amp-wp/blob/0.3.3/includes/sanitizers/class-amp-blacklist-sanitizer.php#L220)) that it looks for that relate to tag and attribute removal. So the function to add to the filter might look something like this:

```php
add_filter( 'amp_content_sanitizers', function( $sanitizer_classes ) {
	$sanitizer_classes['AMP_Blacklist_Sanitizer']['add_blacklisted_tags']       = array( 'canvas' );
	$sanitizer_classes['AMP_Blacklist_Sanitizer']['add_blacklisted_attributes'] = array( 'sizes' );
	
	return $sanitizer_classes;
} );
```

**Comment by mjangda** [comment]
@coreymckrill note that in your sample, it will remove tags/attributes that other users of the filter may have added. Better to `array_merge` (or similar).

**Comment by coreymckrill** [comment]
@mjangda Oh, good point. I've updated the code snipped above.

**Comment by adamlanningmolyneux** [comment]
Thanks for the replies guys, been away for a couple weeks. Will try that, cheers!
