### ISSUE TITLE
Wizard step: Reader mode > side-by-side preview

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4703]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Display reader mode review headline
* Show screenshot of active theme (to indicate it is for desktop (non-AMP) visitors
* Show screenshot of Reader mode theme (for mobile/AMP visitors)
* Clearly indicate that the selected Reader mode will be served to mobile visitors: visitors encounter AMP content (for example through search engines). 
* Add checkbox to indicate whether mobile visitors should be automatically redirected to the AMP version
* Back button and next button

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Design notes from meeting:

- How can we anchor the messaging in a nutshell about how the two themes work based on how you’re coming here
- Link off to learn more from AMP site. Maybe cute illustration with it. 
- If you uncheck checkbox, then right side would just say AMP, not mobile/amp. https://d.pr/i/xsyOkE

**Comment by westonruter** [comment]
Nevertheless, we can actually show the AMP version of a site in a wizard, since there will be room to show it in an iframe. This makes sense in a step after the side-by-side preview, as a way to show them what it actually looks like so they can decide whether or not to open the AMP Customizer. See https://github.com/ampproject/amp-wp/issues/4707#issuecomment-629433953.

**Comment by amedina** [comment]
QA Passed.
