### ISSUE TITLE
Wizard step: Choosing mode

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4706]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Display standard, reader, and transitional modes with information explaining each
* Add ability to choose a mode
* Next button and back button

## Implementation brief

* For this step we will create a shell of the React context provider that will handle the site scan. Currently the shell will only need to provide the recommended mode.
* This recommendation will be passed in to the mode choice screen.

## QA testing instructions

1. Pull the branch and run `npm run build` (or switch to the branch if using QA tester plugin)
2. Navigate to the setup wizard
3. Move to the "Template Modes" screen
4. Make a selection and navigate to the last screen of the wizard to force data save
5. Reload the page and verify your selection persisted
6. Verify the reader themes selection screen is skipped if you don't have reader mode selected

**Note**: For testing purposes, simulate the existence of AMP plugin issues by adding `&amp-plugin-issues=1` to the URL. Simulate the existence of AMP theme issues by adding `&amp-theme-issues=1` to the URL.

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
@jwold Very minor suggestion on this:

<img width="510" alt="Screen Shot 2020-06-16 at 1 29 37 PM" src="https://user-images.githubusercontent.com/9020968/84813356-7986e580-afd5-11ea-9f7e-12dc493d01d6.png">

With the design shown here, there is a down arrow that I presume expands/contracts the details section, so initially the user only sees the top row (everything above the gray line) until the arrow is clicked. 

I suggest moving the arrow down to the same row as "Details" (text subject to change) as shown in this rough WIP:

<img width="936" alt="Screen Shot 2020-06-16 at 1 45 51 PM" src="https://user-images.githubusercontent.com/9020968/84814951-e4d1b700-afd7-11ea-8de4-386a930e5918.png">

Reasons:

1. This will allow the full top row to serve as the radio label. Since labels are clickable, we don't want to have another clickable button inside it.
2. This will allow me to use the WP core `PanelBody` component and save ~100 lines of code for a custom expandable panel.

**Comment by jwold** [comment]
Thinking about this now, the reason to switch it up makes sense.

**Comment by jwold** [comment]
@johnwatkins0 the best way I can think to switch things up would be something like this:

https://v.usetapes.com/4YbSvZyUb3

**Comment by johnwatkins0** [comment]
That will work. Using the core `PanelBody` component, that whole row will be clickable (and will have a hover state indicating as such).
