### ISSUE TITLE
Wizard step: "Done" screen

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4707]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Display headline about branding your theme
* Let users know they're about to be sent to the Customizer to see how their site looks with AMP enabled (Customizer AMP toggle turned on)
* Next button and back button
* Next button takes you to the Customizer

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
The user shouldn't be forced to go to the Customizer at the end. They should also be able to just exit the wizard. 

Actually, when in Reader mode, this last screen could actually embed the AMP version of the site inside of an iframe. The user can then indicate whether they are happy with how it looks. If not, then they can proceed to the Customizer or else they can just go back to the dashboard.

Alternatively, if they selected Transitional mode, instead of providing the user with the site embedded in an iframe or to go to the Customizer, the call to action can be to open paired browsing to navigate around the site.

**Comment by amedina** [comment]
Agree users should not be forced to go to the Customizer. They should have a clear option to go there either at the end of the flow or any time afterwards. The former would be helpful for users not familiar with the Customizer, and the latter would be more general.

**Comment by jwold** [comment]
> Actually, when in Reader mode, this last screen could actually embed the AMP version of the site inside of an iframe. 

I'll explore this as a design, my understanding from previous discussions was we could only show a screenshot. Thanks!

**Comment by westonruter** [comment]
@jwold it's true that we can only show a screenshot when showing the non-AMP and AMP versions side by side, because we cannot embed the desktop non-AMP version in an iframe. However, after that summary step we can show just the AMP version in an iframe where we intend to show a mobile preview.

**Comment by jwold** [comment]
> However, after that summary step we can show just the AMP version in an iframe where we intend to show a mobile preview.

Are you suggesting adding another step to the onboarding wizard to show the AMP iframe?

**Comment by westonruter** [comment]
Not necessarily. I meant this to be the final step, part of the one that you had prompting the user they were about to enter the Customizer. Instead, the last step of the wizard can include:

1. Iframe with AMP version of site
2. Link to exit wizard
3. Link to open AMP Customizer

**Comment by johnwatkins0** [comment]
Mentioned on Slack:

> We should add aspects such as "Using a Caching Plugin", and other recommendations as part of the onboarding flow.

This screen should include a list of "what to do next" items (Customizer, etc) along with recommendations for additional enhancements that go well with the AMP plugin.

**Comment by jwold** [comment]
> This screen should include a list of "what to do next" items (Customizer, etc) along with recommendations for additional enhancements that go well with the AMP plugin.

We discussed today trying a `getting started` module on the settings page once they exit the wizard. This could take the place of this recommendation.

**Comment by jwold** [comment]
We discussed a number of options and I'll update the design.

**Comment by jwold** [comment]
![Screen Shot on 2020-06-23 at 09-17-31](https://user-images.githubusercontent.com/3411173/85428669-68d4f300-b532-11ea-8f03-2d1b993d7a11.png)

**Comment by westonruter** [comment]
@jwold We can actually include the iframe in all three versions. We just have to make sure we put the AMP version of a URL on the site into the iframe, but this will apply regardless of Standard, Transitional, or Reader.

**Comment by westonruter** [comment]
The iframe would necessarily be showing the site in a mobile viewport, of course.

**Comment by jwold** [comment]
Updated the `done` page. Ready for review.

![Done reader](https://user-images.githubusercontent.com/3411173/85782298-56e28400-b6db-11ea-9bf6-db6fd918b713.png)
![Done standard](https://user-images.githubusercontent.com/3411173/85782316-5944de00-b6db-11ea-9bf9-753d1ca48167.png)
![Done transitional](https://user-images.githubusercontent.com/3411173/85782322-59dd7480-b6db-11ea-8fb3-863c02a491f2.png)

**Comment by westonruter** [comment]
Instead of “Scrollable view of your site” it should probably just say, “Live view of hour site” or something. 

It would also seem to make sense to put the Browse button in the inside of that box around the iframe, as the button is essentially causing the user to break out of the iframe.

**Comment by jwold** [comment]
Good point! Here's an update: 

![Done standard](https://user-images.githubusercontent.com/3411173/85897213-bb224800-b7ae-11ea-8146-a95774cd06ae.png)
![Done transitional](https://user-images.githubusercontent.com/3411173/85897214-bc537500-b7ae-11ea-85d8-d4da6ad341d4.png)
![Done reader](https://user-images.githubusercontent.com/3411173/85897216-bcec0b80-b7ae-11ea-92e6-5b1dc45b58b6.png)

**Comment by jwold** [comment]
Good point! Some updates:

![Done standard](https://user-images.githubusercontent.com/3411173/85897572-6e8b3c80-b7af-11ea-92b9-d378663a024e.png)
![Done transitional](https://user-images.githubusercontent.com/3411173/85897581-721ec380-b7af-11ea-9772-21e3e54b0a20.png)
![Done reader](https://user-images.githubusercontent.com/3411173/85897582-72b75a00-b7af-11ea-934e-ed7af2b19c29.png)

**Comment by johnwatkins0** [comment]
Minor bug fix to include in this PR (thanks @pierlon). Z-index adjustments needed:

![image](https://user-images.githubusercontent.com/9020968/85901627-d64d8180-b7c7-11ea-85d3-23008237c1d0.png)

**Comment by johnwatkins0** [comment]
@westonruter @jwold  In the iframe preview, if we load the homepage for reader mode it's not going to show as AMP because only single posts use AMP. It would be easy to pull in the latest post and show that in the iframe instead of the homepage. Would that work?

Also want to make sure I have all these URLs right:

### Standard

- Iframe: Use the homepage URL (no `?amp` needed)
- "Visit your site" button: Link to the homepage (no `?amp` needed)

### Transitional

- Iframe: homepage URL with `?amp`
- "Browse AMP Version" button: Link to the homepage with `?amp` (which persists on subsequent navigations).

### Reader 

- Iframe: The latest single post with `?amp` (see note above)
- "Visit in customizer" link:  Link to customizer with `&amp` added to the URL. This will not be functional until we integrate the relevant parts of #4644 and also complete #4708 this week. Does the customizer also need to load on a single post to allow customizing reader mode?
- "Browse AMP Version" link: Link to single post with `?amp`? This also won't be functional until the the relevant parts of #4644 are integrated.


________

Let me know if I'm missing anything here. I'm also adding a `amp-no-admin-bar` query var check to hide the admin bar in the iframe.

Meanwhile, the "Finish" button (i.e. the "Next" button with text switched on the last page) will go back to AMP settings.

**Comment by westonruter** [comment]
> if we load the homepage for reader mode it's not going to show as AMP because only single posts use AMP. It would be easy to pull in the latest post and show that in the iframe instead of the homepage. Would that work?

Right, we'll need to obtain a URL for _something_ that will be an AMP page. You may be able to re-use `amp_admin_get_preview_permalink()` for this purpose. This function probably needs to be extended to support more templates, but it should be good enough for now. It will handle all of the cases above.

> * "Visit in customizer" link:  Link to customizer with `&amp` added to the URL. This will not be functional until we integrate the relevant parts of #4644 and also complete #4708 this week. Does the customizer also need to load on a single post to allow customizing reader mode?

This link should indeed load the URL returned by `amp_admin_get_preview_permalink()` by default as the `url` query param. In addition:

* When the Legacy theme has been selected, add the query var: `autofocus[panel]=amp`.
* When a non-Legacy theme has been selected, add the query var: `amp=1`.

The reason for this is that in legacy Reader mode, there is an AMP panel whereas in new Reader mode, there is not (since the whole theme is AMP).

Please also refer to the `amp_add_customizer_link()` function which is used to add an AMP admin menu link. However, it is actually insufficient at present because it lacks the `url` query param pointing to `amp_admin_get_preview_permalink()`.

> * "Browse AMP Version" link: Link to single post with `?amp`? This also won't be functional until the the relevant parts of #4644 are integrated.

Yes, link to `amp_admin_get_preview_permalink()`.

> Let me know if I'm missing anything here. I'm also adding a `amp-no-admin-bar` query var check to hide the admin bar in the iframe.

That's a good point. However, if the user navigates around then they'll all of a sudden see the admin bar again. Another option would be to embed the iframe with a [`sandbox`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) attribute that _omits_ `allow-same-origin`. This should have the effect of the iframe loading _without_ cookies, and by extension without the admin bar. You'll naturally need to include other `sandbox` attributes though, especially `allow-scripts`.

> Meanwhile, the "Finish" button (i.e. the "Next" button with text switched on the last page) will go back to AMP settings.

Perfect.
