### ISSUE TITLE
Wizard step: Standard mode

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4710]
## Feature description

The standard mode will need to be represented in the onboarding wizard to clearly help users choose it, as well as present them with a summary of what they've chosen.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

~No change in Phase 1. If user chooses this mode, selecting `next` takes them out of the wizard, back to the AMP Settings screen, and from there they see which mode they're in, and can retrigger the wizard.~

Standard mode can be chosen as an option on the template modes screen. When that happens the following screens will update as a result of this choice.

* The `reader themes` page will be skipped. 
* The `please wait` page will be skipped 
* The `summary` page will be present with different visuals.
  * The description paragraph will be updated.
* The visuals will show screenshot of their parent theme, and a screenshot of the mobile theme. 
* The done page will also be updated with a CTA to browse site and a CTA to finish, which takes them to settings page with getting started module. 

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Updated based on our discussing earlier this week for how the wizard will change if this mode is selected.

**Comment by westonruter** [comment]
> * The `please wait` page will be skipped (need verification on this)

Correct. There wouldn't need to be a need to wait for the Done screen for either Standard mode or Transitional mode because the theme would already be installed.

> * Redirect to mobile checkmark is present

Actually no, it would not be present for Standard mode. Only Reader and Transitional mode. In Standard, there is not a separate version to redirect to.

> * The `reader themes` page will be skipped

I suppose there is a need for the steps to be dynamic then? I mean, if I select Standard mode, it would be strange to see “Reader theme” in the list of steps. So either it should be removed from the steps, or disabled in some way?

> * The visuals will show screenshot of their parent theme, and a screenshot of the mobile theme.

There would be the theme screenshot, and then two arrows that connect that theme screenshot with a desktop illustration and a mobile illustration. Both of these illustrations would have the AMP icon. The two illustrations could be overlapped in some way to indicate they are the same page in fact. 

In contrast with this, the Transitional mode would show arrows to two illustrations with only the mobile version illustration getting the AMP badge, and the illustrations could be separated from each other since they are two separate versions.

> * They'll be then taken to the settings page with an updated getting started module.

Or they can be taken to the site to browse around. That's another action they could take.

**Comment by jwold** [comment]
> I suppose there is a need for the steps to be dynamic then? I mean, if I select Standard mode, it would be strange to see “Reader theme” in the list of steps. So either it should be removed from the steps, or disabled in some way?

I have an idea. 

* Rename `Reader Themes` to `Theme selection`
* Skip step automatically
* If user selects `previous`, they can go back to that screen, but it will be dynamically updated with a message, something like: 

Headline: Theme selection
Description: When the template mode is set to `Reader`, an AMP compatible version theme must be chosen. You've selected `Standard` mode, so this step is not unnecessary`. 

---

The benefit is that we aren't changing the steps on users (which will be confusing), and if someone is canny enough to notice they skipped a step, it's an opportunity for further education if they choose to go back to and look at it.

**Comment by westonruter** [comment]
Yeah, I think that works well.
