### ISSUE TITLE
Canonical URL tag should not be output for non-public posts when Yoast SEO is active

### ISSUE THREAD

**Issue by jonoalderson** [Automattic/amp-wp#4730]
## Bug Description

When Yoast SEO (or Yoast SEO Premium) is active, it takes over managing the presentation of the canonical URL tag (amongst others). Specifically, the AMP plugin's output for this is disabled, and Yoast's normal logic outputs its own tag.

This works correctly in all scenarios _except_ for when the post is 'non-public' (set to `private`, or where Yoast SEO settings result in the presence of a `noindex` directive in the meta robots tag).

## Expected Behaviour

In this scenario, no canonical URL tag should be output (see https://developer.yoast.com/features/seo-tags/canonical-urls/functional-specification/), but the AMP plugin outputs one regardless.

The AMP plugin should respect/echo the Yoast plugin's logic, and not output a canonical URL tag on non-public posts.

## Steps to reproduce

1. Activate the AMP plugin
2. Activate the Yoast SEO plugin
3. View the source code of a post, and see that Yoast has disabled the AMP plugin's canonical URL tag and output its own.
3. Set a post's status to _private_, _or_ set the post to 'noindex' (set the value of the control in `Yoast SEO` > `Advanced` > `Allow search engines to show this Post in search results?` to 'No').
4. View the source code of a post, and see that a canonical URL tag is output, and that the meta robots tag contains a `noindex` directive.

## Video
Video of me recreating
https://www.loom.com/share/3d7618b005a44b3d9482f6ac265aa43f

## Additional context

cc @jdevalk - could you describe/expose a mechanism by which the AMP folks could determine and hook into our private/public status? 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
The AMP spec actually requires a canonical link to be present: https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/?referrer=ampproject.org#required-markup

> AMP HTML documents MUST:
> * contain a <link rel="canonical" href="$SOME_URL"> tag inside their head that points to the regular HTML version of the AMP HTML document or to itself if no such HTML version exists.

The plugin currently makes sure this is the case by unconditionally adding a canonical link if none is present:

https://github.com/ampproject/amp-wp/blob/b9556a12a31fe926de24149ca4fd3b412875b221/includes/class-amp-theme-support.php#L1629-L1641

While it makes sense to not have a canonical link for non-indexed pages, it is a requirement for AMP pages and omitting them would invalidate the AMP page.

**Comment by jdevalk** [comment]
I've noticed this while debugging, and want to just state that this is 100% in conflict with the requirements for Google search as stated by John Mueller amongst other people...

**Comment by jdevalk** [comment]
For reference:

- https://www.seroundtable.com/google-noindex-rel-canonical-confusion-26079.html
- https://www.searchenginejournal.com/google-dont-mix-noindex-relcanonical/262607/

etc.

**Comment by westonruter** [comment]
Is it necessary to remove `canonical` if there is already a `noindex`?

**Comment by schlessera** [comment]
According to @softplus from that Reddit post, the Google index would prioritize the `canonical` over the `noindex`, and thus try to combine the pages.

The `canonical` points to the non-AMP version. As both the AMP and the non-AMP version have a `noindex`, even combining them because of the `canonical` should still result in a `noindex` being set.

If you're going AMP-first, the `canonical` would reference its own page. But that contains the `noindex` as well, so even in that case, there's no danger of losing the `noindex` because of combining pages.

I don't think this is actually an issue in the particular case of canonical URLs on non-indexed AMP pages.

**Comment by jdevalk** [comment]
@schlessera I really respect your development skill, but in this case I think you shouldn't be making these decisions. I need a statement from @softplus that clarifies this or from another known Googler on the search side, as otherwise myself and our support team will be explaining this over and over and over again.

**Comment by softplus** [comment]
This is a non-issue. Theoretically, the given A->canonical->B, both A & B should be equivalent with regards to content & indexationability (noindex or not). In the cases here, as far as I understand them, it's either:

* A=B (self-canonical): then both A & B have the same noindex/not-noindex status automatically, which is fine
* A=AMP, B=HTML: if both A & B have the same noindex/not-noindex status (which they would if the same setting applies to both), then this is fine

**Comment by jdevalk** [comment]
So.... In which cases @softplus is this NOT a non-issue?

Are you saying that noindex is more important than canonical and I can thus have both on a page? Because that's definitely different from what I've understood before but something that _would_ make me very happy. If that's *not* what you're saying, can you please elaborate a bit more on when this is a problem and when it isn't, and why?
