### ISSUE TITLE
Indicate validation errors which occur on other URLs and warn when keeping them

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4751]
## Feature description

When an invalid script is being enqueued unconditionally on every template, every URL that is validated will have a validation error for that invalid markup being listed. When a user looks at the list of validation errors for a given URL, there is currently no indication of which errors are (potentially) unique to that URL and which are known to also occur on other URLs as well. There should be a link to see the list of URLs by opening the validation error single view in a new window. When they change the status of validation errors that occur on other URLs to _keep_ the invalid markup, there should be more explicit warnings that doing so will disable AMP potentially across the entire site. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
**Notes from meeting**

* WR > Say you validate 5 URLS, on everyone of those pages you have theme jQuery added to page (because it does that). Let’s say homepage has an additional script that’s just for carousel on homepage, and latest blog page just has one script for video embed. 
* Validated URL screen for all 3 will have jQuery as validation error. One will have error for carousel, another for video embed. But the jQuery script is common among all three, but you have no idea from validated url results that if you mark jQuery script as being kept (that you should keep it), there’s no indication that that action will affect other URLs on your site as well. 
* There needs to be some indicator with a validation error that says, “also occurs on X other URLs.” Somehow tell that it’s also effecting other URLs. 

*Describing where error appears on site.* 
* WR > When you go to error index, and see list of errors, there is in that context column that says URL count already. 5 URLs with this error, that info is available but we aren’t yet exposing in context of validated URL screen. We need to figure out a way to present in a way that makes sense. 
* John W > For design purposes, since we don’t know how many URLs scanned on given site, might be better to indicate vague terms, “this error occurring multiple pages<“ instead of saying 10,000 pages (might not have that level of detail.” 
* WR > Yes, better to be fuzzy. “This also occurs on at least X number of pages of your site.”

*Inverse*
* AM > Same info should be shared when error fixed. “This same error fixed in X other URLs. 
* WR > You won’t know until you re-run validator. When you fix validation error you don’t change anything about error itself, just eliminating from causing error in first place. You had 10 pages with jQuery on them, but when you DQ you’ll see jQuery gone from that page, but until you re-validate you won’t see it gone from other pages as well. 

*Garbage collection*
* John W > A given URL might be on 10k urls, but we only have data on 4 urls. Doesn’t it become less useful when dealing with less data? 
* WR > Not sure if garbage collection good idea. Going back and forth on it because problem if you have validation error and say reviewed and say it’s ok to remove it, and reviewed, if you garbage collect validated urls, then any errors on those URLs no longer have associated URL, and you click ‘clear empty” to remove those, then re-validate page  and see new error. You did review it, but it just cleared out because reference was removed. 
* WR > With site scanning we have a regular chron job re-checking key templates on ongoing basis. We should always have fresh validated URL for homepage, recent post, a page, author archive, etc. If you have a validation error by jQuery (added by theme), should always have at least multiple urls that reference that validation error. 

*Decouple storage*
* AS > We want to save space, but don’t want to lose info about what was reviewed already. But we can decouple storage of that. Could store hash of validation error instead of actual validation error. Then when you purge existing validation error, if it gets re-validated you could check against hash to see if review status. We’d never purge review status, much less data. Hash and status. If we really go down custom database tables route then that can be very efficient. Then we would just decouple soaring review status from storing validation errors, then we can purge validation errors without losing it. 
* WR > Validation error taxonomy essentially has that today with hash as slug and status being in term group. But then it also has json blob of error attributes, so it would mean essentially duplicating hash and storing status separate instead of storing status with error object itself.
