### ISSUE TITLE
Feature Request: AMP Link Toggle for Smartphone Visitors

### ISSUE THREAD

**Issue by andyforsberg** [Automattic/amp-wp#48]
So when it's toggled on all your AMP-enabled content links redirects to the AMP version of the content if the visitor is on a smartphone, but the links remain the same for non-smartphone users. This way visitors can take advantage of the speed increases even though they didn't access your content through Google's new AMP-powered carousel. If it's toggled off (default), then all your links point to the original content, even for smartphone visitors.

**Comment by mjangda** [comment]
This is a neat idea, @andyforsberg.

I think it's too early to do this, though. For now, it's better to let clients (i.e. Google Search, Twitter, apps, etc.) and themes handle this instead especially since AMP pages right now are pretty standalone (i.e. it's not easy to navigate through the site when on an AMP page). There are also a lot of headaches with setting/handling view defaults (see any mobile theme).

It would be good to revisit this after AMP is officially launched, though to see if it makes sense.

**Comment by andyforsberg** [comment]
Thanks @mjangda and touché.
