### ISSUE TITLE
Error in required structured data element

### ISSUE THREAD

**Issue by shabdghosh** [Automattic/amp-wp#4819]
Hello,

When I test my AMP pages with the Google testing tool, an error is return:
https://search.google.com/structured-data/testing-tool?hl=en#url=https%3A%2F%2Fshabdghosh.com%2Fmadhya-pradesh%2Fjabalpur%2F%3Famp

It also means my AMP pages are not valid in the Google Sear Console.

A required structured data is missing. How can I fix that issue ?

**Comment by westonruter** [comment]
The `image` field is `false`:

![image](https://user-images.githubusercontent.com/134745/83962872-161eea00-a856-11ea-9ec2-3d7962903f02.png)

Nevertheless, I don't believe this is coming from the AMP plugin since the issue is also present in the non-AMP page: https://shabdghosh.com/madhya-pradesh/jabalpur/

See rest results: https://search.google.com/structured-data/testing-tool?hl=en#url=https%3A%2F%2Fshabdghosh.com%2Fmadhya-pradesh%2Fjabalpur%2F

You'll need to investigate which plugin is adding that Schema.org markup to determine what is wrong and how to fix it.
