### ISSUE TITLE
AMP list Initialization from amp-state issue

### ISSUE THREAD

**Issue by kishanugc** [Automattic/amp-wp#4870]
### **AMP list failed to Initialization from amp-state** 
We try many times using amp state but amp plugin removes amp list code or removes SRC attribute. We have bind amp list SRC using amp state value according to the amp. Please check the below Screenshot for more detail. 
![image](https://user-images.githubusercontent.com/60003727/84768151-5ff39700-aff1-11ea-8e16-6f0943f5224a.png)

Right now, we have added an amp list example in the All Store page but amp plugin removes amp list. Please check the below URL & Screenshot for more detail. 
URL : https://devlop.wpengine.com/all-stores/

![image](https://user-images.githubusercontent.com/60003727/84768370-bbbe2000-aff1-11ea-933e-a3d401d9443e.png)

AMP playground URL it’s working fine. Please check below AMP Playground Screenshot for more detail. 

![image](https://user-images.githubusercontent.com/60003727/84768592-1f484d80-aff2-11ea-8633-8d31d22437d8.png)

The below link is a content amp list code.
https://devlop.wpengine.com/code.txt

**Please help me as soon as possible.**

**Comment by westonruter** [comment]
This was fixed in https://github.com/ampproject/amp-wp/pull/4548 but it is not yet in a stable release. If you are currently developing your site and are comfortable using the 1.6-alpha version, then I recommend using the latest build from `develop`: https://github.com/ampproject/amp-wp/wiki/Development-Builds

Otherwise, we may cherry-pick the fix specifically for the upcoming 1.5.4 release.

**Comment by westonruter** [comment]
I'll include this in a 1.5.x release.

**Comment by westonruter** [comment]
PR #4992 merged into `1.5` branch. Build for testing available at https://github.com/ampproject/amp-wp/pull/4992#issuecomment-654514947.
