### ISSUE TITLE
Reduce need to go three levels deep in Customizer

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/amp-wp#500]
Since there are **only** colour-related options available for AMP, I'm wondering if we can eliminate the need for users to click "Color Options" in the Customizer and instead go directly from "AMP" to this panel:

![customize_ hello world coherent 1 0 5 by automattic-4](https://cloud.githubusercontent.com/assets/7662449/19091483/d5d09ee8-8a50-11e6-8a60-e01a43782f5e.png)
## Current flow:

Appearance > AMP > Color Options > Panel where users can make selections
## Suggested flow:

Appearance > AMP > Panel where users can make selections

**Comment by mjangda** [comment]
This is more of a future-looking structure. The thinking here is that we (and other plugins/themes) can expand out and add more options that may not be related to colour (e.g. ["Content Options"](https://en.blog.wordpress.com/2016/08/30/introducing-content-options-an-easy-new-way-to-make-visual-changes-to-your-site/)).

Considering that users are unlikely to be going to the Customizer very often (more of a set-it-and-forget-it type thing), I don't think the extra click is that big an issue. Please let me know if you disagree though (especially since you work more closely to users than I do).

**Comment by allancole** [comment]
I see what you mean as far as this being a future-looking structure. But I think this is more of a UX concern for us Theamers. Right now, there’s only 3 options on the panel, which will turn into 4 when we add that site logo feature. That still leaves plenty of room to fit additional options (like content options) all on that one panel.

Since the AMP options are so limited and simple, I think it’ll just be easier for the user to configure everything in one place as opposed to bouncing back and forth between panels/sections. This way we could get rid of that “Color Options” title which doesn’t really make much sense anyway. 

If we can squeeze this into tomorrow mornings release, that’d be awesome, but understandable if there isn’t enough time. 

Here’s what I’m thinking:

![image](https://cloud.githubusercontent.com/assets/709581/19134129/1ad154f4-8b2a-11e6-9a38-b3328f725204.png)

![image](https://cloud.githubusercontent.com/assets/709581/19134212/a2331342-8b2a-11e6-8a25-ecee717e362f.png)

**Comment by amedina** [comment]
Will close this issue now since and will add this feedback into our planning. Thanks!
