### ISSUE TITLE
Add microcaching to capture WordPress page

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5002]
## Feature description

I have the hypothesis that somewhat often, a regular WordPress page will be generated, and then after that, the AMP page will be generated with only a small delay in-between (or vice-versa, AMP and then WP regular).

I think this can happen:
- in paired browsing mode
- probably during Google indexing (where Google sees the AMP rel link after indexing the page)
- when doing validation (which might be twice the AMP page instead of regular + AMP)
- ...?

In all of these cases, the regular WordPress page being generated is always the same, regardless of whether it is followed by an AMP transformation or not.

I'd like to experiment with microcaching that captures a regular WordPress page and caches it for a short amount of time, like 5 seconds or so. The goal would be to invest a small amount of memory (or DB space) to avoid generating the regular page multiple times, like "WP and then (WP + AMP)". We want to have this be "WP( as-is + AMP) instead".

In the cases where this would work, we would basically strip the WP generation time off of the time we need to generate an AMP page. After the recent performance fix, it seems like the AMP generation takes less time than the WP generation, so this would be a huge win.

Note: On a site with page-caching, this would not change anything for the warm caches, but it would improve the initial cache population time and save server resources in general.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by askmeoffers** [comment]
Sounds Interesting we will wait for this updates @schlessera and many thanks for building AMP optimizer framework.

**Comment by westonruter** [comment]
> In all of these cases, the regular WordPress page being generated is always the same, regardless of whether it is followed by an AMP transformation or not.

I don't think this is the case. Themes and plugins will often vary the output of the page based on whether `is_amp_endpoint()`.

**Comment by amedina** [comment]
+1

**Comment by schlessera** [comment]
> I don't think this is the case. Themes and plugins will often vary the output of the page based on whether is_amp_endpoint().

Ah, yes, of course.

Do you think it would make sense to detect usage of `is_amp_endpoint()` and micro-cache if it was not used?

**Comment by westonruter** [comment]
No, because `is_amp_endpoint()` will be used on _every_ page, if not by a third party theme/plugin theme AMP plugin itself. For example, when `is_amp_endpoint()` is true then the AMP plugin will preemptively not use MediaElement.js and it will preemptively use AMP components for some oEmbeds, for example. In other words, the plugin does as much as it can do during template generation to create the markup that will be as suitable for AMP as possible so that when the sanitizers run they have less work to do, as often they don't have the needed context for _why_ a bit of markup is on the page. By hooking into template generation the AMP plugin can contextually serve the exact appropriate AMP markup. And this depends on `is_amp_endpoint()`.
