### ISSUE TITLE
Allow filtering list of eligible post types

### ISSUE THREAD

**Issue by swissspidy** [Automattic/amp-wp#5050]
## Feature description

In the Web Stories plugin we currently skip AMP for the `web-story` post type entirely using the `amp_skip_post` filter.

Since the Stories post type is `public`, it will appear in the list of eligible post types on the settings screen:

<img width="948" alt="AMP Plugin Stories content type" src="https://user-images.githubusercontent.com/841956/87568386-df928580-c6c5-11ea-9796-795cf5283224.png">

However, due to us using the `amp_skip_post` filter, (un)checking that checkbox won't have any effect.

Because of this, it might be nice if we're able to remove the Stories post type from from that list.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Filter can be added here in `AMP_Post_Type_Support::get_eligible_post_types()`:

https://github.com/ampproject/amp-wp/blob/7dc643bfcae164963f3244596944fa04998698f8/includes/class-amp-post-type-support.php#L35-L50

**Comment by westonruter** [comment]
I think we need to do two things:

1. Eliminate showing the notice if the post type is not supported.
2. Discontinue subsuming the post types under the “all templates supported” checkbox. As demonstrated by the needs of web stories, there can be public post types which should not be processed by the AMP plugin even when all templates of the site should otherwise be served as AMP. This will eliminate the need to use the the more granular `amp_skip_post` filter.

**Comment by westonruter** [comment]
As opposed to a filter, we could also introduce a `show_in_amp` attribute on the actual `WP_Post_Type` objects. It could be `true` by default for any `public` post, but then you could override it to be `false` which could have the same effect as the filter. Maybe not ideal because that would be adding a new variable to a class that doesn't define it. I did do this in the Customize Posts plugin, however (buy my IDE would complain to me): https://github.com/xwp/wp-customize-posts/blob/bfc6b4cd8344537edc2af5451b5a4a8d75d96293/php/class-wp-customize-posts.php#L203-L205

**Comment by swissspidy** [comment]
What about post type supports?

**Comment by westonruter** [comment]
The plugin already supports an `amp` post types support, but it is used to indicate which post types should be enabled _by default_. However, the user can enable AMP for all post types or disable AMP for any post types using the admin UI. Therefore `amp` post type support is only a positive signal for post types that _do_ support AMP. There is no way to use post type support to indicate that a post type _doesn't_ support a feature: I don't think a `noamp` post type support flag makes sense or is in line with how WordPress normally does things.

**Comment by swissspidy** [comment]
Awesome @westonruter!

Opened https://github.com/google/web-stories-wp/issues/3257 to make use of this in the Web Stories plugin.
