### ISSUE TITLE
Optimize hero images

### ISSUE THREAD

**Issue by sebastianbenz** [Automattic/amp-wp#5055]
## Feature description

The validator support for server-side rendering amp-img as img has been merged ([cl/321463348](http://cl/321463348)). Would be great to also support this in the AMP WP plugin. As a reference on how to add it, you can find the AMP Optimizer integration [here](https://github.com/ampproject/amp-toolbox/pull/859).

A few notes on the AMP Optimizer integration:

1.  It will either auto-detect a single hero image on the page, or look for hero images explicitly being marked via the `data-hero` attribute. 
2. For each detected hero image (up to a max of 2) it will generate a preload (if no `srcset` is defined) and inject an img into the amp-img element (this also works for amp-iframe placeholders). 
3. It does not specify `loading=lazy/eager` (see https://github.com/ampproject/amphtml/pull/29025#discussion_r453148028). 

//cc @westonruter @schlessera 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This is great.

For added heuristics in the WordPress context, we may be able to use the same logic that is being used for lazy-loading images that landed in 5.5-beta: the `loading=lazy` is omitted from images that are likely to be used in the first viewport. We could use the same logic to add `data-hero` to the page if no `amp-img` elements exist on the page with that attribute. See https://core.trac.wordpress.org/ticket/50425

**Comment by westonruter** [comment]
Landed in AMP core: https://github.com/ampproject/amphtml/issues/28672

AMP Toolbox Optimizer PR: https://github.com/ampproject/amp-toolbox/pull/880

**Comment by westonruter** [comment]
As discussed just now, let's also include the hero preloading logic detection for CSS background images that are defined with inline `style` attributes. For example, the Cover Image block in core is rendered on an AMP page as follows:

> ![image](https://user-images.githubusercontent.com/134745/94045692-a1c87200-fd84-11ea-93fa-7b54489d4c80.png)

In the same way that a transformer is looking for `amp-img@src`, `amp-video@poster`, `amp-iframe > amp-img` (and `amp-youtube` per https://github.com/ampproject/amp-wp/pull/5350/files#r485283525), it can also look for any element `@style` (or `@data-amp-original-style`) to extract the `background-image` URL, as another candidate for the hero image.

One complication here is that an element with an inline CSS background could be tiny, and we'd have no way of using `isTinyElement` to detect whether it is too small to be a candidate. Perhaps this interplays with whether the element has `data-hero` as referenced in https://github.com/ampproject/amp-wp/pull/5350#issuecomment-697298463. Otherwise, we could have WP-specific support, so we'd automatically consider elements that have `wp-block-*` as a class name to be considered to be not tiny.

**Comment by schlessera** [comment]
I am planning on adding a WP-specific transformer that is responsible for tagging the best images with the `data-hero` attribute. This will be in the plugin, not the Optimizer library.

**Comment by pierlon** [comment]
**QA Passed**

Images within the initial viewport are being optimized and receive the `data-hero` attribute:

![image](https://user-images.githubusercontent.com/16200219/116329282-88742200-a7ba-11eb-8e55-d0ea1af75515.png)
