### ISSUE TITLE
Infinite Scroll: amp-next-page - Add next-page-hide to #wpadminbar

### ISSUE THREAD

**Issue by rickalee** [Automattic/amp-wp#5213]
For cleaner implementation of infinite scroll via amp-next-page, it would be ideal to have next-page-hide on #wpadminbar by default or option to toggle this on. 

https://amp.dev/documentation/components/amp-next-page/

**Comment by westonruter** [comment]
Yes, good idea.

**Comment by schlessera** [comment]
Sounds like this would add a constant effort to add `next-page-hide` to the admin bar, even on sites that don't make use of `amp-next-page` at all? So that would trade a bit of implementation effort per `amp-next-page` use for a bit of overhead on _all_ sites.

I think this should just be a part of the actual `amp-next-page` implementation instead.

Now, if the AMP plugin would provide a streamlined way of providing a generic `amp-next-page` implementation instead...

**Comment by westonruter** [comment]
Something else that came to mind… if `amp-next-page` is paginating through singular posts, then the admin bar from the next page actually _should_ be displayed instead of the admin bar from the first page, as then the Edit Post link in the admin bar would reflect the current post being viewed not the first post being viewed.

**Comment by westonruter** [comment]
> Now, if the AMP plugin would provide a streamlined way of providing a generic `amp-next-page` implementation instead...

I've also just opened https://github.com/ampproject/amp-wp/issues/5311 to look at implementing support in the core themes.
