### ISSUE TITLE
Wrong redirection of portfolio pages

### ISSUE THREAD

**Issue by PaolaBozhilova** [Automattic/amp-wp#5249]
Hello, please help with the following problem. 
In Reader mode, when I select an AMP version of a "portfolio" page, it redirects me to a similar non-AMP version of a "product" type page (in the online store). When such a similar page does not exist, it redirects me to the AMP version of the 404 page.

Thanks in advance!

**Comment by westonruter** [comment]
You're using v2.0.0-RC1, correct? And are you using a new Reader theme or AMP Legacy?

Please provide a URL that is unexpectedly redirecting on mobile.

**Comment by westonruter** [comment]
Also, providing your current Site Health info would be helpful.

**Comment by PaolaBozhilova** [comment]
Yes, I use v2.0.0-RC1, and I chose Twenty Seventeen as a theme, but when it switches to AMP Legacy, everything is normal.
I sent you Site Health info.

**Comment by westonruter** [comment]
Again, please provide a URL that is unexpectedly redirecting on mobile.

**Comment by PaolaBozhilova** [comment]
https://packin.net/portfolio-item/метална-опаковъчна-лента-чембер/?amp **redirects to** https://packin.net/product/метална-опаковъчна-лента-чембер/
https://packin.net/portfolio-item/ръчни-обтегачи/?amp **redirects to** 404 https://packin.net/portfolio-item/ръчни-обтегачи/?amp

**Comment by westonruter** [comment]
Ah, have you registered the post type in the theme itself? If so, then this is a known issue. The AMP plugin isn't currently warning you of this, but in https://github.com/ampproject/amp-wp/issues/4795 it will. Any post types, shortcodes, taxonomies, blocks, etc will not be available when you select a Reader theme because the AMP plugin will switch the theme entirely for the AMP response.

The ideal resolution here is for you to move the custom post type definitions to a custom plugin. This is a best practice anyway for WordPress. 

Alternatively, you can turn off AMP for that post type in the supported templates section. This will prevent the problem from happening, but you won't be able to use the post type in AMP.

**Comment by PaolaBozhilova** [comment]
I have not registered nothing in the theme itself.

**Comment by westonruter** [comment]
What plugin is registering the Portfolio Item post type?

**Comment by westonruter** [comment]
You may not in your child theme, but I believe your parent theme is registering the Portfolios.

**Comment by PaolaBozhilova** [comment]
I'm sorry, I didn't understand the question at first. In my main theme "Beteme", of course it is registered, but I do not think that a special plugin is used, I think it is built into the theme. I want to have an amp on portfolio pages. When the official version comes, will there be a description of how users deal with specific situations?

**Comment by westonruter** [comment]
Since the post type is built into the theme this means that it won't be available when using a Reader theme. Using a Reader theme means that the active theme is not used at all.

In #4795 we will warn users when they have a post type registered in the theme. But that will be after v2.0 is released. 

The quickest fix for you is to turn off AMP for the Portfolio post type in the AMP settings. 

Otherwise, what you could do is locate the code responsible for registering portfolios and put it into a new plugin which can be active on both AMP and non-AMP requests.

Thank you for reporting this issue. It highlights the need for us to better guide users for how to deal with this scenario.
