### ISSUE TITLE
AMP section not appearing at Appearence/customize menu 

### ISSUE THREAD

**Issue by fellyph** [Automattic/amp-wp#5253]
## Bug Description

AMP section doesn't appears at the customize menu, it just appears at the appearance menu or is missing? 

## Expected Behaviour

AMP can be a option at the appearance/customize menu

## Steps to reproduce

1. Go to Appearance
2. Click on customize
3. AMP option is not available

## Screenshots

![Screen Shot 2020-08-21 at 07 32 03](https://user-images.githubusercontent.com/330792/90859620-7535ca80-e380-11ea-8d03-b2004a678fdb.png)

## Additional context

 - WordPress version: 5.5
 - Plugin version: 2.0 RC1
 - Gutenberg plugin version (if applicable):no
 - AMP plugin template mode: reader
 - PHP version: 7.3
 - OS:
 - Browser: chorme 84
 - Device: device

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
You are customizing the non-AMP version of your site, so the AMP section would not be shown here since it is not relevant.

We could do a better job of communicating this by adding a preview notice stating the non-AMP version is being customized, and providing a link to customize the AMP version. Currently, a similar message is shown when the AMP version of a Reader theme is being customized:

![image](https://user-images.githubusercontent.com/16200219/90861691-aeb80700-e37b-11ea-8d7a-32d33cecd4f6.png)


Thoughts @westonruter?

**Comment by westonruter** [comment]
Yeah, that's a good point. It's expected that the AMP panel not to appear because when a Reader theme is selected, the user needs to switch to the AMP Customizer as a whole. However, we could restore the AMP panel in the list but as soon as they tap to open we could navigate them to the AMP Customizer. That could also be disorienting. Another option would be the AMP toggle that appears next to device previews, but that's also problematic because something AMP/non-AMP requires reloading the entire page and not just the preview. Adding an AMP Customizer link to the top could work, but I think it should be more subtle than the notice that appears in the AMP Customizer to go back to the non-AMP Customizer.
