### ISSUE TITLE
Include more sandbox values by default in amp-iframe

### ISSUE THREAD

**Issue by jamesozzie** [Automattic/amp-wp#5256]
Some services that provide embed code such as OneDrive's Excel feature require the use of the `allow-forms` sandbox value. To account for these situations ensure the value is included within the sandbox attribute. 

One example support topic below:
https://wordpress.org/support/topic/issue-with-embedding-ondrive-documents/#post-13292729

**Example embed code as provided from OneDrive** (Not working)
`<iframe src="https://onedrive.live.com/embed?cid=3439BE085D1A0C76&amp;resid=3439BE085D1A0C76%218125&amp;authkey=AGvw6cBocXMvQhc&amp;em=2" width="402" height="346" frameborder="0" scrolling="no"></iframe>`

**Example working embed work**  (Working)
`<iframe src="https://onedrive.live.com/embed?cid=3439BE085D1A0C76&amp;resid=3439BE085D1A0C76%218125&amp;authkey=AGvw6cBocXMvQhc&amp;em=2" width="402" height="346" frameborder="0" scrolling="no" sandbox="allow-scripts allow-forms allow-same-origin  "></iframe>`

_Note that the `allow-forms` value alone doesn't render the form._ 

Examples and console errors can be viewed [here](http://orient.one/900/onedrive-excel/?amp). 

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This is the line of code in question:

https://github.com/ampproject/amp-wp/blob/dce58640f7c36befda67b145d00ec4f40c2278eb/includes/sanitizers/class-amp-iframe-sanitizer.php#L29

The question is: where do we draw the line on adding sandbox values? The best practice is to only include sandbox values that are needed.

**Comment by westonruter** [comment]
We could also add a tailored embed handler for such embeds, given the large number of embeds from that service.

**Comment by jamesozzie** [comment]
> We could also add a tailored embed handler for such embeds, given the large number of embeds from that service.

Sounds good. Rather than tailoring is specifically for one service I guess we can add others that may require the same values in time (should we come across more).

**Comment by westonruter** [comment]
Then again, it doesn't make much sense to me that we allow scripts by default but not forms. If anything, scripts would be more concerning than forms. We should investigate why the current sandbox value was chosen.

**Comment by pierlon** [comment]
It was added via https://github.com/ampproject/amp-wp/pull/70/commits/3bf1c8a55ea7a0b5da619329879f4d7817e7de41, and quoting from commit message:

> Set allow-scripts/allow-same-origin for iframes. If not set, otherwise the iframe is mostly useless.

**Comment by westonruter** [comment]
Seems like it was just overlooked then. Forms inside of iframes are very important for things like polls, commenting, etc. Let's do a review of the other sandbox values to see if we are missing any other clear gaps and add what makes sense by default.

**Comment by pierlon** [comment]
Here's the list of possible sandbox restrictions: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox.

From that list I'd say `allow-forms` and `allow-popups` would be the only ones worth considering. As for popups, they would be relevant in scenarios where the user wants to view more information about embedded content such as a map or YouTube video.

**Comment by westonruter** [comment]
Another which I think is needed is `allow-top-navigation-by-user-activation` to allow navigation to links inside of the iframe. Also perhaps `allow-presentation` if that is needed for fullscreen.

**Comment by westonruter** [comment]
I think `allow-presentation` would make sense for embedding a presentation like from Google Slides. In fact, I can see that one of my own posts has this issue: https://weston.ruter.net/2019/07/12/amp-for-javascripters/

Nevertheless, the issue is for the YouTube video and not the Slides:

![image](https://user-images.githubusercontent.com/134745/90971419-de265b00-e4c4-11ea-8fa6-96801b552cab.png)

Markup:

```html
<amp-iframe class="youtube-player amp-wp-enforced-sizes amp-wp-cbdc213 i-amphtml-layout-intrinsic i-amphtml-layout-size-defined" width="1000" height="563" src="https://www.youtube.com/embed/tiQcA7cwEMo?version=3&amp;rel=1&amp;fs=1&amp;autohide=2&amp;showsearch=0&amp;showinfo=1&amp;iv_load_policy=1&amp;wmode=transparent" allowfullscreen="" sandbox="allow-scripts allow-same-origin" layout="intrinsic" data-amp-original-style="border:0;" i-amphtml-layout="intrinsic">...</amp-iframe>
```

It seems like the lack of `allow-presentation` is an oversight here as well since the `amp-iframe` does have `allowfullscreen`. 

It seems that what the `allow-presentation` sandbox enables (at least in Chrome) is the ability to cast. It seems that if I don't have that sandbox attribute present, then clicking the cast button does nothing, whereas when the sandbox attribute is present then clicking the cast button causes Chrome's cast menu to appear.

![image](https://user-images.githubusercontent.com/134745/90971545-f5197d00-e4c5-11ea-9f78-1db4062df89a.png)

So yeah, we should add `allow-presentation` as well.

----

I'm surprised that `amp-youtube` is not being used, even though the YouTube block is being used:

```html
<!-- wp:core-embed/youtube {"url":"https://www.youtube.com/watch?v=tiQcA7cwEMo","type":"video","providerNameSlug":"youtube","className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed-youtube wp-block-embed is-type-video is-provider-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=tiQcA7cwEMo
</div></figure>
<!-- /wp:core-embed/youtube -->
```

This turns out to be an issue with Jetpack. For some reason Jetpack is causing an `amp-iframe` to be served when this option is enabled:

![image](https://user-images.githubusercontent.com/134745/90971514-bd123a00-e4c5-11ea-9c70-b857220c59e6.png)

**Update:** See https://github.com/Automattic/jetpack/issues/16946.

**Comment by westonruter** [comment]
I the new Loom embed in Jetpack and I saw that this issue is present there as well. 

Given this `post_content`:

```html
<!-- wp:embed {"url":"https://www.loom.com/share/0281766fa2d04bb788eaf19e65135184","type":"video","providerNameSlug":"loom","responsive":true,"className":"wp-embed-aspect-4-3 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed is-type-video is-provider-loom wp-block-embed-loom wp-embed-aspect-4-3 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.loom.com/share/0281766fa2d04bb788eaf19e65135184
</div></figure>
<!-- /wp:embed -->
```

Attempting to click on the video title also causes the iframe block opening a window in a new tab:

> ![image](https://user-images.githubusercontent.com/134745/95500982-83559f80-095c-11eb-9302-ab35dc41aeed.png)

Same goes for when attempting to share on Twitter:

> ![image](https://user-images.githubusercontent.com/134745/95501087-a3855e80-095c-11eb-9e80-9bf2e30278a0.png)

**Comment by westonruter** [comment]
Again, this only applies to `iframe` elements that have have _no_ `sandbox` by default. When an `iframe` lacks a `sandbox`, then it has no restrictions. So by adding new `sandbox` capabilities to iframes that, we're not introducing any _unexpected_ capabilities. We are just unbreaking certain embedded pages that expected to be inside of sandboxless iframes. That being said, here's what I for including in the default `sandbox`:

| Sandbox Token                             | Included | Rationale
|-------------------------------------------|----------|----------
| `allow-downloads`                         | ✅       | Useful for downloading documents, etc.
| `allow-downloads-without-user-activation` | 🚫       | Experimental per MDN. Bad UX.
| `allow-forms`                             | ✅       | For embeds like polls.
| `allow-modals`                            | ✅       | For apps to show `confirm()`, etc.
| `allow-orientation-lock`                  | ✅       | Since we `allowfullscreen`, useful for games, etc.
| `allow-pointer-lock`                      | ✅       | Useful for games.
| `allow-popups`                            | ✅       | To open YouTube video in new window, for example.
| `allow-popups-to-escape-sandbox`          | ✅       | Useful for ads
| `allow-presentation`                      | ✅       | To cast YouTube videos, for example.
| `allow-same-origin`                       | ✅       | Previously included by default. Removed if iframe is same origin.
| `allow-scripts`                           | ✅       | An iframe's primary use case is custom JS. Previously included by default.
| `allow-storage-access-by-user-activation` | 🚫       | Experimental per MDN.
| `allow-top-navigation`                    | 🚫       | Poor user experience. Next used instead.
| `allow-top-navigation-by-user-activation` | ✅       | Key for clicking `target=_top` links in iframes.

Any concerns?

**Comment by westonruter** [comment]
**QA Passed**

I tried adding the OneDrive `iframe` with this markup:

```html
<iframe src="https://onedrive.live.com/embed?cid=3439BE085D1A0C76&amp;resid=3439BE085D1A0C76%218125&amp;authkey=AGvw6cBocXMvQhc&amp;em=2" width="402" height="346" frameborder="0" scrolling="no"></iframe>
```

It embeds successfully:

> ![image](https://user-images.githubusercontent.com/134745/96029740-edb08900-0e0f-11eb-952a-c6b453b53bff.png)

AMP markup:

```html
<amp-iframe src="https://onedrive.live.com/embed?cid=3439BE085D1A0C76&amp;resid=3439BE085D1A0C76%218125&amp;authkey=AGvw6cBocXMvQhc&amp;em=2" width="402" height="346" frameborder="0" scrolling="no" sandbox="allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-scripts allow-top-navigation-by-user-activation" layout="intrinsic" class="amp-wp-enforced-sizes i-amphtml-layout-intrinsic i-amphtml-layout-size-defined" i-amphtml-layout="intrinsic">
	<i-amphtml-sizer class="i-amphtml-sizer">
		<img alt="" aria-hidden="true" class="i-amphtml-intrinsic-sizer" role="presentation" src="data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzM0Nicgd2lkdGg9JzQwMicgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJyB2ZXJzaW9uPScxLjEnLz4=">
	</i-amphtml-sizer>
	<span placeholder="" class="amp-wp-iframe-placeholder"></span>
	<noscript>
		<iframe src="https://onedrive.live.com/embed?cid=3439BE085D1A0C76&amp;resid=3439BE085D1A0C76%218125&amp;authkey=AGvw6cBocXMvQhc&amp;em=2" width="402" height="346" frameborder="0" scrolling="no"></iframe>
	</noscript>
</amp-iframe>
```

Note that `allow-forms` is now included among the `sandbox` values.
