### ISSUE TITLE
Skip bundling docs (generation code) in releases

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5279]
## Feature description

When building a release ZIP, we should either omit the doc generation code (`docs/docs.json`, `docs/includes`, `docs/src`, `docs/templates`), or the entire `docs` subfolder, depending on whether we want to ship reference docs with an installable plugin or not.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I ran `npm run build:prod` and no new files from #5274 were included in the `build` directory. This is because the `docs` directory is not included among the `productionIncludedRootFiles` in the Gruntfile:

https://github.com/ampproject/amp-wp/blob/0e1da8b394909901d9085b34cba0fedfc686555c/Gruntfile.js#L6-L17
