### ISSUE TITLE
2 Important Problems With WordPress Plugin

### ISSUE THREAD

**Issue by Humoropedia** [Automattic/amp-wp#53]
The most important problem is that the pages generated by this plugin do NOT show the Google ads:  here is a page of Monty Python quotes [NOT generated](http://humoropedia.com/monty-python-and-the-holy-grail-quotes/) by this plugin, and here is the same page generated [by this plugin](http://humoropedia.com/monty-python-and-the-holy-grail-quotes/amp/). As you can see from the links, plugin strips Google ads and replaces them with pure code. 

The second problem concerns the usability of this plugin. It does NOT add "amp" at the end of existing pages. Rather, you can create those links yourself. However, how can a site with hundreds of pages and thousands of links manually replace every link with the version that has 'amp' at the end of itself? This is impossible. Therefore, this plugin has to automatically find and replace instances of existing links. Otherwise, Google's bots are not going to index AMP pages.

**Comment by robwent** [comment]
If you check the source code of your page you will see a link

    <link rel="amphtml" href="http://humoropedia.com/monty-python-and-the-holy-grail-quotes/amp/" />

That tells search engines that there is an amp version of the page available.

**Comment by mjangda** [comment]
Thanks for the feedback!

> As you can see from the links, plugin strips Google ads and replaces them with pure code.

I've opened #54 to look into this.

As for Google and other ads, we haven't figured out the best approach to it yet. For now, I think we'll leave it up to individual sites to utilize the plugin hooks to insert their ads, but open to suggestions.

**Comment by Humoropedia** [comment]
Thanks for taking time to reply, Mohammad and Robert! 

Based on your wonderful replies, I have more questions: 

1) How long will it take Google to add my AMP version of Monty Python and Holy Grail quotes page to its mobile search listings?

2) Is there a need to submit a new sitemap to Google or notify it of an availability of AMP pages?

I think that information about search engine indexation would help everyone considering AMP project, so if you guys added that information to the AMP homepage, that would help convert more site owners.

Sincerely Yours,
Roman Marshanski
Founder of Humoropedia.com, the funny site for all and none

**Comment by robwent** [comment]
Hi Roman,

I'm really just someone who is interested in the project and had a look through the issues to see what is going on.

I would assume that Google indexing the pages is at their discretion, a bit like they don't show microdata in search results for all sites that implement it. 

I would have thought that a sitemap isn't needed as it's more of an alternative view of your page for certain devices rather than a different page.
If you submit your sitemap for the standard pages then they should get crawled and the amp pages would get picked up.

You have a point with the internal links that I didn't think about until after my reply. It's probably already there but wordpress generated links like next post should also link to the amp versions. I only had a quick play as I saw the repo when looking for the official project.

This is all very new so it's dificult for anyone to give advice about indexation until Google lets out a bit more information about how it will work.
I guess that will also come down to how many people adopt the idea. 

Let us know how your site gets on!

Rob
(A nobody :)

**Comment by Humoropedia** [comment]
Robert, thank you for such detailed response. I really appreciate that you took the time to share your wisdom with me. I emailed someone responsible for AMP project, so I will let you know as to the response I get from him. You have awesome site by the way, so if I were you, I would call myself Awesome Web Developer.

**Comment by robwent** [comment]
I'd be really interested to hear the response!

I've been meaning to remake my site for years, it's very out of date with what I actually do!
