### ISSUE TITLE
AMP causes gutenberg editor crash on very long posts 

### ISSUE THREAD

**Issue by roo2** [Automattic/amp-wp#5308]
## Bug Description

On a very long post (more than 120000 characters in total), when the AMP plugin is active, the gutenberg editor will fail to load with the following error on the console:
```
index.js?ver=e60bd1460738ba2b6388866b5ee392db:1 Uncaught (in promise) TypeError: Cannot read property 'length' of null 
```
<img width="703" alt="Screen Shot 2020-09-01 at 6 04 39 PM" src="https://user-images.githubusercontent.com/22446385/91824170-b03bd600-ec7d-11ea-94b2-47059f008dd5.png">

When creating text content, I recommend this online string generator, some others actually have a silent limit on the total number of characters generated 

https://onlinerandomtools.com/generate-random-string

The classic editor will still be able to load the post, the published post still renders correctly on the live site, but the gutenberg editor will completely fail to load with the above error on the console.

The error seems to be thrown from within gutenberg code, but I found that after disabling the AMP plugin, the editor loads correctly

![Sep-01-2020 18-34-12](https://user-images.githubusercontent.com/22446385/91827204-dfecdd00-ec81-11ea-9020-05e457508925.gif)

**Comment by pierlon** [comment]
Here's the stacktrace with source maps:

![image](https://user-images.githubusercontent.com/16200219/91866532-28949e00-ec62-11ea-9f60-2dd119c7a139.png)

The error seems to be due to `document.length` being undefined:

![image](https://user-images.githubusercontent.com/16200219/91866775-6396d180-ec62-11ea-9688-fcdaa4451816.png)

I haven't found the reason as to how the plugin causes this error as yet, however.

**Comment by pierlon** [comment]
So the issue lies within this block of code: https://github.com/ampproject/amp-wp/blob/a6514231d6e15568d7698c86eb5f404b552e3ff2/src/ObsoleteBlockAttributeRemover.php#L95-L100

This issue is that the `preg_replace_callback` is returning `null` instead of the original string. According to the [docs](https://www.php.net/manual/en/function.preg-replace-callback.php#refsect1-function.preg-replace-callback-returnvalues) that only happens when an error has occurred:

>  preg_replace_callback() returns an array if the subject parameter is an array, or a string otherwise. On errors the return value is NULL.

In this case the error is due to a catastrophic amount of backtracing being done on the input. For example, if you have:

```php
preg_replace(
    '#(?P<block_comment><!--\s*+wp:\w+.*?-->\s*+)(?P<start_tag><[a-z][a-z0-9_:-]*+\s[^>]*+>)#s',
    'replacement',
    '<!-- wp:paragraph -->' . str_repeat('a', 111101)
);
```

It would take 1000054 steps for the regex engine to figure out that the there is no `<` character after `<!-- wp:paragraph -->`. Here's a [3V4L](https://3v4l.org/jWORF) demoing the issue.

**Comment by westonruter** [comment]
I see. And so this PHP error is causing `content.raw` to be `null` and not a string, and thus `length` is not defined.

Good investigation. We'll ship a fix for this in v2.0.1.

**Comment by mdrovdahl** [comment]
Hi @westonruter =) 

Just adding a +1 as [we](http://wpspecialprojects.wordpress.com/) have a popular site that ran into this today. We're going to rollback to 1.5.5 until the fix lands.

**Comment by westonruter** [comment]
Fix should be out this week. Tomorrow even.

**Comment by westonruter** [comment]
@roo2 @mdrovdahl Actually, the fix (#5313) has landed just now. We have a 2.0.1 pre-release build for you to test if you're willing: https://storage.googleapis.com/ampwp_github_artifacts/refs/heads/2.0/prod/amp.zip (URL to ZIP reflects current state of `2.0` branch)

**Comment by roo2** [comment]
hey thanks for getting this fix out so quickly @westonruter , and yep I can confirm that the 2.0.1-pre-release fixes the issue we've been seeing 👍

**Comment by westonruter** [comment]
Thank you for testing! 

Moving to QA Passed.

**Comment by westonruter** [comment]
@mdrovdahl @roo2 [v2.0.1](https://github.com/ampproject/amp-wp/releases/tag/2.0.1) is now published on WordPress.org.
