### ISSUE TITLE
Add (fragment) caching to validation

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5381]
## Feature description

Doing a validation request is an expensive operation. In a lot of cases, it might not actually be needed, though, as the markup to be validated has not actually changed, or only changed in a way that wouldn't impact the validation results.

To accelerate these cases, we could hash the markup and store that hash with the validation result. If a validation request comes in, the hash of that markup is compared with the hash that is stored with the already existing validation, and if they match, no validation is needed, the old result can just be reused.

The hash should include the set of environment information that can impact the validation result, like the list of active sanitizers and their configuration.

As it is more likely to often have small changes to a page, rather than always validating the exact same page, we can go one step further and apply russian doll caching techniques here. There could be several levels that this hashed comparison is made, provided that the validation can be done on partial content.

As an example, we could first compare a hash of the entire document. If that fails, do a hash of all main HTML elements. If that fails drill down into the element(s) that failed and compare at the next depth level. We'll have to experiment with the logic here to find the right balance between cost of caching and cache hit/miss ratio.

Also, for a failed hash, we could examine that particular piece of content and see whether the change was relevant for validation or not. As an example, if the change was only fixing a typo in a random word in a paragraph, validation results would not change and does validation doesn't need to be redone. This should then just update the relevant hashes.

For this to work, hashes need to be stored with validation results, and at the needed granularity. This will need a rethink of how validation results are stored.

The expected end goal is that worst case scenario is that a full validation request is redone, and had only a small amount of overhead due to hashing. And hopefully, for a large percentage of cases, only a partial validation is being done or no validation at all. Average time spent validating should drastically drop at the expense of a bit more storage space needed for validation results.

As a side-effect, we'd have an improved way of checking whether a given validation result is stale or not.

Note: This needs a POC to see whether:
- partial validation works as expected
- partial validation is reliable in that it always produces the same result as full-page validation for a given extract of the markup
- hashing of the content is reliable in that no plugin filters can interfere in such a way that a cache hit would produce the wrong validation result

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I have doubts as to whether this will yield meaningful results due to how unencapsulated content in WordPress is. 

For example, if I have a block and I toggle the value of one attribute, the effect may not be limited to the element containing the rendered block markup. Namely, an attribute change could cause a script to be added/removed elsewhere in the page. Filters on `the_content`mean there's no way to know what impact a change will have.

Another example is some block that shows a post list. On a homepage template, there may be many of these blocks and there may be server-side logic that prevents duplicate posts from displaying. Let's say a block adds some JS to the page when there is more than 3 posts in a block to "Show More". In this way, changing the query for one of the blocks could cause the JS to end up getting added/removed for another block. In this same way, it is unreliable to render content in isolation from other content. If such a block were rendered by itself, it wouldn't have the context of other blocks on the page. This is a similar problem that [Selective Refresh in the Customizer](https://make.wordpress.org/core/2016/02/16/selective-refresh-in-the-customizer/) seeks to solve. Nevertheless, for themes and widgets it had enabled on an opt-in basis given that the issue of side effects.

Yet another example would be that making a change to a block (e.g. bolding some text) could end up causing the tree shaker not being able to remove a `strong` style rule, which in turn causes the total CSS to go over 75KB. In that case, a validation error would result on the frontend. But if we only validate the bloc in isolation it would not be caught since the tree shaker would not have the context of the entire page.

Lastly, I think the most expensive part of validation is actually making the request to WordPress and firing up the post-processing logic and source attribution. My suspicion is that validating a subset of the page vs the page as a whole is only going to result in a linear reduction in the time it takes to validate a page, and that any the performance gains would not warrant the loss in the fidelity of the results.
