### ISSUE TITLE
[amp-autocomplete ] Fix invalid URL protocol for local development

### ISSUE THREAD

**Issue by artneo-io** [Automattic/amp-wp#5402]
## Bug Description

`Invalid URL protocol http: for attribute src` for amp-autocomplete on local development.

The plugin triggers `INVALID_URL_PROTOCOL` for `//localhost:3000/wp-json/neoblog/v1/search/` URL.

![error](https://user-images.githubusercontent.com/17693529/93581175-28d9ac80-f977-11ea-8426-b86c67f7235d.png)

## Expected Behaviour

It shouldn't be consider an error. To test amp-autocomplete I need to disable the plugin or select _View with AMP disabled_.

![view-with-amp-disabled](https://user-images.githubusercontent.com/17693529/93581405-80781800-f977-11ea-8958-4934fc8cdbbb.png)

---------------

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Is your local development site running under HTTP and not HTTPS?

In looking at the [AMP playground](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9InNlbGYuaHRtbCIgLz4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1mb3JtIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1mb3JtLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWF1dG9jb21wbGV0ZSIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtYXV0b2NvbXBsZXRlLTAuMS5qcyI+PC9zY3JpcHQ+CjwvaGVhZD4KPGJvZHk+Cjxmb3JtIGNsYXNzPSJzYW1wbGUtZm9ybSIKICBtZXRob2Q9InBvc3QiCiAgYWN0aW9uLXhocj0iaHR0cHM6Ly9hbXAuZGV2L2RvY3VtZW50YXRpb24vZXhhbXBsZXMvYXBpL2VjaG8iCiAgdGFyZ2V0PSJfdG9wIj4KICA8YW1wLWF1dG9jb21wbGV0ZSBmaWx0ZXI9InN1YnN0cmluZyIKICAgIHNyYz0iaHR0cDovL2xvY2FsaG9zdC9zdGF0aWMvc2FtcGxlcy9qc29uL2FtcC1hdXRvY29tcGxldGUtY2l0aWVzLmpzb24iPgogICAgPGlucHV0PgogIDwvYW1wLWF1dG9jb21wbGV0ZT4KPC9mb3JtPgo8L2JvZHk+CjwvaHRtbD4K), you can see that `http:` is not valid AMP:

![image](https://user-images.githubusercontent.com/134745/93630979-b8935100-f99f-11ea-898d-ce1e4ef27f70.png)

So on one hand, this would ideally be something that AMP core would update in the validator, to exempt `localhost` from having HTTPS enforced, similar to how Service Workers normally require HTTPS except for when on `localhost`, which is [considered a secure origin](https://www.chromium.org/blink/serviceworker/service-worker-faq#sites-canvas-main-content:~:text=localhost%20is%20also%20considered%20a%20secure%20origin). 

Otherwise, to exempt `http://localhost` from being flagged as a `src` validation error, an alternative would be to force AMP Dev Mode for such elements when `wp_get_environment_type() === 'local'` (as of WP 5.5). In fact, `amp_is_dev_mode()` could be by default return `true` when on the `local` environment and the `HTTP_HOST` is `localhost`. That makes sense to me.

**Comment by westonruter** [comment]
The quick fix is to enable HTTPS for your local environment.

**Comment by artneo-io** [comment]
I develop locally using Browsersync – the HTTP version page refreshes faster than HTTPS.

**Comment by westonruter** [comment]
I suggest you conditionally add the `data-ampdevmode` attribute to this `<amp-autocomplete>` element when `wp_get_environment_type() === 'local'`.

And then also add this plugin code:

```php
if ( wp_get_environment_type() === 'local' ) {
    add_filter( 'amp_dev_mode_enabled', '__return_true' );
}
```

**Comment by artneo-io** [comment]
Does adding `add_filter( 'amp_dev_mode_enabled', '__return_true' );` already changes the plugin behavior somehow?

**Comment by westonruter** [comment]
It forces the `html` element to have the `data-ampdevmode` attribute. Normally this is only ever added if you are logged-in and the admin bar is displayed, since it's important that AMP Dev Mode documents not be accessible to crawlers, since they are explicitly not valid AMP. However, if your site is on a `local` environment then it's clearly not going to be accessible to crawlers, so it doesn't matter.

**Comment by westonruter** [comment]
See default value for this filter here:

https://github.com/ampproject/amp-wp/blob/27718b00bfbaacd4013f1cdbb590dc3f4371b4bf/includes/amp-helper-functions.php#L1442-L1462

**Comment by westonruter** [comment]
I think amending the logic as follows would also make sense:

```diff
--- a/includes/amp-helper-functions.php
+++ b/includes/amp-helper-functions.php
@@ -1458,6 +1458,16 @@ function amp_is_dev_mode() {
 			( is_admin_bar_showing() && is_user_logged_in() )
 			||
 			is_customize_preview()
+			||
+			(
+				! is_ssl()
+				&&
+				(
+					( function_exists( 'wp_get_environment_type' ) && 'local' === wp_get_environment_type() )
+					||
+					'localhost' === wp_parse_url( home_url(), PHP_URL_HOST )
+				)
+			)
 		)
 	);
 }
```

This can then be combined with extending the `AMP_Dev_Mode_Sanitizer` to automatically add `data-ampdevmode` attributes to all elements with `src` and `action` attributes that that have the `http:` protocol which point to the site. Nevertheless, it may be that some AMP components will just refuse to work if not on HTTPS as well, so your mileage may vary with this approach. If that is the case, a feature request to exempt `localhost` from the HTTPS requirement should be submitted to AMP core.

**Comment by westonruter** [comment]
This should also address an issue I've seen with wp-env, where when the PWA plugin is enabled, there are validation error due to the use of `http:` protocol for the Web App Manifest link. This is due to wp-env serving from `http://localhost:8888`

**Comment by pooja-muchandikar** [comment]
QA Passed ✅

Before with v2.4.1:

<img width="1278" alt="Screenshot 2023-07-13 at 1 58 01 PM" src="https://github.com/ampproject/amp-wp/assets/41000648/f0454def-ce32-4aaa-8388-a38716a43ec0">

---

After the fix, this error is not visible. Verified with other plugins such as Web stories,  PWA and WooCommerce nothing suspicious error observed it is working fine.
