### ISSUE TITLE
AMP Validated URL screen: Allow marking multiple validation errors as reviewed or unreviewed at once

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5427]
## Feature description

Currently, this interface requires each checkbox in the "Reviewed" column to be clicked separately. 

<img width="1247" alt="AMP URL validation table" src="https://user-images.githubusercontent.com/9020968/94188900-9e5de500-fe6f-11ea-894c-639da25af297.png">

There should be a way to mark _all_ or multiple issues as reviewed or unreviewed with a single click, maybe alongside these "Remove" and "Keep" buttons:

<img width="464" alt="Keep and Remove buttons" src="https://user-images.githubusercontent.com/9020968/94189106-eda41580-fe6f-11ea-84f1-ab4b90e2b89d.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There are clearly defined bulk actions to mark URLs as reviewed or unreviewed, following the pattern already set with the "Remove" and "Keep" buttons.
* Reviewed/unreviewed toggle can be applied to one or more rows.
* "New" state (the yellower background for a given row) toggles along with the reviewed/unreviewed state. Unreviewed rows should have the new style.

## Implementation brief

* Add new buttons to the bulk action row.
* Use event listeners to toggle the Reviewed checkbox
* Toggle the "new" class on the row accordingly.

## QA testing instructions

* Visit the URL validation screen for a URL with validation errors. Testing will work best if the URL has many errors.
* Test the "Mark as reviewed" and "Mark as unreviewed" buttons on one row, multiple rows, and all rows.
* Verify unreviewed rows always have the new style applied. 
* Verify results persist after saving.

## Demo

* 

## Changelog entry

* On the URL validation screen, added bulk actions to set multiple rows as reviewed or unreviewed.

**Comment by westonruter** [comment]
This is a quick win that can land in 2.0.5 if we get to it.

**Comment by westonruter** [comment]
I just noticed that GitHub's issue/PR tables make use of a similar paradigm as our validation error list on the Validated URL screen:

State | GitHub | AMP Plugin
------|--------|-----------
None checked | ![image](https://user-images.githubusercontent.com/134745/94299932-28b05280-ff1d-11ea-844f-19e37b561574.png) | ![image](https://user-images.githubusercontent.com/134745/94300478-ee938080-ff1d-11ea-86a3-1e51ce551341.png)
Some checked | ![image](https://user-images.githubusercontent.com/134745/94300136-67460d00-ff1d-11ea-9519-9b338075c8fd.png) | ![image](https://user-images.githubusercontent.com/134745/94300453-e0ddfb00-ff1d-11ea-8b61-83b567ab0f98.png)

Notice that when selecting the checkboxes for the PRs, the bar above the table changes its semantics. Instead of serving as a way to filter the list, the dropdowns become a way to mutate the list. Of note here is the "Mark As" dropdown that appears. When we redesign this screen and/or integrate into the edit post screen, we could combine the various bulk actions into a singular "Mark As" dropdown (which would save horizontal space).

Also, GitHub PRs which have changes not yet reviewed show up with a blue border on the left. We use an orange border.

Granted I am not always in love with this particular GitHub UI, but I think it would be a somewhat fair assumption to presume that developers using this screen in the AMP plugin would already have some experience with the GitHub screen as well, if they indicated they are indeed developers.

cc @jwold @amedina

**Comment by pierlon** [comment]
Alternatively, we could use the "Bulk Actions" select drop-down, since that's a common UI used throughout WordPress, eg. the Plugins page:

![image](https://user-images.githubusercontent.com/16200219/94301801-bb231700-ff5a-11ea-8933-ab78f7a99291.png)

I would imagine it somewhat looking like this in the Validated URL screen:

![image](https://user-images.githubusercontent.com/16200219/94302094-31c01480-ff5b-11ea-9077-175fbae36ba3.png)

**Comment by westonruter** [comment]
I think the reason we didn't include the dropdown like that is that the common expectation in the list tables is that clicking Apply would cause a form submission, and then for the page to reload and the dropdown to be reset to having "Bulk actions" as the selected option. If we apply the change instantly as soon as the user clicks Apply, then it could be confusing to see the selected option reset to "Bulk actions" immediately.

**Comment by pierlon** [comment]
One exception to that would be the bulk editing of posts/pages - the page is not reloaded and the selected option is not reset upon clicking the "Apply" button:

![](https://user-images.githubusercontent.com/16200219/94310522-4e634900-ff69-11ea-8dd9-884f7c19becb.gif)

Putting those buttons into a select input would reduce the space occupied by the buttons and we wouldn't have to think about redesigning the layout if we were to add more buttons. Thoughts?

**Comment by amedina** [comment]
One aspect we must consider is the purpose of the underlying functionality. One advantage of not having bulk actions in our case is that it forces users to actually engage with the issues. Similar to what the "Accept" button is not available until you scroll down the end of a document; and perhaps also similar to the needs of the Github interface.

**Comment by amedina** [comment]
Granted that it does not mean users will do or not do, but the UI is conducive to the right behavior.

**Comment by westonruter** [comment]
@pierlon I forgot about that Edit bulk action. Nevertheless, that seems somewhat even more tedious to make a bulk change in the context of the Validated URL screen. In that approach, to change multiple issues to Reviewed, you'd need 4 clicks:

1. Select the validation errors
2. Click the bulk action edit option
3. Click apply
4. Make the desired change.
5. Hit save?

Do you have a difference in how it would appear in our context?

Whereas right now we have:

1. Select the validation errors
2. Click the desired button.

This will be yet improved by https://github.com/ampproject/amp-wp/issues/5431.

The other key difference here is that the bulk actions on the Validated URL screen is that the change applied is not persisted until the user clicks the Update button. We want the user to truly understand the impact of the changes they are making to @amedina's point. So we also have the Preview button to see the impacts.

**Comment by jwold** [comment]
QA passed. Tested and confirmed that it worked as expected.
