### ISSUE TITLE
Content mismatch between AMP and canonical pages

### ISSUE THREAD

**Issue by saurabhdixit123456** [Automattic/amp-wp#544]
Please help me, my webmaster show Content mismatch between AMP and canonical pages. how we solve it

**Comment by fizanos** [comment]
I'm have same issues. Please help

**Comment by mjangda** [comment]
I'm not really sure I understand the issue. Can you please provide more details?

**Comment by niksmac** [comment]
@mjangda [here](http://stackoverflow.com/q/40775685/827525) is more details

**Comment by ahmedkaludi** [comment]
@mjangda I have gone through many webmaster tools reports of the users, I'm still not able to understand what exactly is it that triggers this. The content is same, Canonical is right, I'm unable to find the missing piece. 

Any help from the community would be appreciated.

**Comment by amedina** [comment]
The approach followed by the plugin is transcoding based and is a lossy process; in some cases, if it is not possible to transcode certain components, the sanitizers can remove them. 

Still, it is not clear what content mismatches are referred to here. Closing this issue for now since it is old; please reopen and provide more details if still experiencing an issue.
