### ISSUE TITLE
Customizer: Header Logo

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#551]
Add the ability to replace the text header with an image-based logo.

**Comment by westonruter** [comment]
See note on https://github.com/Automattic/amp-wp/issues/220#issuecomment-361473254

Modifying the post templates in the theme now will run the risk of conflicting with developers who have customized the templates in their theme. If we introduce a way to manipulate the header in some way, but the developer has already added Customizer controls for doing this, then the user could end up seeing two controls for the header, one that works and another that doesn't.

Instead of further building out the built-in post templates I think we should rather go in the direction of facilitating themes to be used wholesale in AMP mode, as is being worked on in 0.7. This will allow a site to use the exact same templates and styles between AMP and non-AMP mode.

**Comment by davisshaver** [comment]
@westonruter That direction sounds promising and it seems I need to read up on the changes going into 0.7. Perhaps this can be closed? cc @mjangda
