### ISSUE TITLE
iframe producing invalid height/width when absolute positioned with top and left of zero

### ISSUE THREAD

**Issue by jenkoian** [Automattic/amp-wp#5514]
Failing test and potential fix added here: https://github.com/ampproject/amp-wp/pull/5513

**Comment by westonruter** [comment]
I can reproduce this issue. If I add a Custom HTML block with the contents:

```html
<div style="position:relative; width:400px; height:400px;">
<iframe
	style="width: 100%; height: 100%; position: absolute; left: 0px; top: 0px;"
	src="https://example.com/video/132886713"
	width="100%"
	height="100%"
>
</iframe>
</div>
```

Then the rendered AMP markup is:

```html
<div data-amp-original-style="position:relative; width:400px; height:400px;" class="amp-wp-260d8b3">
	<amp-iframe src="https://example.com/video/132886713" width="640" height="" layout="fill" sandbox="allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-scripts allow-top-navigation-by-user-activation" class="i-amphtml-layout-fill i-amphtml-layout-size-defined" i-amphtml-layout="fill">
		<span placeholder="" class="amp-wp-iframe-placeholder"></span>
		<noscript>
			<iframe src="https://example.com/video/132886713" width="100%" height="100%" data-amp-original-style="width: 100%; height: 100%; position: absolute; left: 0px; top: 0px;" class="amp-wp-a6afb99">
			</iframe>
		</noscript>
	</amp-iframe>
</div>
```

Notice the `height=""`.

Strange strange that it is including a `width="640"` still.

**Comment by jenkoian** [comment]
@westonruter yeah I thought same

**Comment by jenkoian** [comment]
Thanks for reproducing btw @westonruter 👍

**Comment by pierlon** [comment]
So the bug is two-fold:

- The height is incorrectly set to `''` when the iframe sanitizer is normailizing attributes
- No validation issue is raised for the invalid height

I would be expecting `AMP_Base_Sanitizer::set_layout()` to first remove the height but it seems the condition that should do that is overshadowed by a similar condition:

https://github.com/ampproject/amp-wp/blob/3d0d68a75d16226b8e809a466bc8741fec6e3e10/includes/sanitizers/class-amp-base-sanitizer.php#L311-L339

In this case the first if condition would match and so will set the layout to `fill`, but wouldn't `unset` the width and height attributes. That is instead left up to ```AMP_Base_Sanitizer::sanitize_dimension()``` which will eventually set the height to `''`.

**Comment by westonruter** [comment]
So we should be unsetting the `width` and `height` whenever we are setting the `layout` to `fill` since it serves no purpose. That seems like it will correctly address the symptom of the problem. But you're saying another PR should come later to address the more fundamental issue with validation?

**Comment by pierlon** [comment]
Yes we should follow up with a PR to address the validation issue here.

**Comment by johnwatkins0** [comment]
QA passed. 

Pasted Weston's snippet from above into a custom HTML block. The block worked as expected with no validation errors.
