### ISSUE TITLE
Redirect mobile visitors to AMP

### ISSUE THREAD

**Issue by norbique** [Automattic/amp-wp#5525]
I have a problem, all pages are redirected to AMP even though the slider is turned off. Can I manually turn it off?

Thank you!

**Comment by westonruter** [comment]
What slide are you referring to?

Please share a screenshot.

**Comment by norbique** [comment]
I noticed that I have the same problem on several sites
![ezakopane_screen](https://user-images.githubusercontent.com/73165373/96633879-03dfad00-131a-11eb-9790-db7a3c296166.jpg)

**Comment by westonruter** [comment]
@norbique Please share the URL to a site that has this problem. Are you perhaps referring to AMP-to-AMP linking, where an AMP page will automatically link to other AMP pages? To disable this behavior you can do so with a filter:

```php
add_filter( 'amp_to_amp_linking_enabled', '__return_false' );
```

Currently this is enabled by default in Transitional mode:

https://github.com/ampproject/amp-wp/blob/585f4a2168e3a2fdff521e6062df3414a9983ed9/includes/amp-helper-functions.php#L1455-L1458

It is also enabled by default when mobile redirection is enabled:

https://github.com/ampproject/amp-wp/blob/585f4a2168e3a2fdff521e6062df3414a9983ed9/src/MobileRedirection.php#L53-L55

**Comment by norbique** [comment]
All as prompted, my site ezakopane.pl

**Comment by westonruter** [comment]
But is the problem actually AMP-to-AMP linking?

On this page, for example: https://ezakopane.pl/turystyka/porady/jak-zachowac-sie-w-gorach-w-czasie-burzy?amp

I see links in the footer:

![image](https://user-images.githubusercontent.com/134745/96800718-d991fc00-13ba-11eb-8bc5-dbe55cf55130.png)

The first links to:

https://ezakopane.pl/turystyka/porady/gdy-spotkasz-niedzwiedzia-na-szlaku?amp

The second to:

https://ezakopane.pl/imprezy/kulturalne/xv-wykopki-w-dzianiszu?amp

Note how they are linking to AMP versions. There is no redirection happening. If you turn off AMP-to-AMP linking via the `amp_to_amp_linking_enabled` filter then those links will not have `?amp` added to them.

**Comment by norbique** [comment]
Here too, all pages are redirected to AMP even though the slider is turned off murzasichle.info
![murzasichle_screen](https://user-images.githubusercontent.com/73165373/96825219-e6513700-1430-11eb-849a-27debddb00d2.jpg)

**Comment by westonruter** [comment]
@norbique please define "redirected". I just tried going to https://murzasichle.info/info/kosciol and I am not taken to an AMP page.

**Comment by norbique** [comment]
when I go from google to chrome on my phone, I have the AMP version, not my responsive template

**Comment by westonruter** [comment]
That's not redirection. Google Search serves the AMP version to mobile users when available.

**Comment by hollisterca** [comment]
Not sure if this is the same but 
I described the issue here
https://wordpress.org/support/topic/redirect-301-on-categories-links-on-amp-post/#post-13619613
Basically when on a amp page
https://www.teawea.com/vegan-chinese-spring-rolls/?amp=1
on the very bottom the categories that this recipe belongs to are linked to 
https://www.teawea.com/category/recipes/types/appetizers/?amp
instead of
https://www.teawea.com/category/recipes/types/appetizers/?amp=1
which caused a redirect 301, any change the categories can also be linked to /?amp=1 ?
I am on Template Mode: Reader with Reader Theme: Amp Legacy

**Comment by westonruter** [comment]
> which caused a redirect 301, any change the categories can also be linked to /?amp=1 ?
> I am on Template Mode: Reader with Reader Theme: Amp Legacy

The 301 redirect here is not from https://www.teawea.com/category/recipes/types/appetizers/?amp to https://www.teawea.com/category/recipes/types/appetizers/?amp=1 but rather to https://www.teawea.com/category/recipes/types/appetizers/

In other words, the `amp` query parameter is removed because AMP is not available on the category template on your site, since the AMP Legacy template is being used in Reader mode.
