### ISSUE TITLE
Enable Paired Browsing when Developer Tools are Off

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#5545]
## Feature description

Currently the awesome AMP plugin capability of paired browsing is available only when the plugin is configured in Transitional mode *and* Developer tools are turned on.  This approach serves well the purpose of opening Paired Browsing in response to seeing a validation error, and with the goal of determining the impact of the problem on the functional and/or visual aspects of the AMP version of the site. 

There are scenarios that would benefit from pair browsing, while keeping developer tools off. E.g.:

- There is AMP compatibility (i.e. no errors) but still there are differences between the AMP and non-AMP versions. For example, the underlying component is using `is_amp_endpoint()` (or whatever is called now), but the behavior of the generated markup is not quite the same

- Since users are aware of AMP being used in paired mode, they would likely want to see the visual/functional differences (if any) at any given point in time. 

For adding this capability, we'd have to figure out where to best present it to users. Currently paired browsing is accessed  from the admin bar or from the validated URL screen. If DevTools are not enabled, then the the second option would not be available. An additional way could be having a Paired Browsing link that is added to the admin screen in the same way we now have a AMP Customizer button.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Meeting notes:

* WR > When user sees a discrepancy, caused by validation error, but have dev tools turned off, then what? If they see a difference, no validation error shown, what do we do?
* AM > We can detect there are validation errors, but dev tools off. We could add a notice that says, “there may be discrepancies between AMP and non-amp version, check with your admin for an analysis.” Then, if they are an admin, tell them they can turn on. 
* AM > Probably a simple notice would be a step forward in that direction. Allow the user to go to the admin or if they can, turn on dev tools themselves.
