### ISSUE TITLE
Reduce size of UI elements on Settings screen

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#5559]
## Feature description

On a laptop screen there are two areas in the AMP settings page that feel larger than necessary. With a few minor tweaks we could reduce the size on each. 

Suggestions:

1. For the AMP Settings configuration wizard we could change out the button for a link.

<img width="1048" alt="Screen Shot 2020-11-02 at 8 43 37 AM" src="https://user-images.githubusercontent.com/3411173/97894588-88053d80-1ce7-11eb-9ad0-fdc69f46a5c2.png">

2. Reduce the padding on the `Save` button bar from 30px top/bottom to 20px top/bottom

![Screen Capture on 2020-11-02 at 08-33-25](https://user-images.githubusercontent.com/3411173/97894747-ba169f80-1ce7-11eb-8e8a-486e1cd5a522.gif)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by milindmore22** [comment]
**QA Passed**

AMP settings screen panel for wizard now have links instead of buttons

| Before | After |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/1132541/142238947-6ea6968e-6a9f-4d09-905c-675f55d50f03.png) | ![image](https://user-images.githubusercontent.com/1132541/142239022-8304c6c7-812f-45b4-a816-58ee099b68f3.png) |

Save Button padding has been reduced 
| Before | After |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/1132541/142239811-b02a6439-4adc-47b4-a26f-525e1b0ae566.png) | ![image](https://user-images.githubusercontent.com/1132541/142239874-09394f6c-bbd4-4363-88ab-05bf7cfc6793.png) |
