### ISSUE TITLE
On URL validation screen, improve representation of empty strings

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5598]
There might be a better way to represent this empty-string error on the URL validation screen. 

Instead of:

<img width="285" alt="Screen Shot 2020-11-12 at 4 58 17 PM" src="https://user-images.githubusercontent.com/9020968/99006684-76ead680-2508-11eb-9dac-2fcf1154ba41.png">

Should we do something like this?

<img width="371" alt="Screen Shot 2020-11-12 at 5 01 13 PM" src="https://user-images.githubusercontent.com/9020968/99006833-be716280-2508-11eb-82e9-25bfa7eb51c0.png">

_Originally posted by @johnwatkins0 in https://github.com/ampproject/amp-wp/issues/5516#issuecomment-726394772_

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue and the fix added for the issue is working as expected. 

**Before:** 

![image](https://user-images.githubusercontent.com/44057535/216655997-2e24a977-d7c8-4bb8-b219-821add8c0f94.png)


**After fix:** 

![image](https://user-images.githubusercontent.com/44057535/216656310-5b689f92-26aa-4ffc-ac70-107ec9b3cfb6.png)
