### ISSUE TITLE
CSS Tree Shaking for Admin Bar Classes/IDs

### ISSUE THREAD

**Issue by rickalee** [Automattic/amp-wp#5619]
## Bug Description

Hover states for our custom admin bar menu are getting tree shaked from frontend. 

CSS getting removed by AMP which we need:
#wpadminbar #wp-admin-bar-distributor.hover>.ab-sub-wrapper 

Is there a way to opt out enqueued stylesheet by handle from being tree shaked or ensure that all #wpadminbar styles don't get skipped?

**Comment by westonruter** [comment]
Yes, you can use the same approach as documented in my post: [Integrating with AMP Dev Mode in WordPress](https://weston.ruter.net/2019/09/24/integrating-with-amp-dev-mode-in-wordpress/). Instead of filtering `script_loader_tag`, use the `style_loader_tag` filter like so:

```php
$style_handles = array( /* Handles for Dev Mode */ );
add_filter(
	'style_loader_tag',
	function ( $tag, $handle ) use ( $style_handles ) {
		if ( in_array( $handle, $style_handles, true ) ) {
			$tag = preg_replace(
				'/(?<=<link)(?=\s|>)/i',
				' data-ampdevmode',
				$tag
			);
		}
		return $tag;
	},
	10,
	2
);
```

See an example of this being done in Site Kit: https://github.com/google/site-kit-wp/blob/b57115f8a1e0b4701351521066da95f4ecb4573c/includes/Core/Assets/Assets.php#L267-L277
