### ISSUE TITLE
Asynchronously populate counts for unreviewed validation errors and validated URLs in admin menu and dashboard widget

### ISSUE THREAD

**Issue by maciejmackowiak** [Automattic/amp-wp#5772]
## Feature description

We have noticed a huge performance impact from the query used for populating unread AMP validated urls/validation errors count.
It sometimes adds 0.3-0.5s to wp-admin page load.
Could you please consider moving it to cron job?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by maciejmackowiak** [comment]
Here is an example how much time this query can take:
![obraz](https://user-images.githubusercontent.com/24996403/104135221-0be64080-538f-11eb-9ad5-6678b77c6e56.png)

**Comment by westonruter** [comment]
I don't think the cron job will work because it needs to be live. In other words, if you have just 1 validated URL left that has an unreviewed error, you'll see a (1) next to Validated URLs as well as some other number next to Error Index (x). When you save update the status of a validation error from Unreviewed to Reviewed, the result is that these two numbers should decrement right away. It should be the same behavior as the bubbles next to Comments when there are unmoderated comments, and Plugins when there are updates available. These update immediately upon moderation and update respectively.

What could be done is to introduce a REST API endpoint for fetching the counts count of validated URLs containing unreviewed errors, as well as the count of unreviewed errors in the error index. If this were available, then we could do a request for those fields to then populate the menu item accordingly. Upon the first page load, the fetched numbers could be stored in `localStorage` to populate immediately upon page load to then potentially be updated if there has been a change.

**Comment by westonruter** [comment]
Note the counts themselves are cached in transients per #3222, #3666, and #5343. However, when an update is made to a validated URL then the cache is invalidated.

@maciejmackowiak Are you seeing this slow query with every page load, or just after AMP validated data has been changed?

**Comment by westonruter** [comment]
The two places the counts occur are:

1. The admin menu: 
![image](https://user-images.githubusercontent.com/134745/104259103-95504e00-5435-11eb-9e0d-bf8501a0f97e.png)
2. The At a Glance widget on the dashboard: 
![image](https://user-images.githubusercontent.com/134745/104259142-ad27d200-5435-11eb-976b-3ac4adc88086.png)

**Comment by archon810** [comment]
We have Query Monitor enabled on production for only admins, and this amp query is there all the time throughout the day. It's definitely not every time I load wp admin, but I notice it enough times for it to become frustrating. We have a busy site with lots of posts getting published and updated daily.

**Comment by archon810** [comment]
Ajax all the things!

**Comment by westonruter** [comment]
We can also consider making the request only when we need. So if the user is not even on an AMP settings screen, we can skip making the requests until the user opens the AMP admin submenu.

**Comment by archon810** [comment]
@westonruter 🎉

**Comment by westonruter** [comment]
> @westonruter 🎉

Forwarding to @pierlon!

**Comment by pierlon** [comment]
**QA Passed**

- The "At a Glance" widget is no longer shown:

![image](https://user-images.githubusercontent.com/16200219/116323846-6379b200-a7ae-11eb-9a95-904a6e641f3a.png)

- Validation counts are only asynchronously retrieved when the AMP menu is hovered over:

https://user-images.githubusercontent.com/16200219/116324023-d420ce80-a7ae-11eb-95c9-0505360861a0.mp4

- Validation counts are asynchronously retrieved when the AMP menu is open:

https://user-images.githubusercontent.com/16200219/116324390-940e1b80-a7af-11eb-80d6-a41c8cb4ad18.mp4
