### ISSUE TITLE
Header image fails to be prerendered

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5824]
## Bug Description

I've found that header images (via `custom-header` theme support) fail to get pre-rendered when there is a custom logo or featured image also on the page. For example, in themes that render the header image with an `img` as opposed to a `background-image`, the presence of a featured image in the page will prevent the header image from getting SSR'ed, as any presence of `data-hero` will prevent any hero-image candidate detection (via `PreloadHeroImage::detectHeroImageCandidate`) from running. 

In all four examples below, the header image lacks any prerendering. Only the “Horizontal” featured image gets prerendering:

Twenty Twelve | Twenty Fourteen | Twenty Sixteen | Twenty Seventeen
---------------|------------------|-----------------|-------------------
![twentytwelve](https://user-images.githubusercontent.com/134745/106414137-c1da0300-6400-11eb-9e8e-b5a098196282.png) | ![twentyfourteen](https://user-images.githubusercontent.com/134745/106414139-c4d4f380-6400-11eb-8480-a6f0f3b4bcff.png) | ![twentysixteen](https://user-images.githubusercontent.com/134745/106414142-c56d8a00-6400-11eb-80d2-0de35ea2d362.png) | ![twentyseventeen](https://user-images.githubusercontent.com/134745/106414144-c56d8a00-6400-11eb-9ad3-12f737e2c849.png)

This would have a negative impact on LCP which should be entirely avoidable because both the header image and the featured image can both be prerendered as `data-hero` images.

## Expected Behaviour

The header image should be prerendered whenever possible.

## Steps to reproduce

1. Activate Twenty Twelve, Twenty Fourteen, Twenty Sixteen, or Twenty Seventeen.
2. Add a header image in the Customizer.
3. Navigate to a post that has a featured image assigned.
4. On the AMP page, see that the featured image has `data-hero` whereas the header image does not.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When no images on a page initially have `data-hero`, first two non-tiny images on a page should have get prerendered, including the custom logo, header image, featured image, cover blocks, and other detected image candidates.

## Implementation brief

One way to implement this is to extend `\AmpProject\AmpWP\Transformer\DetermineHeroImages::transform()` to also include detection for header images in the same way it is detecting the custom logo, featured image, and cover blocks. In Twenty Seventeen, this could be accomplished by injecting `data-hero` into the header markup like so:

```php
add_filter(
	'get_header_image_tag',
	function ( $html ) {
		return preg_replace( '/(?<=<img\s)/', 'data-hero ', $html );
	}
);
```

This works in Twenty Seventeen since that theme uses `the_custom_header_markup()`. Unfortunately, none of the other themes use this function to output the header. They instead construct the `img` manually so there is no opportunity for filtering. One way to address that would be for us to add theme-specific XPath selectors to match the header image (e.g. via the core theme sanitizer), but this is not ideal as it would not automatically work for other themes.

I think the problem boils down to `DetermineHeroImages` injecting the `data-hero` attribute into images. This is causing all other candidates, such as the header image, to be omitted during `PreloadHeroImage::findHeroImages()`. I think there needs to be a differentiation between a user-specified `data-hero` which should indeed override any others, but then for our `DetermineHeroImages` to add `data-hero-candidate` attributes _instead_ of plain `data-hero` attributes, so that the `PreloadHeroImage` can include all images that have `data-hero` and then _also_ include the first one or two images that have `data-hero-candidate` to also have server-side-rendering.

1. If there are two images that have (author-supplied)`data-hero` on the page already, then none of the `data-hero-candidate` images would be included.
2. If there was one image that had `data-hero`, then it would get prerendered in addition to the _first_ image that has `data-hero-candidate`.
3. If there were no images that have `data-hero`, then the first _two_ images that have `data-hero-candidate` would get prerendered.

Prerendering any image with `data-hero-candidate` would naturally include adding the `data-hero` attribute as well.

This will require changes to both the AMP plugin here and also the amp-toolbox-php project.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
cc @schlessera

**Comment by westonruter** [comment]
The issue also is present for a user who has a regular Image block in hero position: https://wordpress.org/support/topic/data-hero-for-amp-optimizer/#post-14016250

**Comment by delawski** [comment]
QA passed _(tentatively - see the comment below)_.

---

I've tested a few scenarios on Twenty Seventeen. I each case, I've ran the following code in the dev tools console so that any `img` that has the `data-hero` attribute gets a thick red border:

```js
document.querySelectorAll( 'amp-img[data-hero]' ).forEach( el => el.style.border = '10px solid red' );
```

In each test case, 2 images at most that are within a viewport were assigned the `data-hero` attribute.

**Questions:**

- If there is no custom header, no logo, and no post thumbnail (**4.b**), only 1 image (within the Cover block) has been assigned the `data-hero` attribute. Is it expected? The same applies if relatively small images are added at the very top of the post - only one of them gets the `data-hero` attribute (**5**).
- Whenever a logo is present (**2**, **3**), it feels that it's relatively small compared to other images. Should it still take precedence over the first Cover block image or regular image within a post content? 

### 1. With custom header, without logo

| a) With post thumbnail | b) Without post thumbnail |
| --- | --- |
| <img width="376" alt="Screenshot 2021-04-27 at 12 21 48" src="https://user-images.githubusercontent.com/478735/116226951-e0c40900-a753-11eb-9384-081fac4207d6.png"> | <img width="377" alt="Screenshot 2021-04-27 at 12 20 25" src="https://user-images.githubusercontent.com/478735/116226967-e4f02680-a753-11eb-809e-988e2736da5f.png"> |

### 2. With custom header, with logo

| a) With post thumbnail | b) Without post thumbnail |
| --- | --- |
| <img width="375" alt="Screenshot 2021-04-27 at 12 22 57" src="https://user-images.githubusercontent.com/478735/116227261-3c8e9200-a754-11eb-95aa-54ff3f184fd2.png"> | <img width="376" alt="Screenshot 2021-04-27 at 12 23 17" src="https://user-images.githubusercontent.com/478735/116227306-487a5400-a754-11eb-9365-af73815ff0a1.png"> |

### 3. Without custom header, with logo

| a) With post thumbnail | b) Without post thumbnail |
| --- | --- |
| <img width="378" alt="Screenshot 2021-04-27 at 12 24 07" src="https://user-images.githubusercontent.com/478735/116227498-837c8780-a754-11eb-9e4d-04a27042e7dc.png"> | <img width="377" alt="Screenshot 2021-04-27 at 12 23 48" src="https://user-images.githubusercontent.com/478735/116227516-88d9d200-a754-11eb-9288-4cbaffa14102.png"> |

### 4. Without custom header, without logo

| a) With post thumbnail | b) Without post thumbnail |
| --- | --- |
| <img width="376" alt="Screenshot 2021-04-27 at 12 24 27" src="https://user-images.githubusercontent.com/478735/116227619-a3ac4680-a754-11eb-8958-9b9dfd9be9dc.png"> | <img width="375" alt="Screenshot 2021-04-27 at 12 24 50" src="https://user-images.githubusercontent.com/478735/116227634-a870fa80-a754-11eb-8d5a-0e6fffb7a8b9.png"> |

### 5. Without custom header, without logo, without featured image

<img width="373" alt="Screenshot 2021-04-27 at 12 43 53" src="https://user-images.githubusercontent.com/478735/116229005-4b764400-a756-11eb-862d-c68639ce3900.png">
