### ISSUE TITLE
Introduce plugin row meta for Support and Rating

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#5893]
## Feature description

Let's introduce the "Support" and "Rate AMP plugin"  in the plugin rows [the way](https://github.com/google/site-kit-wp/blob/ce582d1910bdf0104792da6f3975a19586ed186d/includes/Core/Admin/Plugin_Row_Meta.php) the Site Kit by Google plugin does, The idea is to encourage users to reach support forums and rate the AMP plugin more promptly by giving them direct links.

![image](https://user-images.githubusercontent.com/1132541/108405595-40c79c00-7247-11eb-9a0f-8e47876c601d.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Worth taking a look [here](https://app.asana.com/0/1185360131189553/1199884318455591/f) also, to gauge users satisfaction and obtain feedback.

**Comment by westonruter** [comment]
This is part of #4664.

Maybe we should go ahead and and add the admin menu item as well which links directly to a support landing page on amp-wp.org or to the support forum directly.

**Comment by westonruter** [comment]
QA Passed.

* **Contact support** links to https://wordpress.org/support/plugin/amp/
* **Leave review** links to https://wordpress.org/support/plugin/amp/reviews/#new-post

I just noticed that the implementation in AMP and Site Kit differ from Jetpack in that Jetpack adds _action_ links (via `plugin_action_links`) whereas we are adding _meta_ links (via `plugin_row_meta`). 

![image](https://user-images.githubusercontent.com/134745/110391902-fd2daa00-801c-11eb-95ae-6c493ecb207a.png)

I'm not entirely sure which is better, but Jetpack's implementation seems makes the links more prominent, although semantically they seem better as meta since they aren't taking actions on the plugin itself.
