### ISSUE TITLE
AMP Breaks the Square Payment Method

### ISSUE THREAD

**Issue by ryanr14** [Automattic/amp-wp#5985]
## Bug Description

If you've got Square setup as a payment method and then setup AMP the credit card fields at checkout aren't usable.

## Steps to reproduce

1. Setup AMP
2. Setup Square as your payment method
3. Try to buy via Square at Checkout

## Screenshots

Error with AMP & Square activated
![https://d.pr/i/6tolD0](https://d.pr/i/6tolD0+)
Image link: https://d.pr/i/6tolD0

AMP Deactivated and Square working as it should.
![https://d.pr/i/oKzWUv](https://d.pr/i/oKzWUv+)
Image link: https://d.pr/i/oKzWUv

## Additional context

 - WordPress version: 5.7
 - Plugin version: 2.0.11
 - Gutenberg plugin version (if applicable): 10.1.1
 - AMP plugin template mode: Standard
 - PHP version: 8.0.0
 - OS: macOS
 - Browser: [e.g. chrome, safari] Safari
 - Device: [e.g. iPhone6] MacBook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This is working as intended, since custom scripts are not allowed on AMP pages (unless they can be loaded into `amp-script`). The AMP plugin unwraps `noscript` elements so that those fallbacks become the baseline AMP experience. This is why you see that message on the AMP version. 

I don't have experience with the Square payment API but it's possible that there is an AMP-compatible solution. It may be that using an iframe is the best bet for now: https://amp.dev/documentation/examples/e-commerce/payments_in_amp/

Otherwise, disabling AMP for the checkout page is also a common solution.

**Comment by milindmore22** [comment]
As suggested by Weston, I will recommend disabling AMP on Checkout pages. 
![image](https://user-images.githubusercontent.com/1132541/111659887-93d74380-8833-11eb-9f24-8c84adf99ed8.png)

Additionally,  Update cart behavior settings to redirect on adding a product in cart and disabling Ajax add to cart check on from Archive.
![image](https://i.imgur.com/wvms46N.png)

**Comment by ryanr14** [comment]
Thanks for clarifying this, and the quick reply. :)
