### ISSUE TITLE
When switching block editor mode, all errors listed in AMP sidebar incorrectly appear to be removed

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#5994]
## Bug Description

Whenever a block editor mode is switched (e.g. from "Visual editor" to "Code editor"), each AMP validation error listed in the sidebar says that the block it is associated with has been removed from the document.

This was discovered by @westonruter in https://github.com/ampproject/amp-wp/pull/5929#pullrequestreview-615012698. 

## Expected Behaviour

Switching block editor mode should not cause blocks listed in the AMP sidebar to appear as being removed from the document.

## Steps to reproduce

1. Open a post having an AMP error coming from the content in the block editor.
2. Switch the editor mode to "Code editor" using the Options menu (three dots in the top right corner).
3. See that the error associated with the block in the post content is now marked as removed.

## Screenshots

Here's the original video from https://github.com/ampproject/amp-wp/pull/5929#pullrequestreview-615012698:

https://user-images.githubusercontent.com/134745/111583606-f53adc00-8779-11eb-936c-131876d92df4.mov

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

The root cause of the issue is the fact that whenever the block editor mode is changed, [blocks are being reset](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/store/actions.js#L51-L64). This, in turn, causes resets all `clientId` values that we rely on in the [`useValidationErrorStateUpdates`](https://github.com/ampproject/amp-wp/blob/develop/assets/src/block-validation/use-validation-error-state-updates.js) hook.

Possible solutions:
* Errors stored in the app state should be reconciled with the updated list of blocks after switching editor mode, or
* Revalidation should be triggered after blocks have been reset.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
> Possible solutions:
>
> - Errors stored in the app state should be reconciled with the updated list of blocks after switching editor mode

That doesn't seem like a feasible solution, as blocks could be removed or have their content updated while in the Code Editor, which could lead to some blocks not being able to be re-associated with its validation error.

I think your second solution is the way to go: triggering re-validation after blocks being reset.

**Comment by jwold** [comment]
* WR > Current solution asks users to revalidate because content may have changed. That seems sufficient to me. 
* PD > I think we should trigger validation anytime the editor mode changes. Is it possible that post wouldn't be dirty when switching to another mode of the editor it would get dirty, but not really because of change of content, but for other reasons? 
* WR > I don't think so. If you open the editor, haven't made change, and switch to code tab; you still haven't made any changes, so only reason to revalidate at that point wouldn't be because of changes to content, but because client IDs are no longer valid. 
* WR > Number of times user switches to code editor view is low, not big priority. Also, for them to also have AMP validation sidebar open at same time, to see my results are stale; If they do make change they want to hit revalidate anyway, proactively revalidating content after merely switching to code editor seems like it may be excessive. 
* PD > Makes sense.

**Comment by jwold** [comment]
* WR > May not be necessary to do. 
* PD > We have some solutions for this already; the one WR added. It's something that signals or flags that post may have changed after we switched to the other mode of editor; there is a solution already, I think it's pretty good. The only thing we could do would be probably too sophisticated for this: reconcile those blocks only if there is no change done between switching editor mode and - going too deep. 
* PD > This could probably get closed.
* WR > One thing related, when testing on ampwp.org; when you have Yoast active, their UI makes use of meta boxes even in block editor somehow. I noticed that when you have Yoast active, it always says content may have changed; that issue where we don't know contents of metabox changed, I thought Yoast would have implemented storage of data in UI as part of redux store. This apparently is not the case. Yoast is popular, so if it's not working for when Yoast is active, that's a problem. 
* WR > Can you check to see what Yoast is doing @delawski and see maybe if we can reduce the need to always show the content may have changed message unless we have to.
* AS > As a quick note about how Yoast implements this, don't know if latest state; but probably it is, when Yoast initially added sidebar, they still needed to support Gutenberg + Classic Editor; they built sidebar in such a way that it can be extracted, and built a meta box that provides simulation of sidebar container; so they can paste code for sidebar into meta box for classic editor; but surrounding infrastructure is missing. They probably make UI fit into Gutenberg as best they can so they can reuse in Gutenberg + Classic, but they can't rely too deeply on state of Gutenberg, because not present in Classic. 
* WR > In Gutenberg is there non meta box way to add panels to bottom, or only in ride sidebar? 
* AS > Bottom is after the fact hack added for adding meta boxes, in beginning not planning support for meta boxes, was meant to be everything in sidebar; meta boxes compromise, nothing meant to be at bottom. 
* WR > Problem is Yoast UI requires wide area. Snippet preview and other items that don't fit in sidebar width. Seems like something missing in Gberg in general, standard UI space with real estate. 
* AS > Built as page builder, not management system. M in CMS is missing with Gutenberg because focuses solely on visual aspect of page, the more you need non visual representation of data in your page, the more you'll have problems with Gutenberg. 
* WR > Add Yoast block for containing special fields.

**Comment by jwold** [comment]
@delawski can we open a new issue for Yoast to investigate?

**Comment by jwold** [comment]
* WR > If only meta box is Yoast, and Yoast puts data in store to track changes - if only using Metabox as place for react components, and still putting data in store, so we can listen to changes, then we may want to make it a special case where we say, if Yoast, still consider that there are meta boxes.
