### ISSUE TITLE
Ensure errors displayed in the block editor sidebar and on the Validated URL, Validated URLs, and Error Index screens look the same 

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#5995]
## Feature description

The appearance of the error messages in the block editor sidebar has been updated in #5929.

<img width="280" alt="Screenshot 2021-03-17 at 16 07 32" src="https://user-images.githubusercontent.com/478735/111490465-57282100-873b-11eb-8036-8931cf485456.png">

<img width="281" alt="Screenshot 2021-03-17 at 16 07 46" src="https://user-images.githubusercontent.com/478735/111490571-6dce7800-873b-11eb-8521-08091fd9f55f.png">

However, the same errors on the Validated URL, Validated URLs, and Error Index screens have not been updated:

![image](https://user-images.githubusercontent.com/134745/111355369-8c057c80-8644-11eb-841f-d52ae12674e5.png)

![image](https://user-images.githubusercontent.com/134745/111355409-96c01180-8644-11eb-9934-8cdfae83f9a1.png)

![image](https://user-images.githubusercontent.com/134745/111355455-9f184c80-8644-11eb-8657-dd19b0dfc322.png)

This causes an inconsistency that should be removed.

This has been originally communicated by @westonruter in https://github.com/ampproject/amp-wp/pull/5929#issuecomment-800475083.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
* WR > Now the design language has changed the reviewed versus unreviewed. Before something not reviewed had orange background in way that was similar to unmoderated comments. But now in block editor that's been replaced with having bold text and darker background. Then the orange/red border now means that invalid markup kept, so that same design should be consistent with validation screens.
* JW > Want support PD? 
* PD > Haven't thought about details yet, might be cases where some design support might be needed. If you could look at the screenshots and maybe if you find something that is not obvious about the design approach, then please comment or raise guidance. @jwold

**Comment by jwold** [comment]
Played with some concepts for this on [Figma](https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/?node-id=2001%3A4812).

--------

![Group 62](https://user-images.githubusercontent.com/3411173/113061618-2eeee800-9167-11eb-88bb-f524ccef1e1e.png)

--------

![Group 60](https://user-images.githubusercontent.com/3411173/113061621-2f877e80-9167-11eb-8dc7-5983c42ad494.png)

--------

![Group 61](https://user-images.githubusercontent.com/3411173/113061614-2d252480-9167-11eb-8c17-2f3b70b3763c.png)

I think I've figured out some ideas that work, but feedback is welcome.

**Comment by westonruter** [comment]
We'll need to retain some dark horizontal line to differentiate between the rows. 

In the block editor:

All unreviewed | All reviewed
---------------|-------------
![image](https://user-images.githubusercontent.com/134745/113066733-e4259e00-916f-11eb-81dc-880b69898bea.png) | ![image](https://user-images.githubusercontent.com/134745/113066893-2f3fb100-9170-11eb-93eb-1dc3d28fe11e.png)

Currently on the validated URL screen:

All unreviewed | All reviewed
---------------|-------------
![image](https://user-images.githubusercontent.com/134745/113066832-0fa88880-9170-11eb-9478-2d776b455ca5.png) | ![image](https://user-images.githubusercontent.com/134745/113066805-04555d00-9170-11eb-9c08-70f46230cccb.png)

Note in the case of unreviewed issues, there is no zebra striping currently, so if we eliminate the use of zebra striping for reviewed errors then that should be fine. We just need to make sure there is a clear border between each error.

There is also no zebra striping for the Plugin Suppression table:

> ![image](https://user-images.githubusercontent.com/134745/113067023-6ca43e80-9170-11eb-97f6-9a851259e057.png)

So yeah, we can eliminate the zebra striping.

----

Note that adding a icon to the status dropdown will require a custom component since `select` does not support this:

> ![image](https://user-images.githubusercontent.com/134745/113067198-c60c6d80-9170-11eb-8127-8649100007f8.png)

**Comment by delawski** [comment]
Good points, @westonruter.

I think that for the sake of consistency and readability, it'd be good to have dark horizontal separators.

Also, I'd prefer not to add a custom select dropdown just because of the icon. However, since this select field is already handled by JS, we could pretty easily have an icon next to the dropdown. It would represent the current markup status and change whenever the select value changes.

**Comment by jwold** [comment]
* WR > Currently there is zebra striping, which reduces need for horizontal lines. But if we eliminate zebra striping (which isn't present for unreviewed, but when reviewed there is zebra striping.)
* WR > If no zebra striping, need horizontal lines to separate rows. 
* Guidance: We can probably get rid of zebra striping so long as we have horizontal lines.

* WR > Regarding icons, can't be inside dropdown, would have to be beside the dropdown.

**Comment by jwold** [comment]
Good suggestions. Here's an updated version @delawski:

![Group 92](https://user-images.githubusercontent.com/3411173/113522728-e4e77700-9557-11eb-9695-d0cabf6174b0.png)

----

![Group 93](https://user-images.githubusercontent.com/3411173/113522732-e6b13a80-9557-11eb-8656-242973732204.png)

----

![Group 91](https://user-images.githubusercontent.com/3411173/113522735-e749d100-9557-11eb-8a34-6eadb943f301.png)

**Comment by jwold** [comment]
**QA Passed.**

Screenshot of validation screen errors:
<img width="867" alt="Screen Shot 2021-04-28 at 6 55 18 AM" src="https://user-images.githubusercontent.com/3411173/116415934-bd9a6780-a7ee-11eb-9b59-5bede410dead.png">

Note that the unreviewed are bold and white bg, and the reviewed are normal font weight gray bg. This is a change from the designs I shared above, as it's more in line with our original concept when discussing this plan. 

And here is the comparison view on the block editor:

<img width="241" alt="Screen Shot 2021-04-28 at 6 59 15 AM" src="https://user-images.githubusercontent.com/3411173/116416567-4ca77f80-a7ef-11eb-9730-ffc6ec851e8c.png">
