### ISSUE TITLE
Explore incorporation of AMP's Content Security Policy

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6029]
## Feature description

As per [Secure from third party attacks](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/secure-pages/) on AMP.dev, highlighted by @jono-alderson, there is a Content Security Policy (CSP) which can be added to AMP pages to further secure them:

```html
<meta
  http-equiv="Content-Security-Policy"
  content="
    default-src * data: blob:; 
    script-src blob: https://cdn.ampproject.org/v0.js https://cdn.ampproject.org/v0/ https://cdn.ampproject.org/viewer/ https://cdn.ampproject.org/rtv/;
    object-src 'none';
    style-src 'unsafe-inline' https://cdn.ampproject.org/rtv/ https://cdn.materialdesignicons.com https://cloud.typography.com https://fast.fonts.net https://fonts.googleapis.com https://maxcdn.bootstrapcdn.com https://p.typekit.net https://use.fontawesome.com https://use.typekit.net;
    report-uri https://csp-collector.appspot.com/csp/amp
  "
>
```

(Naturally the specific `report-uri` here should _not_ be included, but see also the [Reporting API](https://wordpress.org/plugins/reporting-api/) plugin.)

We should look into whether this can be added automatically be the plugin on AMP pages. Note that it would need to be _excluded_ when in dev mode since custom scripts are then expected (e.g. for the admin bar).

There's also an issue with this CSP blocking installation of service workers, as noted in https://github.com/ampproject/amp.dev/pull/5612. The URL to be added to the `script-srcs` could be automatically detected via a sanitizer by inspecting the `amp-install-serviceworker` on the page and grabbing its `src`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jonoalderson** [comment]
I'd recommend a few more tweaks to adapt this for life on a WP AMP page, which might have some more moving (or stale!) parts than the suggested string anticipates:
- Make it more future-proof / version-agnostic, by removing 'versioning' of individual AMP assets (e.g., `v0.j`), and consolidating the various `https://cdn.ampproject.org` path definitions into a single rule
- Move the consolidated `https://cdn.ampproject.org` rule into the `default-src` declaration.
- Add `'self'` as a `default-src`, to allow all local resources which aren't otherwise constrained by the rest of the rules (e.g., a service worker)
- Clone the `default-src` values into the `script-src` declaration, and add a `connect-src` declaration with the same values; both for ease of filtering
- Add `img-src * data:`, `media-src * data:` and `frame-src * data:` declarations, to allow for the origin page to include externally hosted images, iframes (e.g., for embedding arbitrary media - e.g., a YouTube video - in content) and audio/video
- Remove `report-uri` (this [isn't supported](https://developers.google.com/web/fundamentals/security/csp#the_meta_tag) when the directive is implemented via a meta tag, as opposed to a HTTP header)


That gives us: 
```
default-src 'self' https://cdn.ampproject.org data: blob:; 
script-src 'self' https://cdn.ampproject.org data: blob:; 
connect-src 'self' https://cdn.ampproject.org data: blob:; 
img-src * data:;
frame-src * data:;
media-src * data:;
object-src 'none';
style-src 'unsafe-inline' https://cdn.ampproject.org https://cdn.materialdesignicons.com https://cloud.typography.com https://fast.fonts.net https://fonts.googleapis.com https://maxcdn.bootstrapcdn.com https://p.typekit.net https://use.fontawesome.com https://use.typekit.net;
```

## Notes:

### *Filtering & integrations
Edge-cases and additional resource requirements should probably be handled in whichever tools handle those implementations (e.g., Site Kit), or, conditionally based on their presence. That does mean that we need each of the declaration types to be filterable. Eg...

#### Analytics
When `amp-analytics` is active, we also need to allow the relevant resource (Google Tag Manager, Google Analytics, other vendor-specific domain) - and/or any resources declared in a `config` (or `requests > pageview`) value in the `connect-src` declaration.

Alternatively, a string of known vendor hostnames (or resource URLs) could simply be added, regardless of integration status.

Note that only the initiating resource is required; e.g., adding `https://www.googletagmanager.com` to `connect-src` means we _don't_ need to add `https://www.google-analytics.com/` to `script-src` or `connect-src`.

e.g., when running Google Tag Manager (which in turn connects to Google Analytics):
```
default-src 'self' https://cdn.ampproject.org data: blob:; 
script-src 'self' https://cdn.ampproject.org data: blob:; 
connect-src 'self' https://cdn.ampproject.org https://www.googletagmanager.com data: blob:; 
img-src * data:;
frame-src * data:;
media-src * data:;
object-src 'none';
style-src 'unsafe-inline' https://cdn.ampproject.org https://cdn.materialdesignicons.com https://cloud.typography.com https://fast.fonts.net https://fonts.googleapis.com https://maxcdn.bootstrapcdn.com https://p.typekit.net https://use.fontawesome.com https://use.typekit.net;
```

#### Service workers / the WP PWA plugin
The outlined approach 'solves' the [PWA / Service Workers problem](https://github.com/ampproject/amp.dev/pull/5612) by permitting same-domain scripts. If we want to be tighter on this and only include explicitly allowed scripts, the aforementioned problem will also need to consider either:
- Filtering the directive to add a `script-src` declaration which includes PWA plugin subresources (e.g., various files which are loaded by/in `/wp-content/plugins/pwa/`), or;
- Altering the PWS plugin to load these resources in a different way.

**Comment by westonruter** [comment]
Note also that we intend to implement self-hosting of AMP scripts: https://github.com/ampproject/amp-wp/issues/5581.

This will improve performance by reducing the need to open a TCP connection to `cdn.ampproject.org`, while also quelling any privacy concerns. So this adds further need for the `'self'` to be included in `script-src`.

**Comment by westonruter** [comment]
Note the `meta[http-equiv]` tag is actually invalid AMP (see https://github.com/ampproject/amp.dev/pull/5612#issuecomment-811636355). The CSP actually has to be set via a `Content-Security-Policy` HTTP response header.

**Comment by westonruter** [comment]
I also realize that the CSP will no longer work as-is with the new `script[amp-error]`. See https://github.com/ampproject/amphtml/issues/22543#issuecomment-673603872 and https://github.com/ampproject/amp-toolbox/issues/1146.

CSP is indicated at https://github.com/ampproject/amphtml/issues/22543#issuecomment-673603872.
