### ISSUE TITLE
Improve page experience for fonts in core themes via preloading, preconnecting, and using `font-display:optional`

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6036]
## Bug Description

Improve page experience of core themes by preloading and preconnecting fonts, as suggested by Pixi let's preload core theme fonts which are loaded through URL also use font-display property suggested `font-display: optional`

As we discussed core themes are still widely used, and also used as Reader Mode themes, so let's add these small improvements.

Ref: https://github.com/ampproject/amp.dev/pull/5531/

Core themes and fonts Tested 

| Themes | Fonts | Source |
|--|--|--|
| twentyten  |  None | |
| twentyeleven  | None | |
| twentytwelve  |  Open Sans |  Google Fonts |
| twentythirteen  | Source Sans Pro, Bitter, genericons |  Google Fonts, Theme |
| twentyfourteen  | Lato, Genericons | Google Fonts, Theme |
| twentyfifteen  | Noto Serif, Noto Sans, Inconsolata | Google Fonts, Theme |
| twentysixteen  |  Merriweather, Montserrat, Inconsolata | Google Fonts |
| twentyseventeen  |  Libre Franklin | Google Fonts |
| twentynineteen  |  NonBreakingSpaceOverride | Theme |
| twentytwenty  |  Inter var, NonBreakingSpaceOverride | Theme, AMP Plugin |  |
| twentytwentyone  | None | |

## Expected Behaviour

[preconnect and dns-prefetch](https://web.dev/uses-rel-preconnect/)
`<link href=https://fonts.gstatic.com rel="dns-prefetch preconnect" crossorigin>`

[preload](https://web.dev/optimize-webfont-loading/#preload-your-webfont-resources)
`<link rel="preload" href="https://mywebsite.com/wp-content/themes/twentytwenty/assets/fonts/inter/Inter-italic-var.woff2" as="font" crossorigin>
`
## Steps to reproduce

1. Go to Themes
2. Activate any Core theme
3. Chack AMP page on [Page Experiance](https://amp.dev/page-experience/)
4. Check Preload Fonts

## Screenshots
| font-display:optional  | Preload  |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/1132541/113437540-6b8b3f80-9404-11eb-96a3-24b3ecdccd20.png) | ![image](https://user-images.githubusercontent.com/1132541/113437622-92497600-9404-11eb-922f-88e7ab72a890.png) |

## Additional context

 - WordPress version: 5.7
 - Plugin version: 2.0.11
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Standard Mode
 - PHP version: 7.4.10
 - OS: MacOS Catalina
 - Browser: Chrome
 - Device: Mac Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
For Genericons, we definitely will need to use `font-display:block` because this is an icon font and with `swap` we'd get unknown glyph boxes rendered momentarily and for `optional` we'd get permanent boxes on the first visit. The performance problems of using an icon font are surely the reason SVG was used in Twenty Seventeen. 

In the table, Genericons should be added to Twenty Fifteen and Twenty Sixteen. Note there is a [`NoIconFontIsUsed`](https://github.com/ampproject/amp-toolbox/blob/main/packages/linter/src/rules/NoIconFontIsUsed.ts) linter check which doesn't yet include Genericons, but it should. Once that happens, we'll get linting errors for these themes. Not sure how we'd be able to fix that, as we'd need to somehow convert Genericons into SVGs and rewrite any stylesheet references to use them.

For the `data:` URL fonts that we are externalizing, the logic is found here: https://github.com/ampproject/amp-wp/blob/2d0de18b0f33b3f56e718742407f2c8a195a0f60/includes/sanitizers/class-amp-style-sanitizer.php#L2433-L2570

This is where we'd need to add the `link[rel=preload]` elements and make the switch to `optional`:

https://github.com/ampproject/amp-wp/blob/2d0de18b0f33b3f56e718742407f2c8a195a0f60/includes/sanitizers/class-amp-style-sanitizer.php#L2566-L2570

For Google Fonts, the `font-display` tweak would need to be done here:

https://github.com/ampproject/amp-wp/blob/2d0de18b0f33b3f56e718742407f2c8a195a0f60/includes/sanitizers/class-amp-style-sanitizer.php#L1374-L1402

For Google Fonts, we'd be adding `display=optional` to the `$normalized_url` and update the `href`. Note that WordPress core as of https://core.trac.wordpress.org/ticket/47282 opted to actually go with `display=fallback` rather than `display=swap`. The [`FastGoogleFontsDisplay`](https://github.com/ampproject/amp-toolbox/blob/main/packages/linter/src/rules/FastGoogleFontsDisplay.ts) linter rule seems to be fine with `swap`, `fallback`, or `optional`. The Twenty Twenty theme is using “Inter var” and has a `font-display:swap`. It seems there is a newer [`fontDisplay`](https://github.com/ampproject/amp-toolbox/blob/main/packages/page-experience/lib/checks/fontDisplay.js) check which is explicitly checking for `optional`.

**Comment by westonruter** [comment]
Relevant post: [More than you ever wanted to know about font loading on the web](https://www.industrialempathy.com/posts/high-performance-web-font-loading/)

**Comment by westonruter** [comment]
As noted in https://github.com/ampproject/amp-wp/issues/5678#issuecomment-818979953, let's only worry about maximizing the performance of the three most recent core themes. These are the ones bundled with core now, and they are the three that we'll always show as Reader themes (even if not installed).

**Comment by westonruter** [comment]
> [preconnect and dns-prefetch](https://web.dev/uses-rel-preconnect/)
> `<link href=https://fonts.gstatic.com rel="dns-prefetch preconnect" crossorigin>`

I've filed an issue to address this separately: https://github.com/ampproject/amp-wp/issues/6156.

**Comment by westonruter** [comment]
For Google Fonts needing to use `font-display:optional`, I've also filed this upstream suggestion for an Optimizer transformer: https://github.com/ampproject/amp-toolbox/issues/1229. If we have the right fallbacks in place for core themes, this transformer could be enabled by default.

**Comment by westonruter** [comment]
I've also identified that core is adding `preconnect` resource hints for Google Fonts but is failing to also add `dns-prefetch`. Opened ticket with patch to fix that upstream: https://core.trac.wordpress.org/ticket/53122

**Comment by westonruter** [comment]
One of the areas of optimization is to force the `NonBreakingSpaceOverride` font to have `font-display:optional`. But it seems this is already the case in the plugin. See https://github.com/WordPress/twentynineteen/pull/585 and https://github.com/WordPress/gutenberg/issues/11405.

**Comment by fellyph** [comment]
**QA Passed:**


| Themes | Fonts | display | preconnect | 
|--------- | ----- | ------- | ------------|
| twentyten | None | 
| twentyeleven | None | 
| twentytwelve | Open Sans | fallback | yes |
| twentythirteen | Source Sans Pro, Bitter, genericons | fallback | yes |
| twentyfourteen | Lato, Genericons | fallback | yes |
| twentyfifteen | Noto Serif, Noto Sans, Inconsolata | fallback | yes | 
| twentysixteen | Merriweather, Montserrat, Inconsolata | fallback | yes | 
| twentyseventeen | Libre Franklin | fallback | yes |
| twentynineteen | NonBreakingSpaceOverride |
| twentytwenty | Inter var, NonBreakingSpaceOverride | Theme, AMP Plugin
| twentytwentyone | None |
