### ISSUE TITLE
Custom header video does not render if a custom header image is not present

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#6054]
## Bug Description

In Twenty Seventeen, if a custom header image is not set but a custom header video is, the custom header video does not render:

![image](https://user-images.githubusercontent.com/16200219/113803824-d910d600-974c-11eb-8609-35d3b51d7786.png)

This is because the `get_header_image_tag` hook does not fire to call `AMP_Theme_Support::amend_header_image_with_video_header()` to render the `amp-video` markup.

## Expected Behaviour

The custom header video should be displayed even when a custom header image is not defined.

## Steps to reproduce

1. Switch to the Twenty Seventeen theme
2. Go to the Customizer and hide the current header image
3. Set a custom header video and save
4. See that the custom header video is not displayed on an AMP page

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I think this is somewhat expected, and users should have always supplied a header image. The reason is that on a mobile viewport the homepage won't show the video, and on non-homepage doesn't show the header video regardless of the device. 

So for full feature parity this should be fixed, but in practice I doubt anyone has selected a header video without also selecting a header image.
