### ISSUE TITLE
Block content does not render if animation is added

### ISSUE THREAD

**Issue by simranvijwani** [Automattic/amp-wp#6058]
## Bug Description

Content of the Image, Gallery, and Cover block does not render if the animation is added to the block

## Expected Behaviour

Content of the block should be displayed if the animation is added to the block

## Steps to reproduce

1. Add an Image/Gallery/Cover block
2. Add the image/text
3. Add animation from the block toolbar
4. Publish the post/page
5. Check the AMP version of the post/page
6. Block content does not display
7. Clicking anywhere in the Gallery block area displays the image. 

## Screen recording

https://user-images.githubusercontent.com/34896144/113738720-c2eb2180-971c-11eb-8084-44f81e39301f.mov

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@simranjeetkaur10 Animation is not a feature of WordPress core Guteberg. What plugin are you using that adds animation? Apparently it is CoBlocks? If so, this is a bug with CoBlocks and not the AMP plugin. Note that the same issue occurs when I turn off JS in the non-AMP version. The content fails to render. This is because of the following CoBlocks CSS rule:

![image](https://user-images.githubusercontent.com/134745/114072965-a0a9ee80-9857-11eb-90bd-512f25c9e331.png)

So CoBlocks needs to:

1. Add fallback behavior for when JS is disabled or fix their animations to work without the need for JS.
2. If JS is required, add AMP-compatible effects likely using [`amp-fx-collection`](https://amp.dev/documentation/components/amp-fx-collection/?format=websites).

I see this was previously reported on CoBlocks as well: https://github.com/godaddy-wordpress/coblocks/issues/1834. So I'm closing this in favor of that issue.

**Comment by westonruter** [comment]
@milindmore22 Could be an opportunity for a PR contribution.
