### ISSUE TITLE
Error when using Google Ad Manager AMP tag with fluid layout

### ISSUE THREAD

**Issue by webzunft** [Automattic/amp-wp#6172]
## Bug Description

When copy&pasting an AMP tag from the Google Ad Manager account, the following error is visible in the source code of the AMP page:

```html
<!--
AMP optimization could not be completed due to the following:
 - CannotPerformServerSideRendering: Cannot perform serverside rendering, unsupported layout: <amp-ad layout="fluid" height="fluid" type="doubleclick" data-slot="/123/native-ad-rectangle" data-multi-size="…> => fluid
 - CannotRemoveBoilerplate: Cannot remove boilerplate because of an unsupported layout: <amp-ad layout="fluid" height="fluid" type="doubleclick" data-slot="/123/native-ad-rectangle" data-multi-size="…>
-->
```

When we remove the `fluid` size from the AMP ad tag then the ad shows up and the error is gone.

## Expected Behaviour

Consistency between the code generated for AMP in the Ad Manager account and its behavior on AMP pages. Either GAM should not generate tags that include `fluid` for AMP, or it should work with that layout.

## Steps to reproduce

1. Create an ad tag in Google Ad Manager that includes the `fluid` size – or use the dummy tag below.
2. Add the tag to the AMP site – we used [Advanced Ads](http://wpadvancedads.com/)
3. Open the source code
4. See the error mentioned above and no ad showing

Sample AMP tag

```html
<amp-ad layout="fluid" height="fluid"
    type="doubleclick"
    data-slot="/123/native-ad-rectangle"
    data-multi-size="728x90,300x250">
</amp-ad>
```

The AMP ad tag generated by GAM is different when `fluid` is not used in the same ad unit and then it also shows up:

```html
<amp-ad width=728 height=90
    type="doubleclick"
    data-slot="/123/native-ad-rectangle"
    data-multi-size="300x250">
</amp-ad>
```

## Additional context

 - WordPress version: 5.7.1
 - Plugin version: 2.0.11
 - AMP plugin template mode: Transitional, Reader

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
Thanks for the report!

Serverside rendering is disabled with the `fluid` ad layout because serverside rendering is about hard-coding a static layout into the markup (instead of letting the AMP runtime figuring it out dynamically on the client). The static layout can only be prerendered on the server if there are no unknowns about the dimensions of the individual elements. Using a `fluid` layout turns the dimensions of the ad into an unknown on the server (it adapts to its client window), therefore SSR is not possible anymore.

I'm not sure whether this is something we can fix automatically. The Google Ad Manager should not necessarily know about technical implementation details of the AMP Optimizer doing SSR. And I'm not sure we can transform the ad automatically either, because I assume the end result will be different (which is then a sanitization, instead of an optimization). We'll have to discuss this internally to see if something can be done about this.

**Comment by westonruter** [comment]
@webzunft Does Google Ad Manager always output the `fluid` layout? Or did you configure it in a way to specifically output this? I'm not familiar with the UI or what options are provided. The resolution may just be to not use the `fluid` size because this is not currently SSR-able as noted by @schlessera. Even if it were server-side rendered, it would ultimately still need to cause a layout shift on the page once loaded. So it's not ideal for performance.

You may want to consider using `layout=responsive` instead of `layout=fluid` as well.

**Comment by webzunft** [comment]
@westonruter 

In the Google Ad Manager interface, I can create the AMP tag in one step:

![Bildschirmfoto 2021-05-04 um 19 37 30](https://user-images.githubusercontent.com/2728720/117045778-2f534380-ad10-11eb-8ae7-6af16ba27653.png)

Next, I can choose the sizes:

![Bildschirmfoto 2021-05-04 um 19 38 12](https://user-images.githubusercontent.com/2728720/117045839-45f99a80-ad10-11eb-9844-a4380f19e32f.png)

I can disable the "fluid" size and all is fine.

At Advanced Ads, we have a [GAM add-on](https://wpadvancedads.com/add-ons/google-ad-manager/) that pulls ad units automatically. It makes sure that they work out of the box on AMP. So it is important for us to know how to handle fluid sizes on AMP. I am now taking away that we should ignore fluid on AMP pages. I am sure we will also find a way to communicate it to our users.

**Comment by westonruter** [comment]
I'd say to _discourage_ the use of Fluid if possible, since it is not as performant. However, if they need the Fluid size then AMP then they can do so. I'm going to follow up with the AMP team on adding SSR support for Fluid, although it will still cause a layout shift so if another unit can be used then this is preferred.

**Comment by westonruter** [comment]
I've drafted SSR support for the fluid layout here: https://github.com/ampproject/amp-toolbox-php/pull/181

A validator update will be needed before this can be merged.

Nevertheless, take note of the [Fluid layout docs](https://github.com/ampproject/amphtml/blob/main/extensions/amp-ad-network-doubleclick-impl/fluid.md):

> **Note** that due to AMP's no reflow policy, the fluid creative will not be rendered when the slot is within the viewport and it is therefore recommended that fluid be used for below-the-fold slots. For the same reason, if using the `data-loading-strategy` attribute, it is recommended that higher values be used for fluid slots, to ensure that the slot is requested before the user has time to scroll it into the viewport.

So this is another reason to avoid the `fluid` layout when possible.

**Comment by westonruter** [comment]
Update on this: the validator has been updated to allow SSR for the fluid layout. So now I've submitted https://github.com/ampproject/amp-toolbox-php/pull/181 for review and I hope to include it in v2.1.3.
