### ISSUE TITLE
object-fit with amp carousel

### ISSUE THREAD

**Issue by rsmith4321** [Automattic/amp-wp#6428]
## Feature description

Is there a way to change the object-fit property on the amp carousel that was added with a standard gallery shortcode. My galleries always have object-fit="cover" added inline in the html and I can't find a way to override this with css.  I would like it to be object-fit="contain".  Thanks for the help!

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
The `object-fit` is coming from this code:

https://github.com/ampproject/amp-wp/blob/14433a512b706643a7342b67ba119d481c6e5385/src/Component/Carousel.php#L93-L101

This is happening during post-processing so unfortunately it's not something that can be fixed with just some CSS.

The quickest solution would be to create a mini plugin that registers a new sanitizer that replaces `object-fit="cover"` with `object-fit="contain"`.

**Comment by jamesozzie** [comment]
@rsmith4321 Can you try [this mini plugin](https://github.com/milindmore22/amp-carousel-img-attribute-remover), which will ensure all individual images used the "contain" value.

**Comment by rsmith4321** [comment]
That works, thanks for the help!
