### ISSUE TITLE
Introduce support for a more flexible AMP via Bento with levels of sandboxing enforcement

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6443]
## Feature description

The AMP plugin currently offers a binary choice: either you are 100% AMP or you disable AMP. The Bento AMP initiative seeks to make AMP more flexible by allowing you to use AMP components on non-AMP pages. In reality, the AMP plugin has supported this to a limited degree in Standard mode. When invalid markup is kept, the AMP plugin serves an AMP page without the `amp` attribute on the `html` element (cf. #5549). This in effect allows you to have a page with all the benefits of the AMP runtime, but also with additional non-AMP scripts you may need. The caveat here is that this is not officially supported and since AMP components lack encapsulation, there is no guarantee that it will work. Your mileage may vary. Bento solves this problem by encapsulating the components with shadow DOM so that other scripts on the page can't interfere with their internal behavior.

An additional purpose of the Bento project is to make components much easier to author via Preact. In addition to the AMP core components being available as Bento, site owners and plugin authors may create their own Bento components which may not be “certified” for AMP and yet still have an assurance of performance by being created with the Bento framework.

With Bento components in hand, we can relax AMP validation to make pages more flexible. In particular, we can introduce sandbox levels to indicate how strict a site owner wants to be in terms of the markup allowed on the page:

* L1: The initial sandboxing level involves the plugin converting markup to Bento components where it is able (e.g. social embeds, videos, images), and then anything else it finds (custom scripts for a carousel) will be left in place. In other words, this level involves no sanitization (removal) of markup from the page. As such, this level should not break existing pages.
* L2: The second level introduces sanitization by stripping out markup that is not part of a Bento component, either a Bento AMP component or a custom 3rd party component.
* L3: The third level is the most strict and it corresponds to what is currently valid AMP. Only valid AMP components are allowed.

For the initial exploration, the sandbox levels would only be available in Standard mode. Initially it would default to L3, maintaining strict AMP validity. Once Bento matures, the plugin can switch from Reader mode being the default to instead having Standard mode with L1 sandboxing as the default. 

Additionally, in the initial sandboxing implementation, the level would largely be static. If you select L1, then that is the level that would be reflected on the rendered document. However, in a subsequent iteration the sandboxing levels should dynamically adjust based on the content of the page. So if you selected L1 and yet there is no invalid AMP markup on the page, then it would automatically be upgraded to L3.

Lastly, in future releases we may allow the sandboxing levels to be used in non-Standard modes as well, in particular Reader mode. If the user selected L1 or L2 sandboxing for Reader mode, then the paired versions would not be linked to as AMP with `link[rel=amphtml]`, since there would be no guarantee that the pages would be valid. Instead, only a `link[rel=alternate][media]` would appear as is today when mobile redirection is enabled, as is documented in the [Separate URLs](https://developers.google.com/search/mobile-sites/mobile-seo/separate-urls) documentation on Google Search Console. In other words, Reader mode with these lesser sandboxing levels would provide a “mobile theme” for the site, which would be particularly useful for sites which have a primary theme which is fundamentally not responsive with a poor user experience.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

- [ ] Remove amp attribute from html and add data-ampdevmode to Bento experiment opt-in script?
- [ ] The image sanitizer no longer converts img to amp-img but instead just ensures dimensions are provided.
- [ ] Bento versions of scripts are used instead of latest.
- [ ] The amp-runtime is omitted as a dependency of any Bento scripts. (Eventually, but currently it is required.)
- [ ] Bento stylesheets are enqueued for any Bento components used on the page. (Should these be excluded from CSS concat?)
- [ ] Add sanitizer that upgrades AMP components to Bento, specifically where attributes change or where there are backward-incompatibilities. For example, `amp-carousel` should be converted to `amp-base-carousel`.
- [ ] When there is a form POST on the page which didn't originally have `action-xhr`, do not include the `amp-form` component.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Supporting graphic:

<img width="1187" alt="Screen Shot 2021-07-23 at 9 44 22 AM" src="https://user-images.githubusercontent.com/3411173/126814641-57a8ae00-29a2-4142-822d-cf627dd6fd98.png">

**Comment by jwold** [comment]
We discussed this in our plugin sync today, and per the initial release this will be an experimental feature. We won't have a user interface to reveal the feature, but will instead make it available as a PHP filter for initial testing.

**Comment by delawski** [comment]
**QA Passed**

After enabling the experimental feature (via the [example plugin](https://gist.github.com/westonruter/b0bd2cb92454428ba0f93dd08ba98929)), I've followed the QA process described in #6546 (Testing section).

The sandboxing level selected on the AMP settings page was set to Loose. All three sample posts passed the specified tests:

| Loose mode<br>`sandboxing-level=1:1` | Moderate mode<br>`sandboxing-level=1:2` | Strict mode<br>`sandboxing-level=1:3` |
| --- | --- | --- |
| ![Screenshot 2021-11-22 at 19 36 23](https://user-images.githubusercontent.com/478735/142918066-b195edef-3061-418e-bd33-c7490e57d0c2.png) | ![Screenshot 2021-11-22 at 19 34 26](https://user-images.githubusercontent.com/478735/142918203-58d2c282-e9de-4e87-b948-1bc247829a25.png) | ![Screenshot 2021-11-22 at 19 39 53](https://user-images.githubusercontent.com/478735/142918148-092f011f-47f2-42f5-a704-a276064e068a.png) |

_Tested on AMP 2.2.0-alpha-20211117T230738Z-094aef8_

I'm leaving this issue in "Ready for QA" so that @dhaval-parekh has a chance to do a QA separately.

**Comment by dhaval-parekh** [comment]
✅  Automatically upgrading to sandboxing level if page supports it.

✅  I have tested with the QA process described in PR #6546 (Testing section) and that looks good to me.

⚠️  While doing testing in loose sandbox mode for video. I found that adding dimensions may cause some issues specifically video with higher dimensions than container width. Check the below images.

| None AMP Mode                                                                                                                     | Loose mode                                                                                                                               |
|-----------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|
| ![AMP-GH-6546-nonAMP-video](https://user-images.githubusercontent.com/8168027/143421824-b984015c-54d4-4673-a9ef-2cd091b0c449.png) | ![AMP-GH-6546-Loose-Sandbox-video](https://user-images.githubusercontent.com/8168027/143422065-f8911c25-0209-4ba3-9d9a-11c2002b7afb.png) |

However, It works perfectly in "Moderate" and "Strict" mode because of the AMP video component.
I believe we are setting height/width to reduce CLS. In that case, I think we can add a video container element ( The way `amp-video` component do ) and set height in percentage according to the aspect ratio of the video. 
cc: @westonruter @delawski 

Other than this all looks good to me.

**Comment by westonruter** [comment]
@dhaval-parekh Yes, I'm seeing that as well. Thanks for raising that. This seems like it may be a Gutenberg bug. Specifically, I'm seeing that Gutenberg has [this style rule](https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/block-library/src/video/style.scss#L4-L6):

```css
.wp-block-video video {
    width: 100%;
}
```

The `width` and `height` attributes being present, along with a `width:100%` but a lack of `height:auto` is causing the aspect ratio to not be respected.  This seems to have been something that was missed in the recent PR https://github.com/WordPress/gutenberg/pull/30092.

**Comment by westonruter** [comment]
I've opened https://github.com/WordPress/gutenberg/pull/37052 to address this.

**Comment by milindmore22** [comment]
@westonruter 

While testing sandboxing level with Strict Mode (develop branch), I noticed comment form is missing `on` attribute.

![image](https://user-images.githubusercontent.com/1132541/145073556-6cfd35e7-0e60-4b50-ab0f-97331b383ce2.png)

**Comment by westonruter** [comment]
@milindmore22 I'm not seeing that in `develop`:

![image](https://user-images.githubusercontent.com/134745/145076232-1281168f-52cd-43d8-869f-2b81a672fc10.png)

**Comment by westonruter** [comment]
Were you testing with one of these test cases?

![image](https://user-images.githubusercontent.com/134745/145076647-83bd40b9-8dc1-4de7-9fa6-a032def80fee.png)

**Comment by milindmore22** [comment]
yes, I was testing those test cases

**Comment by westonruter** [comment]
The fact that your screenshot is showing a red outline means that something is not working as expected. The test cases should only have green outlines if they are passing.

**Comment by milindmore22** [comment]
JFI : I installed production build v2.2.0-alpha-20211207T172207Z-0ab628a on the test site to confirm
https://plugins.dev6.rt.gw/sandboxing-level-strict/

**Comment by westonruter** [comment]
Can you add me to that site?

**Comment by westonruter** [comment]
Nevermind, I'm able to reproduce it now. It doesn't happen when I have the Sandboxing level set to Loose and I'm upgraded to Strict since there is nothing AMP-invalid on the page. However, if I've set the level to Strict then it fails to add the `on` attribute. Investigating...

**Comment by westonruter** [comment]
Simple fix: https://github.com/ampproject/amp-wp/pull/6769

**Comment by westonruter** [comment]
(And good catch!)

**Comment by milindmore22** [comment]
**QA Passed**

Sandboxing Levels are all well tested and Look good as per the QA process #6546

- [x] Remove amp attribute from html and add data-ampdevmode to Bento experiment opt-in script?

 - [x] The image sanitizer no longer converts img to amp-img but instead just ensures dimensions are provided.
- [x]  Bento versions of scripts are used instead of latest.
- [x] The amp-runtime is omitted as a dependency of any Bento scripts. (Eventually, but currently it is required.)
- [x] Bento stylesheets are enqueued for any Bento components used on the page. (Should these be excluded from CSS concat?)
- [x] Add sanitizer that upgrades AMP components to Bento, specifically where attributes change or where there are backward-incompatibilities. For example, amp-carousel should be converted to amp-base-carousel.
- [x] When there is a form POST on the page which didn't originally have action-xhr, do not include the amp-form component.
