### ISSUE TITLE
Allow mime type webp in Featured Image validation 

### ISSUE THREAD

**Issue by thrijith** [Automattic/amp-wp#6536]
## Bug Description

As Core 5.8 and above allows WebP support by default, it is possible user may use WebP in Featured images, though the upload for WebP is allowed, the info/alert from AMP might be confusing.

![5a5adf7d048137e9ef59e50742b78615](https://user-images.githubusercontent.com/13589980/129374476-467d3a22-c10c-4a4f-9dfc-30684e4766da.png)

Can `webp` be added to the existing list here? https://github.com/ampproject/amp-wp/blob/2df1d2a7085883a6a7f6cfba0729d8b06ffba1b5/assets/src/common/helpers/index.js#L90-L95

## Expected Behaviour

- Don't display info when `.webp` files are selected.

## Steps to reproduce

1. Edit an exiting post or `Post` -> `Add New`
2. Try using `.webp` image for Featured Image.
3. See the notice displayed saying format issues.

## Screenshots

![5a5adf7d048137e9ef59e50742b78615](https://user-images.githubusercontent.com/13589980/129374476-467d3a22-c10c-4a4f-9dfc-30684e4766da.png)

## Additional context

 - WordPress version: 5.8
 - Plugin version: 2.1.3
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version: 7.4
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Good catch.

The original issue that added this check was https://github.com/ampproject/amp-wp/issues/1812 which cited this Google Search requirement:

> Images must be in .jpg, .png, or .gif format.

The requirements have been updated to replace that point with 

<blockquote>The file format must be <a href="https://developers.google.com/search/docs/advanced/guidelines/google-images#supported-image-formats">supported by Google Images</a>.</blockquote>

That page says:

> Google Images supports images in the following formats: BMP, GIF, JPEG, PNG, WebP, and SVG.

Clearly we do not want BMP since that is _bad_ for performance. But we may want to add SVG as a recognized type in addition to WebP. 

Nevertheless, I wonder why AVIF is not included in this list?

**Comment by pierlon** [comment]
> Nevertheless, I wonder why AVIF is not included in this list?

Probably because AVIF [isn't supported](https://caniuse.com/avif) in (the stable versions of) Firefox nor Safari?

![image](https://user-images.githubusercontent.com/16200219/129402361-e662f3a5-5420-49fb-a9eb-466266081459.png)

**Comment by westonruter** [comment]
Maybe, but Google's requirements are for the sake of _Google_ being able to consume the image to surface in search results. I presume Google transforms the image into the required dimensions for SERPs and would use the required format at that time (e.g. taking what was originally a poorly-encoded JPEG and serving as an optimized WebP) rather than passing through the original format.

**Comment by pierlon** [comment]
> But we may want to add SVG as a recognized type in addition to WebP.

I forgot that WordPress doesn't support SVG images due to the possibility of code injection (here's an 8 year old [Trac ticket](https://core.trac.wordpress.org/ticket/24251) discussing it at length). Nevertheless, we can still add the SVG MIME type given that there are plugins that add support for it.

**Comment by delawski** [comment]
**QA Passed**

I've dragged and dropped a WebP image into the Featured Image pane in the editor sidebar. No info/alert message about the file format has been shown as expected:

<img width="290" alt="Screenshot 2021-08-27 at 15 37 11" src="https://user-images.githubusercontent.com/478735/131137193-273b5551-b24e-4c71-afbc-63cd779311d3.png">

*Tested against Version 2.2.0-alpha-20210825T212353Z-ab5a1e7*

**Comment by westonruter** [comment]
(To re-check on 2.1.4-alpha)

**Comment by delawski** [comment]
Confirmed to be working as expected on 2.1.4-alpha:

<img width="957" alt="Screenshot 2021-08-30 at 17 43 09" src="https://user-images.githubusercontent.com/478735/131366226-8de8dae9-7bd8-4d88-9974-fa2662e06a85.png">
