### ISSUE TITLE
Hide recommendations when Site Scan results are stale

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6690]
### Feature Description

If the Site Scan results are stale or the Site Scan is currently in progress, none of the Template Modes should have “Recommended” or “Not recommended” appear anywhere. These should only be shown if the Site Scan is complete and the results are not stale.

Additionally, it may make sense to hide the notice above the template modes since the Site Scan box already is indicating "Stale Results":

![image](https://user-images.githubusercontent.com/134745/140458410-60f566ae-6ac5-4501-bbf6-c811290d845d.png)

**Comment by delawski** [comment]
The Template Mode recommendations (both on the AMP Settings screen and in the Wizard) are defined in [`getTemplateModeRecommendation()`](https://github.com/ampproject/amp-wp/blob/develop/assets/src/components/use-template-mode-recommendation/index.js#L61-L77) and that's where the logic needs to be updated. However, since the descriptions and the recommendation levels are based on the [matrix in the Template Mode Selection doc](https://docs.google.com/document/d/1yjpVpGV6PCPs641hzmUWXzo0a46VKvjiWTytFqxtyEk/edit), it's worth first updating the matrix and use it as a single source of truth.

The notice about the results being stale it not related to `getTemplateModeRecommendation()` and should be removed separately.

**Comment by dhaval-parekh** [comment]
✅ Remove notice about stale scan results from the Template Mode section on the AMP Settings screen.

✅ Do not show any recommendations when the scan results are stale.

⚠️ Do not show any recommendations when a scan is in progress.
When results are not stale but the user still rescans the site. recommendations are still displayed to the user

https://user-images.githubusercontent.com/8168027/144273354-06d04b3d-965a-4947-86fc-4f7f22e178db.mov

**Comment by westonruter** [comment]
> ⚠️ Do not show any recommendations when a scan is in progress.
> When results are not stale but the user still rescans the site. recommendations are still displayed to the user

If the results are not stale, I don't think an in-progress scan should necessarily hide the recommendations. If the results _are_ stale then certainly the recommendations should be hidden, both before and _during_ a scan. @delawski Isn't that right?

**Comment by dhaval-parekh** [comment]
> If the results are not stale, I don't think an in-progress scan should necessarily hide the recommendations.

I agree with that.

> If the results are stale then certainly the recommendations should be hidden, both before and during a scan.

Yes, It is hidden when results are stale and during the scan (if results are stale).

With that can mark this issue as **QA Passed**.

**Comment by delawski** [comment]
> If the results are not stale, I don't think an in-progress scan should necessarily hide the recommendations. If the results _are_ stale then certainly the recommendations should be hidden, both before and _during_ a scan. @delawski Isn't that right?

That is correct 👍
