### ISSUE TITLE
Avoid showing Stale Results when landing on Settings Screen from Onboarding Wizard

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6692]
### Feature Description

Currently as soon as the Onboarding Wizard completes and the user is taken to the Settings Screen, the first thing they will see is stale results in the Site Scan. This would be confusing to the user because they had just performed a Site Scan in the Onboarding Wizard. There are two reasons why the Site Scan results from the Wizard aren't showing on Settings Screen:

1. The validated URLs are not being requested to be cached.
2. The user may not have selected Standard mode.

For the first point: instead of validating URLs with `amp-first`, we can instead pass the desire to check URLs in Standard Mode by passing a parameter like `amp_validate[force_standard_mode]=1`. This `amp_validate` parameter is removed from the URL when it is stored in the Validated URL, so then such URLs should be returned when obtaining the Scannable URLs on the Settings Screen, if they had been requested to be cached in the onboarding wizard.

For the second point: When the user clicks "Close" to exit the Onboarding Wizard to go back to the Settings screen, there should be a query parameter included to indicate they had just completed the Wizard. When this parameter is present, if the Site Scan results are stale, a scan should be automatically initiated.

cf. https://github.com/ampproject/amp-wp/pull/6683#issuecomment-961507054

**Comment by dhaval-parekh** [comment]
**QA Passed**

Site scanning is initialized when a user came back from the onboarding wizard and there is stalled result. ✅ 

https://user-images.githubusercontent.com/8168027/144231449-58e08029-6255-4c07-bc91-5418a19435c7.mov



However, If initially the "Transitional" mode is selected and the user opens the onboarding and go through the process and came back to the AMP setting screen there will always be staled result because the Onboarding wizard use force standard mode.
