### ISSUE TITLE
Validated URL data may not be included with Support request

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6707]
### Bug Description

I realized that if you're on the frontend and you click the Support in the AMP admin bar menu:

> ![image](https://user-images.githubusercontent.com/134745/141170391-73e9e966-0b11-4633-95d8-4d8bb8b6cfaf.png)

If you hadn't first gone to “Validate URL” the result is that the URL will not be included among the validated URLs that are included in the request. I was on `https://wordpressdev.lndo.site/2021/03/amp/` but the URLs being sent are only the non-stale URLs checked by Site Scan:

> ![image](https://user-images.githubusercontent.com/134745/141170623-f9362f56-9d10-4feb-aa00-b45c0520ab47.png)

The URL here is `/w-admin/admin.php?page=amp-support&post_id=0`.

If, however, I validate the URL first and then click the “Get Support” link on the Validated URL screen:

> ![image](https://user-images.githubusercontent.com/134745/141170835-b4292e14-6c49-44bf-a99c-36c1c218e7a9.png)

Then I am taken to `/wp-admin/admin.php?page=amp-support&post_id=3914` and that URL is included:

> ![image](https://user-images.githubusercontent.com/134745/141170915-b24226f8-ef8a-47e7-859b-95a07625f099.png)

The passed `post_id` query var is the post ID of the Validated URL post. When one doesn't exist, then it has to resort to non-stale Validated URLs instead of the URL that the user was on. This isn't ideal. Note that when a user has Developer Tools turned off, the Validate URL menu item is _omitted_, so it will be common for users to not have the Validated URL data included.

### Expected Behaviour

Instead of passing the `post_id` of the validated URL to send, I suggest the frontend URL itself be included as a query var. Then on the AMP Support screen, it should make a request to that URL with the necessary `amp_validate` query parameters to obtain the _fresh_ data to send with the request. How to do this can be seen in the new Site Scan feature (although no need here to store/`cache` the validation results).

### PHP Version

7.4

### Plugin Version

2.2-alpha

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by dhaval-parekh** [comment]
I also noticed that If there is no error information available, the "Support page" doesn't provide more information about why there is no error information, especially when a user doesn't request a specific URL.

There could be several reasons for not having AMP error information. Such as no validation has been done or results are stalled because of changes in AMP settings of the new plugin, or maybe the validated URL doesn't have any AMP Error (but there are some stalled results).

e.g. The screen below doesn't provide more information other than there is not error information.
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/8168027/142405320-c3235d9b-6f77-46af-bf51-6768dd8055e4.png">


Also, When a specific URL is requested, and that doesn't have an AMP error. In such cases, We should show appropriate notice to the user. 

However, I'm not sure if we should allow users to request support if there is no error information?
cc: @westonruter

**Comment by westonruter** [comment]
If there are zero non-stale validated URLs and the user didn't request support from a specific frontend URL, one option would be to go ahead and obtain the site scan results for the scannable URLs. cc @delawski

**Comment by delawski** [comment]
> Instead of passing the `post_id` of the validated URL to send, I suggest the frontend URL itself be included as a query var. Then on the AMP Support screen, it should make a request to that URL with the necessary `amp_validate` query parameters to obtain the _fresh_ data to send with the request. How to do this can be seen in the new Site Scan feature (although no need here to store/`cache` the validation results).

@westonruter A general question: did you envision the single URL validation happening asynchronously, client-side, like in the Site Scan, or "traditionally", i.e. synchronously on the backend? I guess the latter and that's how it's implemented in #6718.

**Comment by westonruter** [comment]
I was hoping asynchronously client-side the same way as is done for Site Scan and the same way that is being implemented after plugin activation and when saving a post.

**Comment by delawski** [comment]
This would require taking a quite different approach than what we have in #6718.

I could see the following as a potential way forward:
- Review and use the backend validation proposed in #6718 in the near term.
- Replace the backend validation with a client-side async process as soon as #6685 is done since it would share some code introduced there. I could take care of that next and I think there's still a chance to have it done as part of v2.2.

What's your take on that?

cc @maitreyie-chavan

**Comment by westonruter** [comment]
Doing async client-side validation requests is what I was intending to specify with the expected behavior:

> Then on the AMP Support screen, it should make a request to that URL with the necessary `amp_validate` query parameters to obtain the _fresh_ data to send with the request. How to do this can be seen in the new Site Scan feature (although no need here to store/`cache` the validation results).

So taking the same approach as Site Scan, whether that's on the Settings Screen, Onboarding Wizard, or (soon) plugin activation screen.

But assuming there us a frontend `url` provided, as opposed to incorporating all of the site scanning logic, to me it seems it could be as simple as just doing the request client-side instead of server-side. I haven't yet dug into the PR yet, however.

**Comment by delawski** [comment]
> But assuming there us a frontend `url` provided, as opposed to incorporating all of the site scanning logic, to me it seems it could be as simple as just doing the request client-side instead of server-side. I haven't yet dug into the PR yet, however.

Yes, it makes sense. It would be as simple as making a `fetch` request and then processing the response. No need to reuse the logic from Site Scan (the `SiteScanContextProvider` is pretty heavy and has a few other dependencies so it'd be better to have a lightweight replacement for fetching validation data for a single URL).

**Comment by dhaval-parekh** [comment]
Async would be a good idea. However, we can not use the same API that we use for site scanning. Since data will be different. 

Support data service generates its own slugs for errors and errors source and does not use that is generated during validation. Also, it modifies the data (remove site domain from errors and error sources.) 

To make it async, We need to add a new API that will return support data based on the provided argument. (besides we use to send support requests). Something like `amp/v1/get-diagnostic-data`

**Comment by milindmore22** [comment]
**QA Passed**

| Scenario         |    Support Link  | Validated URL included |QA Status  |
| --------------|----------------------- | --------------|--------------|
| Page with Validation error  |  Admin ToolBar | Yes | ✅  |
| Page with no validation errors error | Admin ToolBar | No (message displayed) |  ✅  |
| Page with Validation error  |  Validation Tool | Yes | ✅  |
| Page with no validation errors error | Validation Tool | No (message displayed) | ✅  |
