### ISSUE TITLE
Author URL missing

### ISSUE THREAD

**Issue by dyderik** [Automattic/amp-wp#6729]
### Bug Description

The bug is described on https://wordpress.org/support/topic/google-search-console-problem-4/ James Osborne doesn't reply me anymore. Please assist. Thanks!

### Expected Behaviour

The Google rich snippet Warning should not be there. The plugin AMP for the theme GeneratePress is also installed. Version is 0.1

### Plugin Version

2.1.4

### AMP plugin template mode

Standard

**Comment by milindmore22** [comment]
Hello @dyderik 

Sorry for the inconvenience, When you confirmed the issue is fixed we marked that topic as resolved, once we do that it doesn't show us your topic as "pending" so we are not able to notice that.

Can you please create a [new support topic](https://wordpress.org/support/plugin/amp/#new-topic-0) and we are happy to assist you further.

**Comment by dyderik** [comment]
Ok done and thanks!
