### ISSUE TITLE
User is asked to purge caches even if no page caching is enabled

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#6731]
### Bug Description

Related: #4843, #4386

After deactivating a page caching plugin (WP Super Cache), a user is asked to purge caches when switching a template mode.

If Site Health is visited before switching a template mode, a user is not asked to purge the cache anymore.

It seems a page caching test should be done every time a plugin is deactivated (and possibly activated, too).

The video presents a QA process of #4843. Compare the message with and without visiting a Site Health page between plugin deactivation and template mode change:

https://user-images.githubusercontent.com/478735/142615825-648a1d71-8074-44ad-b316-82519f44ce45.mp4

### Expected Behaviour

If there is no page caching detected on a site, a user should not be asked to purge caches after switching a template mode.

### Plugin Version

2.2.0-alpha-20211117T230738Z-094aef8

### AMP plugin template mode

Standard

**Comment by westonruter** [comment]
> It seems a page caching test should be done every time a plugin is deactivated (and possibly activated, too).

Also, even though a caching plugin is activated, it may not be caching initially. With WP Super Cache, for example, caching has to be enabled after activating the plugin. So we wouldn't be able to check for that scenario.

Honestly, I'm not sure this is really needing to be fixed. It's unlikely that someone is going to be turning off their page caching plugin. And even if they do, the notice to ask the user to flush the page cache isn't really going to hurt. On the other hand, fixing the problem would require re-running the Site Health test with each save, which would be expensive.

I'm OK with this being a known limitation.

**Comment by delawski** [comment]
> I'm OK with this being a known limitation.

I think that in this case we can close the issue, right?

**Comment by dhaval-parekh** [comment]
I also noticed there can be the reverse scenario as well. Where "Page cache" is disabled initially but even after enabling it will not show any notice to flush the cache. It's because we are using the cached results of the "page cache" test.
(However, it will perfectly work if "Page cache" is already enabled or cached results are not available)

https://user-images.githubusercontent.com/8168027/142995188-2db1b299-e90c-40aa-b9e2-ce43e7edbe75.mov

To address that, We can use REST endpoint `/amp/v1/test/page-cache` to check the availability of page cache asynchronously on the "AMP Setting" page. Or we can reduce the expiration time.

**Comment by westonruter** [comment]
True, but requests to `/amp/v1/test/page-cache` are slow due to the loopback requests. So if we wait for it to return, we'll be slowing down the save process and adding a lot of server load without much benefit, I feel.

While the `amp_has_page_caching` transient has a life of 1 month in the success case, in reality since Site Health runs via WP Cron on a weekly basis, the transient will never be older than 1 week. So I feel it's not critical to have fresher information on the Settings screen. I'm happy to be wrong.

**Comment by westonruter** [comment]
Closing maybelater.
