### ISSUE TITLE
Mobile menu from Twenty Twenty-two isn't working

### ISSUE THREAD

**Issue by fellyph** [Automattic/amp-wp#6790]
### Bug Description

I know there are some work for the version 2.3, but I was testing the core theme Twenty Twenty-two and I found two validations errors: 
![Screen Shot 2021-12-14 at 13 21 25](https://user-images.githubusercontent.com/330792/146011099-f7f96f86-29b0-4062-921e-b2be11af717b.png)
![Screen Shot 2021-12-14 at 13 21 52](https://user-images.githubusercontent.com/330792/146011110-54dfefe9-5744-4ea9-93a3-5a6ee7033c68.png)

And the last one is affecting the navigation menu on mobile, at the AMP version the menu is not working:
https://user-images.githubusercontent.com/330792/146012100-6dd07b11-113f-4c4b-bfdd-0dd5dac4169f.mp4

### Expected Behaviour

The mobile menu works on AMP and non-AMP version

### PHP Version

8.0

### Plugin Version

2.2

### AMP plugin template mode

Transitional

### WordPress Version

5.9 beta 2

### Gutenberg Version

12.1.0

### OS(s) Affected

MacOs

### Browser(s) Affected

Chrome

**Comment by westonruter** [comment]
I opened a PR to add `aria-modal` to the validator spec a few weeks ago: https://github.com/ampproject/amphtml/pull/37002

I've also identified the validation error in the existing issue regarding the responsive navigation block: https://github.com/ampproject/amp-wp/issues/6319#issuecomment-969854748

This should be fixed with https://github.com/ampproject/amp-wp/pull/6744

So I'm going to close this as a duplicate.
