### ISSUE TITLE
No AMP blocks available

### ISSUE THREAD

**Issue by marziolek** [Automattic/amp-wp#6836]
### Bug Description

Fresh WP install, no plugins except for AMP. There are no available AMP blocks.

### Expected Behaviour

There should be multiple AMP blocks i.e JW Player block

### PHP Version

7.3.21

### Plugin Version

2.2.0

### AMP plugin template mode

Standard

### WordPress Version

5.8.3

**Comment by westonruter** [comment]
> There should be multiple AMP blocks i.e JW Player block

These blocks have been deprecated/removed due to low/no usage. See #4556. Registration of these blocks is now omitted if they are not being used on a post: #5575.

As an alternative to these blocks, you could just use the Custom HTML block and add the AMP markup directly. The blocks were not particularly well designed in terms of user interface, so you're not losing much by just adding the markup yourself. For example:

```html
<amp-jwplayer
  data-player-id="aBcD1234"
  data-media-id="5678WxYz"
  layout="responsive"
  width="16"
  height="9"
>
</amp-jwplayer>
```
