### ISSUE TITLE
Plugin renders default css from TWC on amp pages with Nginx

### ISSUE THREAD

**Issue by edgin** [Automattic/amp-wp#685]
Plugin renders default css from TWC (total cache) onall amp pages 
therefore resulting in errors for amp pages , its on nginx is server.
Do you know what setting might be cousing it?

**Comment by amedina** [comment]
This issue is related to the TWC plugin modifying the AMP pages after they are generated by the AMP plugin. We do not have a solution for avoiding such problems other than avoiding the use of plugins that invalidate AMP pages. If possible, check with the TWC plugin to see if the permalinks with the /amp slug can be avoided.
