### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by jridgewell** [Automattic/amp-wp#687]
Cross posting @riyaz95's [report](https://github.com/ampproject/amphtml/issues/8873) made on the AMP HTML repo:
- - -
Hi
my error_log is growing with:
[19-Apr-2017 09:14:10 UTC] PHP Warning: Invalid argument supplied for foreach() in /home/user/public_html/wp-content/plugins/amp/includes/utils/class-amp-html-utils.php on line 11

I know it’s just a waring but it grow up every minute… 🙁

(I’m using PHP 7)

Thanks

PS: The error_log file is generated by the server

**Comment by mjangda** [comment]
Do you have the full stack trace @riyaz95? The method expects an array, which means it's being called incorrectly and it would be good to understand where in the stack that's happening.

**Comment by pako69** [comment]
Hi

I'm the one who have his error_log growing with amp errosr (https://wordpress.org/support/topic/erro_log-invalid-argument-supplied-for-foreach/)

Someone asked me to create a Github account to post my error_log.

I have never used Github before so I hope that's what you were waiting for... I have attach here the error log, note that it is not the full error_log but just for 2 days (I forced to delete this error_log file because it's become biger every day...)

PS: I'm not english, so please excuse my typos. :)

Thanks

[error_log.zip](https://github.com/Automattic/amp-wp/files/988830/error_log.zip)

**Comment by pako69** [comment]
Hello
Do you need something more?
Thanks

**Comment by amedina** [comment]
Hi Pako69, the method expects an array and apparently that pre-condition is being violated; the file you sent is the error log with the messages; can you provide more details such as a full stack trace?

**Comment by pako69** [comment]
Hi
I installed a WordPress plugin named Query Monitor, and then go to this AMP posts: https://www.domodeco.fr/interieur/chambre/bien-dormir-tout-un-savoir-faire/amp
> See the quey debug output in my screenchot.
I hope it can help...
Thnaks
![amp-stack](https://cloud.githubusercontent.com/assets/28571856/26711010/deb40782-475d-11e7-93d2-66bdc136ffe3.jpg)

**Comment by laptopleon** [comment]
I'm not using AMP but I have a similar error 'foreach()' in my error logs and all kinds of trouble with Wordpress, with uploading images amongst others. Is there anything I can do or is this more in the scoop of a programmer? (They regular methodes like disabling plugins do not work out.)

**Comment by amedina** [comment]
This is actually not related to Automattic's AMP plugin; the AMP plugin referred to here is this one: https://wordpress.org/plugins/accelerated-mobile-pages/
