### ISSUE TITLE
Story transformer should optimize images in story

### ISSUE THREAD

**Issue by mszylkowski** [Automattic/amp-wp#6911]
### Feature Description

The transformer currently doesn't optimize /compress all the images in stories, I'm not sure what images get compressed so I'll list all that need to. This improvement could bring **_very_** significant LCP improvements to most stories.

- `<amp-img src>`
- `<amp-img srcset>`
- `<image href>` and `<image xlink:href>` which are SVG-specific images.
- `<link rel=icon href>`
- `<link rel=preload as=image href>`
- `<link rel=preload imagesrcset>`
- `<amp-story-page-attachment cta-image>`
- `<amp-story-page-attachemnt cta-image-2>`
- `<amp-story-page-outlink cta-image>`
- `<amp-video poster>`
- a background image given in the `<style amp-custom>` tag / style attribute

For instance, https://hamdirecipes.com/web-stories/ina-garten-meatloaf-recipe/ has a 1000x1500 outlink cta-image that shouldn't be larger than 24x24.

### Acceptance Criteria

The link above has a page outlink icon that's smaller than 1000x1500, and other images currently not compressed are also smaller

cc @ampproject/wg-stories @ampproject/wg-performance

**Comment by erwinmombay** [comment]
cc @westonruter for input

**Comment by westonruter** [comment]
This should really rather get reported to https://github.com/GoogleForCreators/web-stories-wp

The AMP plugin doesn't do any image optimization. Rather, it relies on ecosystem plugins to do the optimization. For example, I opened pull requests so that Jetpack's Image CDN would apply to images in stories: https://github.com/Automattic/jetpack/pull/12821 and https://github.com/Automattic/jetpack/pull/13278.

I'm not sure what the current state of the art is for image optimization in the Web Stories plugin, but @swissspidy would know.

**Comment by erwinmombay** [comment]
@westonruter my apologies, i was the one who pointed @mszylkowski here. thanks for pointing us to the correct repo!

**Comment by swissspidy** [comment]
@erwinmombay @mszylkowski Heya, TL fir the Web Stories WP plugin here 👋  Happy to go discuss this on our repo or offline.

Since the primary issue seems to be a very large outlink cta-image, some background:

In the WP editor, when adding outlinks we grab the target‘s favicon or Open Graph image by default. That image is sinpmy hotlinked, so we don‘t do any additional processing there.

If this is a common issue with WP stories I‘m happy to prioritize some appropriate fix though.

Curious to learn more.
