### ISSUE TITLE
Amp validation failing for the site https://point4counterpoint.wordpress.com

### ISSUE THREAD

**Issue by charliescheer** [Automattic/amp-wp#692]
In the ticket <a href="https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3188608&departmentid=41&ticketstatusid=5#">3188608</a> a user contacted us because they had received a message informing them that there were issues with their site and amp.  The information they were given was:
Accelerated Mobile Pages
Fix applicable issues in your Accelerated Mobile Pages (AMP) in order to
have them prominently served to mobile users. Learn more.

Accelerated Mobile Pages > Invalid layout property found in AMP tag
(Critical issue)
Fix invalid layout properties in your AMP tags. AMP pages with invalid
layout property may appear in Google search results without AMP-specific
display features. Learn more.

Status: 5/3/17
7

AMP pages with issues
Status: 5/3/17
285

Indexed AMP pages
10

AMP pages with critical issues

AMP URLLast detected
1
/2017/02/24/treating-migraines-more-ways-to-fight-the-pain/amp/
4/29/17
2
/2017/03/25/is-it-really-fda-approved-u-s-food-drug-administration-fda/amp/
4/27/17
3
/2017/04/04/today-is-equal-pay-day-help-us-close-the-gender-wage-gap/amp/
4/27/17
4
/2017/04/27/miracle-cures-u-s-food-drug-administration-fda/amp/
4/27/17
5
/2017/03/27/improving-your-odds-for-cervical-health/amp/
4/26/17
6
/2017/03/27/improving-your-odds-for-cervical-health/amp/
4/26/17
7
/2017/04/24/codeine-and-tramadol-can-cause-breathing-problems-for-children/amp/
4/26/17

I ran the <a href="https://validator.ampproject.org/#url=https%3A%2F%2Fpoint4counterpoint.wordpress.com%2F2017%2F02%2F24%2Ftreating-migraines-more-ways-to-fight-the-pain%2Famp%2F">validator</a> and it failed for me as well
I could not identify any obvious reasons for the failure.

**Comment by k-atul** [comment]
@charliescheer  Although this should be handled by the plugin itself, but you can add a filter to the_content and for amp-img tag and check if it has height="" blank then add some static height value to it. Something like below.

add_action( 'pre_amp_render_post', 'amp_content_filter' );
function amp_content_filter() {
	add_filter( 'the_content', 'amp_tag_filter'  );
}
function amp_tag_filter( $content ) {
//code check here
}

**Comment by designsimply** [comment]
Tested and confirmed the problem where AMP does not validate for https://point4counterpoint.wordpress.com/ I checked https://validator.ampproject.org/#url=https%3A%2F%2Fpoint4counterpoint.wordpress.com%2F and here are the first few errors and a screenshot for reference:

* The mandatory attribute '⚡' is missing in tag 'html ⚡ for top-level html'.
* The property 'minimum-scale' is missing from attribute 'content' in tag 'meta name=viewport'.
* The tag 'script' is disallowed except in specific forms.
* The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'.

There are quite a few errors shown on the AMP validation page:

![image](https://cloud.githubusercontent.com/assets/1119271/26503925/dadc02bc-41ff-11e7-9ed9-eb47430eaf4c.png)
<sup>Seen at https://validator.ampproject.org/#url=https%3A%2F%2Fpoint4counterpoint.wordpress.com%2F using Firefox 53.0.3 on Mac OS X 10.12.5.</sup>

I see similar errors for my test blog at https://validator.ampproject.org/#url=https%3A%2F%2Fdesign5279.wordpress.com%2F

I also tested searching for those sites and viewing their AMP pages using Pixel, Android 7.1.2 and everything loaded normally, so I am not sure how important the validation problems are to get to since I can't tell based on the information I've seen so far that they are causing problems.

**Comment by amedina** [comment]
These errors do not seem related to the plugin. It is likely that the site has some other plugin installed which is undoing the work of the AMP plugin. Notice for example that even the AMP (i.e. lightning bolt) in the html tag is missing.
