### ISSUE TITLE
WordPress FSE and AMP-WP lazy loads the Gutenberg logo block resulting in an LCP error

### ISSUE THREAD

**Issue by rolandfarkasCOM** [Automattic/amp-wp#6942]
### Bug Description

 I am not 100% sure if this is a problem with either AMP-WP or Gutenberg..

**Largest Contentful Paint** image was lazily loaded:

> _Above-the-fold images that are lazily loaded render later in the page lifecycle, which can delay the largest contentful paint._

@westonruter, the `loading=lazy` attribute is present on the non-amp version of the page, so it could be Gutenberg causing this but could the AMP-WP plugin remove this from the Gutenberg logo block before rendering `<amp-img>`? Or shall I raise this under the Gutenberg Github issues?

### Expected Behaviour

Above-the-fold images shouldn't be lazily loaded and cause a delay in LCP

### PHP Version

8.0

### Plugin Version

2.2.1

### AMP plugin template mode

Standard

### WordPress Version

5.9.1

### Gutenberg Version

10.8-11.9

### OS(s) Affected

Ub

**Comment by westonruter** [comment]
> the `loading=lazy` attribute is present on the non-amp version of the page, so it could be Gutenberg causing this but could the AMP-WP plugin remove this from the Gutenberg logo block before rendering `<amp-img>`? Or shall I raise this under the Gutenberg Github issues?

In WordPress core, the `get_custom_logo()` function explicitly omits the `loading` attribute, and I see that the Site Logo block's [`render_callback`](https://github.com/WordPress/gutenberg/blob/d5915916abc45e6682f4bdb70888aa41e98aa395/packages/block-library/src/site-logo/index.php#L26) in Gutenberg is calling that same function. So I don't know why `loading=lazy` would be present. This may have actually been reported as an issue here: https://github.com/WordPress/gutenberg/issues/30960. Apparently even though the Site Logo block omits the `loading` attribute, the fact is that the `wp_img_tag_add_loading_attr()` function then adds the `loading` attribute anyway since it is part of the content in a FSE context.

It appears you can fix this by adding a `wp_img_tag_add_loading_attr` filter to prevent `loading` from being added. I believe this would work:

```php
add_filter(
	'wp_img_tag_add_loading_attr',
	static function ( $value, $image ) {
		if ( false !== strpos( $image, 'custom-logo' ) ) {
			$value = false;
		}
		return $value;
	},
	10,
	2
);
```

**Comment by rolandfarkasCOM** [comment]
Thank you for that @westonruter, that's a nice workaround and exactly what I needed! 🙏
