### ISSUE TITLE
Improve checks for image dimensions extraction to avoid warnings

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6968]
### Bug Description

As per this [support topic](https://wordpress.org/support/topic/php-warning-division-by-zero-in-class-amp-img-sanitizer-php-on-line-299/) User seeing a warning while extracting a dimension of an image. 

``` PHP Warning: Division by zero in /wp-content/plugins/amp/includes/sanitizers/class-amp-img-sanitizer.php on line 299```

I am not able to reproduce the issue at my end by I think it might be unsupported image type or corrupted image, which returned `0` or `false` 

As [suggested](https://wordpress.org/support/topic/php-warning-division-by-zero-in-class-amp-img-sanitizer-php-on-line-299/#post-15415762) by Weston we should replace `isset()` checks with `empty()` to avoid warning and apply fallback dimensions instead.

### Expected Behaviour

Should not show any warrning 

### PHP Version

7.4

### Plugin Version

2.2.1

### AMP plugin template mode

Reader

### WordPress Version

5.9.1

### Site Health

Site health : https://insights.amp-wp.org/admin/report/uuid/ampwp-2c37937f-1474-5871-856e-92cd1bf35954

**Comment by westonruter** [comment]
This is the line in question: 

https://github.com/ampproject/amp-wp/blob/28bc1bb1ef7b4d78cdcce16d7c0ce114a1acec5e/includes/sanitizers/class-amp-img-sanitizer.php#L299

Somehow `$dimensions['width']` is `0`. Fixing the symptom would be to just make sure that `$dimensions['width'] > 0`. I wonder if it is actually `false` here and it is being cast to `0`. I wonder if instead of checking `isset()` if we should rather be checking `! empty()` in this method.

The value for `$dimensions['height']` is most likely coming from here: 

https://github.com/ampproject/amp-wp/blob/28bc1bb1ef7b4d78cdcce16d7c0ce114a1acec5e/includes/utils/class-amp-image-dimension-extractor.php#L246-L249

So perhaps `wp_getimagesize()` is returning a bad value?

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Images are rendering proper dimensions and no warnings are displayed. 

| Image type    | Actual Dimension | Displayed Dimensions | Warning |
| ------------- | ------------- | ----------- | ----------- |
| JPEG   | 534x340 | 534x340 | NO
| PNG  |  1080x1920 | 1080x1920 | NO |
| JPG | 1280x796 | 1280x796 | NO|
| PNG | 920x946 | 920x946 | NO |
