### ISSUE TITLE
Ensure Plugin Suppression section is scrolled into view when deep linked

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7005]
### Bug Description

As noted by @pooja-muchandikar in https://github.com/ampproject/amp-wp/issues/5340#issuecomment-1076232982:

> If `Suppressed on AMP Pages` link is clicked from plugin screen, it should redirect to AMP settings > Plugin Suppression section. But currently it is redirecting to AMP settings > Review Section
> 
> Issue is specifically in Chrome Browser latest version
> In Safari Browser latest version it is working fine. 
> 
> https://user-images.githubusercontent.com/41000648/159684293-8f48f4ed-d34b-4c2f-8eef-81a67f398772.mov

I think this is a separate issue with the Settings screen. Namely, I think the Review section is loaded asynchronously after the scrolling has started so that once the scrolling ends up the Review section and not Plugin Suppression. 

Nevertheless, I am not able to reproduce the issue right now.

### Expected Behaviour

The Plugin Suppression section should be scrolled into view when linking to `/wp-admin/admin.php?page=amp-options#plugin-suppression`.

Note the Analytics link in the admin menu should also consistently deep-link to the Analytics section of the settings screen.

### Plugin Version

2.2.2

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by dhaval-parekh** [comment]
@pooja-muchandikar Can you please provide a specific Browser and it's the version where you were facing this issue?
And if you can provide screen resolution that will be great..

**Comment by pooja-muchandikar** [comment]
@dhaval-parekh Following are the details where issue was observed. 

AMP Mode: Standard

Browser Details:
Chrome Version 100.0.4896.60 (Official Build)

Screen Resolutions Tested:
1440x900 and 1280×640

**NOTE:** Redirections is working fine with above resolution in safari browser(v14 and v15)

**Comment by pooja-muchandikar** [comment]
QA Passed ✅  With One Regression Issue.

Chrome Version 102.0.5005.61, Also checked with Chrome Version 100.0.4896.60 -> Review Plugin Suppression is redirected/scrolled to proper section. 

---

**But Found one regression issue(Browser Safari Version 14.0.3  and Safari 15.3)** When the Review Plugin Suppression is scrolled to review section the menu from left sidebar scrolls upwards. Because of the UI is not looking good. Observe the sidebar in following screenshots. 


---

Chrome Browser Scroll:

![image](https://user-images.githubusercontent.com/41000648/172153938-d151b81b-c7f8-4e2a-9cd8-e46847d14033.png)

---

Safari Browser Scroll:

<img width="1060" alt="screenshot_2022-06-06_at_5 04 55_pm" src="https://user-images.githubusercontent.com/41000648/172154091-f79498be-50a9-4289-92fc-1e7ef0279405.png">

---

**Comment by westonruter** [comment]
That would seem like it is a bug in WordPress core and not something we should worry about.
