### ISSUE TITLE
Pre-fill default configuration for top analytic vendors.

### ISSUE THREAD

**Issue by dhaval-parekh** [Automattic/amp-wp#7019]
### Feature Description

Currently, When users select "googleanalytics" or "gtag" in Analytics section ( in AMP Settings page) It pre-fills the default configuration.

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/8168027/161249236-c990ade1-3cfc-497d-9506-9de8e9ecd943.png">

A similar feature, we need to implement for other top vendors. 

1. Google Analytics
2. Google Tag
3. Google Ads
4. Adobe Analytics
5. Alexa Metrics
6. Baidu analytics
7. Facebook Pixel
8. New Relic
9. Nielsen
10. Yandex Metrica

An example of default configuration can be found [here](https://github.com/ampproject/amphtml/blob/main/examples/analytics-vendors.amp.html).

**Comment by dhaval-parekh** [comment]
Related issue #6367

**Comment by pooja-muchandikar** [comment]
QA Passed ✅  

Cross checked the 10 top vendors listed in issue description all are working fine except Google Ads. Google Ads default configuration is not getting pre-filled and this is expected behaviour as per the conversation with @dhaval-parekh 

https://user-images.githubusercontent.com/41000648/172155316-d8eadba7-d69d-4610-8a26-592f0f3a20cd.mov
