### ISSUE TITLE
Bump minimum PHP version from 5.6 to 7.0

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7031]
### Feature Description

As discovered in a [support topic](https://wordpress.org/support/topic/version-2-2-2-parse-error-syntax-error-unexpected/), when Composer runs now on PHP 8 it will generate an `autoload_real.php` that causes syntax errors for PHP 5.6. According to the latest [WordPress Statistics](https://wordpress.org/about/stats/), PHP 5.6 only accounts for 6.6% of all installs, and any site running that version of WordPress gets a big upgrade warning shown on the Dashboard. PHP 5 versions older than 5.6 (which WordPress doesn't support now either) take up 2.9%. Given that PHP 5.6 is significantly slower than PHP 7 and PHP 8, it is not in the best interest of users to allow them to stay on this old version either in terms of PX.

![image](https://user-images.githubusercontent.com/134745/162071331-538a34f8-2016-4cab-884b-a3764af75d5f.png)

- [x] Bump the minimum PHP version in `README.md`.
- [x] Bump PHP version in `amp.php`, in both the metadata header and the `if` version check statement.
- [x] Remove PHP 5.6 from the `build-test-measure.yml` testing matrix.
  - [x] Eliminate the `install-pwa-plugin` matrix property (since always `true`).
  - [x] Move the `external-http` from 5.6 to new lowest PHP version 7.0.
- [x] Bump the PHP version used in the `build-zip` GHA step (see #7030).
- [ ] ~Remove any tests that targeted PHP<7.~
- [ ] ~Add step to deploy command that lints the files in `vendor` for PHP 7.0 compatibility (e.g. via phpcs).~

**Comment by eldietista** [comment]
Its funny. 
I reviewed the plugin explaining exactly the problem with for this php 5.6 compatibility, speed....and you deleted my review and blocked my user. 
But I find here that you do know that WP doesn´t support 5.6.
And you do know that is slower.
And despite you do perfectly know, you cant accept a review with one star and instead keep deleting WP users older than this plugin. 
Its extremely sad to see that developers can´t take opinions. And instead, bully a customer for having an opinion, experience and knowledge.
If you don´t want opinions, don´t have your plugin in WP repository. You may choose to and sell it in a website with fake opinions if you wish.
Its quite sad from anyone not being able to accept bad reviews and get moderators to use them to delete reviews thta have a perfect point, are explained, have background and knowledge behind.
We webmasters spend lots of hours to make our sites
1) secure and php 5.6 is not, since is not lkonger patched.
2) fast and php 5.6 is not compared to 7 or 8.
Its not like php 7 is new. And if we work to update content its sad to find ourselves using plugins that are mean to increase speed, that instead use old code, slow and dangerous.
Now you can delete, or whatever my account, if you can´t take opinions... its your problem, you will have to deal with it sooner or later.
Regards :)

**Comment by westonruter** [comment]
@eldietista

> I reviewed the plugin explaining exactly the problem with for this php 5.6 compatibility, speed....and you deleted my review and blocked my user.

I didn't delete your review and I didn't block you. This was done by a forum moderator because you violated the support forum guidelines. The forum moderator explicitly contradicted you when you said that WordPress requires PHP 7: WordPress requires PHP 5.6 but recommends PHP 7.

> But I find here that you do know that WP doesn´t support 5.6. And you do know that is slower.

Where do you find here that WP doesn't support 5.6? I never said that. I just said that only 6.6% of WordPress installs run on 5.6. So it's not worth the maintenance burden to remain compatible with 5.6. By increasing the minimum version, users will be forced to upgrade. WordPress core already warns users of PHP 5.6 to upgrade due to being slower and insecure. It's shown as a big metabox on the dashboard.

Again, as I've said over and over again, the AMP plugin does not require PHP 5.6 instead of PHP 7 and PHP 8. It is compatible with all these PHP versions, the same as WordPress core and other popular plugins. Yoast SEO has a minimum PHP requirement of 5.6 the exact same as the AMP plugin. WordPress core _recommends_ PHP 7 but still supports PHP 5.6. We and other popular plugins have done the same. Plugins are slowly bumping the minimum version to PHP 7 since there are fewer and fewer installs running PHP 5.6. 

It's the same situation as WordPress and Internet Explorer. Until recently WordPress supported Internet Explorer but it didn't by any means require using IE11. You were recommended and encouraged to use a modern browser. But IE11 support was dropped when usage dropped low enough to warrant compatibility. It's the same situation for PHP compatibility.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Created an environment with PHP 5.6 and tried to install AMP plugin(development build), error was displayed mentioning requirement of PHP .0 as expected.

![image](https://user-images.githubusercontent.com/41000648/173013437-03c49914-daa7-49fe-8e00-5135233df367.png)
