### ISSUE TITLE
Desktop Expanded menu not Working on the Twenty Twenty Theme

### ISSUE THREAD

**Issue by fellyph** [Automattic/amp-wp#7056]
### Bug Description

The core theme Twenty Twenty, has different Menu Locations and one option is the Desktop Expended Menu:

<img width="775" alt="Screen Shot 2022-04-14 at 16 17 42" src="https://user-images.githubusercontent.com/330792/163421163-2db1e22b-5697-48b0-9714-1f45740df5d0.png">
 
When this option is selected only appears in the non-AMP version: 

**non-AMP version:**
<img width="1414" alt="Screen Shot 2022-04-14 at 16 16 23" src="https://user-images.githubusercontent.com/330792/163421615-d9d549c5-59bd-4fd0-9f2c-6cea76872b4a.png">

**AMP version:**
<img width="1398" alt="Screen Shot 2022-04-14 at 16 21 49" src="https://user-images.githubusercontent.com/330792/163421830-7c6a68be-17b4-4488-8c33-6b3218a8a0ed.png">

### Expected Behaviour

The AMP version should display the expanded menu option as the non-AMP version

### PHP Version

8.0

### Plugin Version

2.2.4

### AMP plugin template mode

Standard, Transitional

### WordPress Version

5.9.3

**Comment by westonruter** [comment]
What is the “AMP sidebar menu” theme location there? Where is that coming from?

**Comment by westonruter** [comment]
We should check to see if this is a recent regression.

**Comment by fellyph** [comment]
The "AMP Sidebar menu" is from the [James's sidebar menu plugin](https://wordpress.org/plugins/amp-sidebar-hamburger-menu/)

**Comment by dhaval-parekh** [comment]
After checking with a different version found that this bug introduces in AMP version 2.2.2 ( because of [this](https://github.com/ampproject/amp-wp/pull/6312/files#diff-a29bb1b373fe5ec82590f011babf3afd5ddab11e722ae6e84fe624daf215afd3L2924-L2928) change )

Before the change it was converting `.no-js .hide-no-js` selector into `:root:not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_) .no-js .hide-no-js` which was not applying  to expanded menu in twenty-twenty theme, But after changes it convert into `.no-js .hide-no-js:not(#_#_#_#_#_#_#_)` which is apply to expanded menu. ( Note: menu have `header-toggles hide-no-js` classes )

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Cross checked the issue with the test environment mentioned in the issue description and the fix added to the issue is working as expected. 


https://user-images.githubusercontent.com/41000648/172190249-f882f4ca-f2b3-48df-9292-7ed4cb176cf9.mov
