### ISSUE TITLE
Update sanitizer for auto-lightbox disabling to target root element instead of body

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7057]
### Feature Description

Based on https://github.com/ampproject/amphtml/pull/37854#issuecomment-1099619098 it turns out that now if you add `data-amp-auto-lightbox-disable` to the root `html` element, not only will the auto-lightbox behavior be disabled but also the auto-lightbox script will also be prevented from being autoloaded. So we need to update `AMP_Auto_Lightbox_Disable_Sanitizer` (introduced in #6936 for #5122) to make that change.

### Acceptance Criteria

The `data-amp-auto-lightbox-disable` attribute should be added to the `html` element instead of the `body` element.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

data-amp-auto-lightbox-disable attribute is shown in HTML tag instead of body tag. 

**Before: data-amp-auto-lightbox-disable attribute in body tag**

<img width="953" alt="Screenshot 2022-06-07 at 11 22 19 AM" src="https://user-images.githubusercontent.com/41000648/172305729-19b9c180-0b94-409b-9d9f-bb3adce1ab2d.png">

---

**After: data-amp-auto-lightbox-disable attribute in HTML tag**

<img width="881" alt="Screenshot 2022-06-07 at 11 23 00 AM" src="https://user-images.githubusercontent.com/41000648/172305811-1e9dac75-6e14-4f04-8463-2b09dcb603cd.png">

---
