### ISSUE TITLE
I just updated to AMP for wordpress 2.3 It appears this upgrade broke my page formatting

### ISSUE THREAD

**Issue by stephenmorton** [Automattic/amp-wp#7149]
### Bug Description

I just updated from I guess 2.2 to 2.3 and it broke my page formatting. It was the latest version as of an hour ago. I updated it only about 30 mins ago as an update was available. It appears to have broken my wordpress page formatting. I am not sure it is this as I also updated woocommerce at the same time. I am thinking about rolling back to the previous version. What is the best way to do that, I assume disable the plugin in wordpress, uninstall and then dowload and install this previous release

### Expected Behaviour

It is a pretty basic wordpress website. It was working fine, just before updating APM and woocommerce. It could also be the woocommerce update, but I am not sure. I was going to downgrade AMP first, then do the same with woocommerce.

### PHP Version

8.1

### Plugin Version

2.3

### AMP plugin template mode

Standard

### WordPress Version

6.0

**Comment by westonruter** [comment]
You can downgrade by downloading the 2.2 version linked to from the Previous Versions section at https://wordpress.org/plugins/amp/advanced/

With the `amp.zip` file in hand, you can then upload it to WordPress via the admin in Plugins > Add New > Upload. This will then override 2.3 with 2.2.

Do not uninstall. No need to deactivate.

Providing a screenshot would be helpful. It's likely that WooCommerce introduced more CSS which caused it to go over the 75KB limit. If this is the case, an alternative would be to try the “moderate” sandboxing level on the AMP settings screen. This will allow you to have more than 75KB of CSS but otherwise retain the AMP framework.

cc @milindmore22

**Comment by stephenmorton** [comment]
Hi Westonruter, thanks for your quick response. Actually, I don't think this update caused the issue, I think it may have been woocommerce. I have already rolled back this with a rollback plugin, but the site is the same, so I think woocommerce. I'll close this, sorry for the false alarm.

**Comment by westonruter** [comment]
Thanks for the update. Still, you may want to consider the moderate
sandboxing level as a way to continue using WooCommerce and AMP in Standard
mode.
