### ISSUE TITLE
Add "the_content_amp" filter?

### ISSUE THREAD

**Issue by talgalili** [Automattic/amp-wp#715]
It would be nice if instead of using:
```
function change_amp_content($content) {
  if (is_amp_endpoint()) {
// do stuff $content = ...;	
  }
  return $content;
}
add_filter('the_content', 'change_amp_content',100);
```

I could just use:

```
function change_amp_content($content) {
// do stuff $content = ...;	
  return $content;
}
add_filter('the_content_amp', 'change_amp_content',100);
```

Thanks.

**Comment by amedina** [comment]
I see your point @talgalili; but the the_content filter hook is needed to catch the content right after it is retrieved from the DB. Changing the hook to the_content_amp would require to define that hook to behave similarly to the the_content filter and that is outside the scope of the plugin. @mjangda WDYT?

**Comment by westonruter** [comment]
There's not really any difference between the two, other than some syntactic changes. If we added a `the_content_amp` filter then it would essentially require the AMP plugin to add:

```php
add_filter( 'the_content', function( $content ) {
    if ( is_amp_endpoint() ) {
        $content = apply_filters( 'the_content_amp', $content );
    }
    return $content;
} );
```

However, you would then not have control over the priority for when your `the_content_amp` filters apply in relation to the filters for `the_content`.

Since you can easily write your own wrapper like the above for your own theme or plugin, I don't think this is something that needs to be in the AMP plugin.
