### ISSUE TITLE
Invalid Attribute Error displayed in Editor

### ISSUE THREAD

**Issue by pooja-muchandikar** [Automattic/amp-wp#7152]
### Bug Description

For any image available in editor if Lightbox is enabled, Invalid attribute error is shown. This error is specifically visible in WordPress 6.0. 

With WordPress 5.8 this error is not displayed and is working as expected. 

### Expected Behaviour

Error shouldn't be shown, should be able to check image in lightbox.

### Screenshots

Editor Error Screenshot of WP 6.0

<img width="1273" alt="Screenshot 2022-06-15 at 11 08 43 AM" src="https://user-images.githubusercontent.com/41000648/173748968-67475a52-2ebb-41a5-a585-09a8b014a5d5.png">

---

Screenshot of WP 5.8 Editor
<img width="1256" alt="Screenshot 2022-06-15 at 11 15 25 AM" src="https://user-images.githubusercontent.com/41000648/173751357-e6629723-310f-4a0d-9e51-0e35dbe48d91.png">

### PHP Version

8.1

### Plugin Version

2.3.0

### AMP plugin template mode

Standard

### WordPress Version

6.0

**Comment by westonruter** [comment]
Is this when you have enabled native `img` in the advanced settings? It may be what @milindmore22 also found and reported in chat.

**Comment by pooja-muchandikar** [comment]
No, even if native `img` setting is disabled the error is shown.

**Comment by westonruter** [comment]
@thelovekesh Please investigate further.

**Comment by milindmore22** [comment]
I think it's the same issue I mentioned in chat, it will show those attribute invalidations if you turn on lightbox and carousel with the native image and on gallery, I didn't encounter any issue while using amp-img

**Comment by westonruter** [comment]
> No, even if native `img` setting is disabled the error is shown.

@pooja-muchandikar Could you double check this?

**Comment by westonruter** [comment]
When native `img` is being used, instead of adding `layout=fill` we could instead add an inline `style` that has the same properties (e.g. `position:absolute; left:0; right:0; top:0; bottom: 0; width:100%; height:100%`).

The same is true for adding the `object-fit` attribute, we could instead add the inline `style`, `object-fit:cover`.

What we can't solve entirely is the `lightbox`, as this will require amending the AMP validator spec. Currently, the `lightboxable-elements` attribute list is only present on [`amp-img`](https://github.com/ampproject/amphtml/blob/b86012a5ab4e25d76293033de9f93f828bf040b5/validator/validator-main.protoascii#L3908-L3993), but it needs to be added to the [`img` spec](https://github.com/ampproject/amphtml/blob/b86012a5ab4e25d76293033de9f93f828bf040b5/validator/validator-main.protoascii#L1825-L1877) as well. While waiting for this to be valid, we could go ahead and add `lightbox` to the `img` and then add `data-px-verified-attr="lightbox"` to prevent it from being sanitized out.

**Comment by pooja-muchandikar** [comment]
> Could you double check this?

Sure checking, will share update in soon.

**Comment by pooja-muchandikar** [comment]
### Update:

First of all sorry for the inconvenience. 

> No, even if native img setting is disabled the error is shown.

This was due to my site cache. 

---

Secondly yes, the issue happens when `native img` is enabled. Performed the steps on fresh site and following is my observations. 
- Native img is disable: tried creating gallery and enabled lightbox - no error displayed. 
- Native img enabled: tried with same gallery and image and enabled lightbox - error was displayed


https://user-images.githubusercontent.com/41000648/174219582-d35cf31e-4de1-4bd7-a1b5-9e9ffd356799.mov

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue and the fix added for the issue is working as expected. 


https://user-images.githubusercontent.com/44057535/216884708-d4883907-ec30-4667-b979-e78a3cf0fae5.mp4
