### ISSUE TITLE
Lightbox effect: Fails if image is aligned

### ISSUE THREAD

**Issue by Robertght** [Automattic/amp-wp#7154]
### Bug Description

HIt looks like the AMP lightbox effect fails if an image is aligned inside the editor.

Previous issue: https://github.com/ampproject/amp-wp/issues/2936

Also replicated it here: https://github.com/Automattic/wp-calypso/issues/62774

### Expected Behaviour

To be able to open the lightbox.

### PHP Version

8

### Plugin Version

2.3.0

### AMP plugin template mode

Standard, Transitional, Reader

### WordPress Version

6.0

### Gutenberg Version

13.4.0

### OS(s) Affected

MacOS, Windows

### Browser(s) Affected

Chrome

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue and the fix added for the issue is working as expected. Verified it on both FSE and non-FSE theme looks fine. 


**Before:** 

https://user-images.githubusercontent.com/44057535/216864522-34567ed9-0e96-4311-a33f-879256993df2.mp4




**After fix:** 


https://user-images.githubusercontent.com/44057535/216862760-c218f3c0-917d-4541-b5d8-7003a2f5b730.mp4
