### ISSUE TITLE
Improve Paired-mode Templates

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#728]
One of the limitations of plugin at this moment is the simplicity of the of the used templates, which pose some UX challenges (e.g. not clear back navigation to the main site).

**Comment by amedina** [comment]
https://github.com/Automattic/amp-wp/issues/542

**Comment by amedina** [comment]
Considering [ampstart](https://ampstart.com/) as a plausible way to bring good templates to paired mode in the plugin.

**Comment by westonruter** [comment]
The paired mode templates are the (legacy) ones bundled with the plugin which are used when there is no `amp` theme support. Since site implementors who have used the plugin will likely already have added this customizations to the templates to suit their needs, it will be dangerous to further change the bundled paired mode templates since it could break existing sites. 

I think that we should postpone this (after 0.7) to only apply to a new family of `amp`-supporting themes which users can then opt into. We'll need to look at ways for users to be able to install a theme that supports `amp` but to selectively use that theme in a paired mode instead of using the bundled templates. This could play into the work to create AMP-specific versions of the most popular themes.

**Comment by westonruter** [comment]
The bundled paired-mode post templates should be deprecated in favor of `amp` theme support. I think work should focus on adding AMP support to the most popular themes instead of trying to improve the AMP post templates that diverge from the style of the non-AMP pages.
