### ISSUE TITLE
Automatically mark GA4 scripts as being PX-verified

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7289]
### Feature Description

As we have [advised](https://wordpress.org/support/topic/how-to-ga4-to-amp/#post-15870515) in the support forum, site owners can use GA4 on AMP pages by using the moderate sandboxing level and adding `data-px-verified-tag` to the Google Analytics scripts. 

We should add a sanitizer that will do this automatically when the user has selected either the Moderate or Loose sandboxing level. This will facilitate using GA4 while waiting on an AMP implementation.

### Acceptance Criteria

GA4 scripts should not get sanitized from pages when in Moderate or Loose sandboxing level.

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue and the fix added for the issue is working as expected with the Moderate or Loose sandboxing mode. 

- Gtag script is displayed as data-px-verified. 
- Element with gtag on click script is also displayed as data-px-verified. 

![image](https://user-images.githubusercontent.com/44057535/216908126-a52a9d47-a641-4af2-85ff-2acd26b57473.png)


![image](https://user-images.githubusercontent.com/44057535/216907828-cbe193cd-327a-4538-afe8-32736e93f18e.png)
