### ISSUE TITLE
Add Filter that can be used to disable auto site scan on plugin page.

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#7309]
### Feature Description

A user on [support topic](https://wordpress.org/support/topic/disable-site-scan/#post-16098734) asked if we have any filter to disable auto site scan on the plugin page.

As discussed on slack service is not shared so it will be easy for users to toggle off with a filter.

### Acceptance Criteria

A new filter that can disable site scan (auto site scan) on plugin page.

**Comment by thelovekesh** [comment]
@westonruter In this situation, we have the option to turn off the site scan by ceasing to enqueue `amp-site-scan-notice` assets in the admin, but doing so will also have an impact on the site scan drawer on the settings page.

What if we could regulate it via settings rather than a filter, in my opinion? We can offer some choices in the `site scan` drawer, including the ability to disable the `site scan` and the following options:
- Disable site scan - In this case, we will not enqueue the site scan assets at all in the admin.
- Disable site scan on plugin page - In this case, do not enqueue site scan assets on `plugins.php`.
- Disable site scan on theme page - In this case, do not enqueue site scan assets on `themes.php`.

In case the user disables site scan on themes and plugins pages, we will able to scan results in the `Site Scan` drawer.

**Comment by milindmore22** [comment]
@thelovekesh I will recommend going with disabling the site scan on `themes.php` and `plugins.php` since the manual site scan (drawer) is a feature and we should not disable it as the manual site scan will only trigger when the user performs a certain action (click site scan button)

The auto scan on the plugins and themes page is affecting users without their intention and slowing down the bulky sites.

**Comment by westonruter** [comment]
@thelovekesh Thanks for pointing out the fact that merely dequeuing the script/style could disable the scan. In that case, since there is a fixed handle, could not a mini plugin be created that runs only on the plugins screen or the themes screen that runs at `admin_enqueue_scripts` priority 11 and dequeues the `amp-site-scan-notice` style/script? 

Since only one user has requested this, I hesitate to introduce a new setting or even a new filter for that matter.

**Comment by thelovekesh** [comment]
> In that case, since there is a fixed handle, could not a mini plugin be created that runs only on the plugins screen or the themes screen that runs at admin_enqueue_scripts priority 11 and dequeues the amp-site-scan-notice style/script?

It does make sense, yes.

 > Since only one user has requested this, I hesitate to introduce a new setting or even a new filter for that matter.

Since there is very little likelihood that it will be utilized by external plugins, I am also against it, at least for the filter. Additionally, its overkill to have a setting on our options page if it isn't frequently requested.

> runs at admin_enqueue_scripts priority 11 and dequeues the amp-site-scan-notice style/script

💯

**Comment by thelovekesh** [comment]
Mini plugin for disabling site scan on plugins/themes activation page - https://github.com/rtCamp/amp-site-scan-disable

**Comment by milindmore22** [comment]
Since this is not every user request, we will be providing this as a mini plugin, the plugin has been added to the [mini plugin and extensions page](https://amp-wp.org/documentation/extending-amp-compatibility-extensions-and-mini-plugins/)
