### ISSUE TITLE
Validation issue with WP 6.1 core navigation block

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#7322]
### Bug Description

The core navigation block enqueues a script for the block, creating an invalidation in the core.

The error is reproducible with Twenty Twenty-Two and Twenty Twenty-three theme

```json
{
	"node_name": "script",
	"parent_name": "head",
	"code": "DISALLOWED_TAG",
	"type": "js_error",
	"node_attributes": {
		"src": "http://one.wordpress.test/wp-includes/blocks/navigation/view-modal.min.js?ver=__normalized__",
		"id": "wp-block-navigation-view-2-js"
	},
	"node_type": "ELEMENT",
	"sources": [
		{
			"type": "core",
			"name": "wp-includes",
			"file": "blocks/navigation.php",
			"line": 668,
			"function": "register_block_core_navigation",
			"hook": "init",
			"priority": 10,
			"dependency_type": "script",
			"handle": "wp-block-navigation-view-2"
		},
		{
			"type": "core",
			"name": "wp-includes",
			"file": "blocks/template-part.php",
			"line": 15,
			"function": "render_block_core_template_part",
			"dependency_type": "script",
			"handle": "wp-block-navigation-view-2"
		},
		{
			"type": "core",
			"name": "wp-includes",
			"file": "script-loader.php",
			"line": 2127,
			"function": "wp_print_head_scripts",
			"hook": "wp_head",
			"priority": 9
		}
	],
	"removed": true,
	"reviewed": false
}
```
However, the menu toggle is working on AMP pages. 

### Expected Behaviour

The Core and Core themes should not create validation issues 

### Screenshots

![image](https://user-images.githubusercontent.com/1132541/199218308-77f14887-aa33-486c-aaaf-b74c8b19e3e1.png)

### PHP Version

7.4.3

### Plugin Version

2.3.0

### AMP plugin template mode

Standard, Transitional

### WordPress Version

6.1-RC3

**Comment by thelovekesh** [comment]
The navigation block was modified in https://github.com/WordPress/gutenberg/pull/40135, which caused the block's view script to be spllited and now it's the cause of the validation issue. Also, this navigation block was previously made amp-compatible in https://github.com/ampproject/amp-wp/pull/6838.

Since it doesn't implement something new other than splitting the block's view script, dequeuing the `wp-block-navigation-view-2` script handle will work fine.

**Comment by westonruter** [comment]
The handle `wp-block-navigation-view-2` is curiously named!

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue and the fix added for the issue is working as expected. Verified it with the Twenty Twenty-Two and Twenty Twenty-three themes working fine. 

**Before:** 

![image](https://user-images.githubusercontent.com/44057535/216885206-d1bc3d90-a281-43bf-b3f3-cb1986887ca5.png)


**After fix:** 

https://user-images.githubusercontent.com/44057535/216885457-594bd29f-89cf-47fb-8368-9a49c6b57469.mp4
