### ISSUE TITLE
i-amphtml-sidebar-mask has z-index that covers links in sidebar

### ISSUE THREAD

**Issue by ActionCoding** [Automattic/amp-wp#736]
Just noticed this recently but when using the amp-sidebar to show a menu when the sidebar is opened the mask is given a z-index value of 2147483646. This overrides the sidebar which makes the links unclickable

**Comment by westonruter** [comment]
I think this may actually be an issue for the [amphtml](https://github.com/ampproject/amphtml) project itself.

**Comment by pbuzdin** [comment]
`amp-sidebar+div { opacity: 0; pointer-events: none; }`

**Comment by fabianmarz** [comment]
In case someone stumbles across this: I had the same issue today. This was caused because of the wrong placement of the `<amp-sidebar>` container where I placed it in a div, not as a direct child of `<body>`. As the [docs](https://www.ampproject.org/docs/reference/components/amp-sidebar#behavior) state:

> The `<amp-sidebar>` should be a direct child of the `<body>`.
