### ISSUE TITLE
Large number of calls to Parser State

### ISSUE THREAD

**Issue by spacedmonkey** [Automattic/amp-wp#7381]
### Bug Description

While doing some profiling on the web stories plugin, I noticed a high number of calls to Parser State call. See screenshot. Calling the same method 150k times, seems a little high. I wonder if this could be improved to improve performance. 

The screenshot was generated using blackfire. 

Let me know if you have anymore questions. 

### Expected Behaviour

Less calls to method.

### Screenshots

<img width="1786" alt="Screenshot 2022-12-19 at 11 57 23" src="https://user-images.githubusercontent.com/237508/209156765-e51fe809-fd0c-421c-b82a-3d884a6aadad.png">

### PHP Version

8.0

### Plugin Version

dev-master

### AMP plugin template mode

Standard

### WordPress Version

6.1.1

### Site Health

NA

**Comment by westonruter** [comment]
Thanks for the report. That does seem high. It should only be getting called once for each element in the DOM. I assume you aren't testing with a document that has 150K elements?

**Comment by thelovekesh** [comment]
After checking it, I can confirm that, at first glance, it does make a significant number of calls to the `ParserState` class. In my opinion, this is because many of the Parser classes rely on the `ParserState` class. For illustration;

![image](https://user-images.githubusercontent.com/54371619/221963145-4afb20af-7d32-45bb-b514-3ff7b8ce4753.png)


However, once the stylesheet was cached after the first reload, the CSS Parser was not used again.

![image](https://user-images.githubusercontent.com/54371619/221967096-753cf2a3-abbd-4ce0-805d-479c6d11c693.png)

Profiler: XDebug
Call graph generation is done using [KCachegrind](https://kcachegrind.sourceforge.net/html/Home.html) :)

**Comment by westonruter** [comment]
What about calls to `process_node` as originally identified?

**Comment by thelovekesh** [comment]
> What about calls to process_node as originally identified?

I think we are investigating calls to ParserState which is not related to `AMP_Tag_And_Attribute_Sanitizer::process_node`. Oh did you point it out from the caller graph? Here are the results though. 

The AMP plugin is calling `process_node` the right number of times. For a page with `156` elements, it got triggered `153` times which is expected I think.

> document.all.length
156

![image](https://user-images.githubusercontent.com/54371619/222067586-6d59256b-5d57-4770-a579-6274dac0d280.png)

**Comment by westonruter** [comment]
Yeah, that's what I would expect as well. I'm confused why @spacedmonkey saw it being called 150k times, specifically in the context of a Web Story document.

**Comment by westonruter** [comment]
Sorry, I misread the original issue. Even though the graph shows that `AMP_Tag_And_Attribute_Sanitizer::process_node()` is selected, the extreme number of calls are indeed in `ParserState`. This is part of the [PHP-CSS-Parser](https://github.com/sabberworm/PHP-CSS-Parser) library. When encountering a stylesheet for the first time, the AMP plugin (and Web Stories plugin) will use PHP-CSS-Parser to parse the CSS and the result is then cached. When a parsed stylesheet has not been cached, it is expected that there be a significant performance bottleneck due to PHP-CSS-Parser. Unfortunately this isn't something we can fix in the context of the AMP plugin, and it's something that would need to be addressed with that library directly.
