### ISSUE TITLE
Custom Post Type Support Not Working

### ISSUE THREAD

**Issue by bobsilon** [Automattic/amp-wp#753]
Hi There,
I'm trying to add custom post type support as shown in wiki, but when I try to view my custom post using `/amp` in end of URL, it redirects to post's original URL. And of course, No `amphtml` meta tag added to source code of page.

This is how I registering my CPT:
```php
add_action('init', 'Ordme_Post_Types::register_post_type');
add_action( 'amp_init', 'ordme_article_amp_cpt' );

function ordme_article_amp_cpt() {
	add_post_type_support( 'ORDME_SLUG_TYPE_ARTICLE', AMP_QUERY_VAR );
}

public static function register_post_type() {
	register_post_type(ORDME_SLUG_TYPE_ARTICLE, array(
		'labels' => array(
                        'name' => __( 'Articles' ),
                        'singular_name' => __( 'Article' )
	                'parent_item_colon' => ''),
		'public' => true,
		'exclude_from_search'=> false,
		'show_ui' => true,
		'_builtin' => false,
		'capability_type' => 'post',
		'has_archive' => true,
		'hierarchical' => false,
		'taxonomies' => array('post_tag'),
		'rewrite' => array('slug' => ORDME_SLUG_TYPE_ARTICLE, 'feeds' => true),
		'menu_icon' => '',
		'supports' => array('title','editor','thumbnail','custom-fields', 'comments', 'author')
	));
}
```
I also **flushed** rewrite rules using permalinks and **deactivated** other plugins, but no change. Am I doing something wrong? Any idea?

AMP: v0.5
Wordpress: v4.7.2

**Comment by k-atul** [comment]
@bobsilon 
have you defined a constant for custom post because you are using it in 2 ways

like value: in quotes
add_post_type_support( 'ORDME_SLUG_TYPE_ARTICLE', AMP_QUERY_VAR );

and then as constant var as-well: without quotes
register_post_type(ORDME_SLUG_TYPE_ARTICLE
'rewrite' => array('slug' => ORDME_SLUG_TYPE_ARTICLE,

probably you need to change it, either use as constant or as value and then you need to save your Settings->Permalinks again for urls to work.

**Comment by westonruter** [comment]
There is a typo in your `ordme_article_amp_cpt` function. It should contain:

```php
add_post_type_support( ORDME_SLUG_TYPE_ARTICLE, AMP_QUERY_VAR );
```

Whereas currently it is incorrectly passing a string `'ORDME_SLUG_TYPE_ARTICLE'`.
