### ISSUE TITLE
Remove Gfycat

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7610]
### Bug Description

The Gfycat service has been shut down: https://techcrunch.com/2023/07/05/gfycat-shuts-down-on-september-1/amp/

This is causing unit tests to fail. We need to remove support for Gfycat.

### Expected Behaviour

Any sanitizers and embed handlers for Gfycat should be removed since the service is shut down.

### Plugin Version

n/a

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

The Embedding of Gyfcat URLs is not working. After embedding a Gyfcat URL the link is visible. 

<details><summary>Details</summary>

![image](https://github.com/ampproject/amp-wp/assets/44057535/20127d3c-6091-4e50-86d9-4a3fff40f57c)

</details> 



When a URL is embedded using an iframe, the content is displayed within the tag instead of amp-gyfcat. 

<details><summary>Details</summary>


![image](https://github.com/ampproject/amp-wp/assets/44057535/fce3b21f-8c1b-4ddf-b1cb-b3105e479166)



</details>
