### ISSUE TITLE
PHP error: Undefined array key "type" in class-amp-validation-manager.php on line 1169

### ISSUE THREAD

**Issue by jcvignoli** [Automattic/amp-wp#7862]
### Bug Description

When executing WP updates (using a cron with wp-cli), I get:
`Got error 'PHP message: PHP Warning: Undefined array key "type" in wp-content/plugins/amp/includes/validation/class-amp-validation-manager.php on line 1169'`

### Expected Behaviour

No warning

### PHP Version

PHP 8.2

### Plugin Version

2.5.4

### AMP plugin template mode

Transitional

### WordPress Version

6.6.1

**Comment by camrionnvmff** [comment]
This is due to attempting to access keys that do not exist in the array.
In PHP 8.2, this situation will trigger a warning.

To solve this problem, you can modify the relevant code in the class amp validation manager. php file to ensure that it is checked before accessing the type key.

Here is an example

if (isset($array['type'])) {
//Accessing the $array ['type '] key
$type = $array['type'];
} else {
//The processing logic when the key does not exist
$type = null; //  Or other default values
}
To be specific to your situation, you can find the relevant code near line 1169 and make similar modifications.

If you are unable to modify the plugin code, you can try switching the PHP version to 8.3 through Servbay.

**Comment by katiehartrick** [comment]
Same issue on WordPress.com hosting
PHP 8.1.29
WordPress 6.6.1
AMP plugin 2.54

**Comment by westonruter** [comment]
A build with a fix is available for testing: https://github.com/ampproject/amp-wp/pull/7864#issuecomment-2305256999

You can install the `amp.zip` for the production build via that comment.

**Comment by jcvignoli** [comment]
I continue having the same issue, just the line has changed:
`Got error 'PHP message: PHP Warning: Undefined array key "type" in wp-content/plugins/amp/includes/validation/class-amp-validation-manager.php on line 1176; `
Currently WP 6.6.2, PHP 8.3, AMP 2.5.4

**Comment by westonruter** [comment]
@jcvignoli The change has not been released yet. You can try the pre-release production build linked to from https://github.com/ampproject/amp-wp/wiki/Development-Builds

**Comment by westonruter** [comment]
This has been released in v2.5.5.
