### ISSUE TITLE
 The tag 'FORM [method=GET]' requires including the 'amp-form' extension JavaScript.

### ISSUE THREAD

**Issue by abrambailey** [Automattic/amp-wp#802]
I'm seeing this error being generated on my site. 

`The tag 'FORM [method=GET]' requires including the 'amp-form' extension JavaScript.`

This is from the generated amp html:
```html
<form action="[removed]" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate=""> </form>
```

**Comment by westonruter** [comment]
Where is the form coming from? Is it in the post content or is it somewhere else? Is it coming from a shortcode?

**Comment by abrambailey** [comment]
This comes from the following raw html on a page. 
```html
<form action="[removed]" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
  <div id="mc_embed_signup_scroll" class="input-group">
  <input type="email" value="" name="EMAIL" class="email form-control" id="mce-EMAIL" placeholder="email address" required="">
    <div><input type="text" name="[removed]" tabindex="-1" value=""></div>
    <span class="input-group-btn"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button btn btn-info"></span>
    </div>
</form>
```

**Comment by abrambailey** [comment]
@westonruter Is there a class name that I can apply to this form's containing div to have it ignored for the amp version? Like `class="hide_in_amp"` or something?

**Comment by brianlayman** [comment]
For now, you could add the amp-form extension through a function hooked to the action 'amp_post_template_head', checking for that specific page.

**Comment by westonruter** [comment]
For forms that are added to to the v0.6 paired mode templates, adding the `amp-form` component script needs to be done via the `amp_post_template_data` filter as can be seen being done for analytics:

https://github.com/Automattic/amp-wp/blob/216ec376ab5bc698e03a149e6e68fa771cffd2d0/includes/amp-post-template-actions.php#L20

https://github.com/Automattic/amp-wp/blob/216ec376ab5bc698e03a149e6e68fa771cffd2d0/includes/amp-post-template-actions.php#L120-L131

Otherwise, for forms that are added to the _content_ or for forms that are added to templates in themes that have `amp` support (new in 0.7-alpha in `develop`), then merely adding a `<form>` to the response will cause the AMP component script to automatically be included.

See #907 and #875.
