### ISSUE TITLE
Merging color scheme options for AMP / Non-AMP in Customizer

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#830]
https://v.usetapes.com/TYe1axBIXB

Related to the work on #796 would it be helpful to merge the color schemes for the AMP version of the Customizer and the non-AMP version?

cc @ThierryA and @westonruter

**Comment by westonruter** [comment]
Yes it would be ideal to connect them so that AMP re-uses the color scheme from the theme. The challenge here is that not all themes have comparable a concept of “color scheme” to use (see core themes below). For some themes we could try to create a bridge to re-use the theme's styles when relevant ones are present, but then we'd need to have an adapter for each theme we support. All of the core themes would make sense. Whatever the most [popular themes](https://wordpress.org/themes/browse/popular/) are. So really this would be part of an effort to create AMP'ed versions of the core themes to have a “transparent paired mode”—where the AMP templates and non-AMP templates look identical, or almost the same.

# Twenty Thirteen

![image](https://user-images.githubusercontent.com/134745/33913555-28d00ed6-df4f-11e7-99dd-34414c9f2eb2.png)

# Twenty Fourteen

![image](https://user-images.githubusercontent.com/134745/33913572-39a63406-df4f-11e7-9d5d-6708c0cab942.png)

# Twenty Fifteen

![image](https://user-images.githubusercontent.com/134745/33913620-67b12ca2-df4f-11e7-9c15-bc83b94f3374.png)


# Twenty Sixteen

![image](https://user-images.githubusercontent.com/134745/33913641-85382212-df4f-11e7-947f-c1ec5ee275fe.png)

# Twenty Seventeen

![image](https://user-images.githubusercontent.com/134745/33913684-b3c25f6c-df4f-11e7-8178-8b66cdc166a5.png)

**Comment by westonruter** [comment]
This is now irrelevant now that we have full theme support.
