### ISSUE TITLE
"selected" and "option" attributes are stripped on amp-selector childs

### ISSUE THREAD

**Issue by htrex** [Automattic/amp-wp#899]
AMP_Allowed_Tags_Generated does not allow the "selected" attribute in divs.
In AMP examples the "selected" attribute is used inside ``<div>`` elements and using it is mandatory for it to work.
https://ampbyexample.com/advanced/tab_panels_with_amp-selector/
That page is AMP valid, so it shouldn't be a problem to add it.

**Comment by htrex** [comment]
Thanks for caring, I've just found that the "option" attribute is mandatory too, for it to work.
The "selected" and "option" attributes may only appear in divs with an ``<amp-selector>`` parent or ancestor. 

This is AMP valid 
```
<!-- NOT VALID AMP  -->
<div selected option="a"></div>
  
<!-- VALID AMP  -->
<amp-selector>
  <div selected option="a"></div>
  <div>
    <div selected option="a"></div>
  </div>
  <div><div>
    <div selected option="a"></div>
  </div></div>
</amp-selector>
```

**Comment by westonruter** [comment]
It looks like the problem is that the whitelist sanitizer doesn't currently parse out “Reference Points”, such as introduced by the `amp-selector` component: https://github.com/ampproject/amphtml/blob/aa3dc098aaf7e1b336751c6c35174ffbe374c510/extensions/amp-selector/validator-amp-selector.protoascii#L64-L94

I can see that this change makes it so that the `selected` and `option` attributes aren't stripped, by this `whitelisted_attr_regex` which is not currently generated from the spec:

```diff
diff --git a/includes/sanitizers/class-amp-rule-spec.php b/includes/sanitizers/class-amp-rule-spec.php
--- a/includes/sanitizers/class-amp-rule-spec.php
+++ b/includes/sanitizers/class-amp-rule-spec.php
@@ -77,7 +77,7 @@ abstract class AMP_Rule_Spec {
 	 */
 	public static $whitelisted_attr_regex = array(
 		'@^data-[a-zA-Z][\\w:.-]*$@uis',
-		'(update|item|pagination)', // Allowed for live reference points.
+		'(update|item|pagination|option|selected|disabled)', // Allowed for live reference points.
 	);
 
 	/**
```

**Comment by westonruter** [comment]
@htrex please test #905.
