### ISSUE TITLE
Should we hydrate $authordata before calling templates?

### ISSUE THREAD

**Issue by davisshaver** [Automattic/amp-wp#981]
As described earlier in https://github.com/Automattic/amp-wp/issues/734, we may want to hydrate the global `$authordata` variable to improve developer experience in AMP templates.

```
add_action( 'pre_amp_render_post', 'author_data_in_amp' );

/**
 * Add author data to amp.
 */
function author_data_in_amp() {
  global $authordata;
  if ( ! isset ($authordata ) ) {
      $post = get_post( $post_id );
      $authordata = get_userdata( $post->post_author );
  }
}
```

**Comment by davisshaver** [comment]
The use case for me was using the same function to generate GTM data layer JSON blob for AMP and non-AMP.

**Comment by westonruter** [comment]
We wouldn't you just do `$authordata = get_userdata( get_queried_object()->post_author )` always? Relying on the presence of a global variable is not ideal. I suppose the only reason to do so would be for the sake of plugins that are looking for `$authordata`.

Really the issue is not that `$authordata` is not being defined but rather that `setup_postdata( get_queried_object() )` is not being called. This is what defines `$authordata` among other variables. That being said, this function will also paginate multi-page content so that could be problematic.

Note that the AMP post templates in the plugin will eventually be deprecated in favor of full theme support with templates written the normal WordPress way so this will become irrelevant.

**Comment by davisshaver** [comment]
I was using `get_the_author()` which assumes presence of `$authordata` global. I saw the issue as inconsistent behavior of core template functions but I understand the pagination side effect you are mentioning. Maybe the best step is just to close this and if anyone else runs into the same they can use the pattern above as a workaround?

**Comment by westonruter** [comment]
Yeah, agreed. The above workaround will work well. Since `pre_amp_render_post` will cease to be called with the move to AMP-supporting themes, the code will eventually cease to be required.
