### ISSUE TITLE
AMP is not available

### ISSUE THREAD

**Issue by otpidusprime** [Automattic/amp-wp#988]
Getting an `AMP is not available for the page currently being previewed.` message on the site: globaltripinfo.co when we go to AMP option in the customizer - even if the plugin is enabled and updated.

I tried to check if it is a plugin conflict, disabling other plugins did not help.

**ISSUE SCREENSHOT:**
![screen shot 2018-03-03 at 4 06 21 pm](https://user-images.githubusercontent.com/29238672/36933322-082f3cc2-1efd-11e8-9f9c-3992a67501dd.png)

**STEPS TO REPRODUCE:**
1. Go to **My Site → Customize**
2. Click on **AMP**

**Comment by westonruter** [comment]
Look in the footer, you'll see an AMP toggle. Clicking it will reveal a tooltip with a link to load an AMP page into the preview:

![image](https://user-images.githubusercontent.com/134745/36942267-3d4e17ea-1f23-11e8-885a-11055e6f1233.png)

**Comment by otpidusprime** [comment]
When I click on that toggle, the tooltip has no link to AMP compatible page.
![screen shot on 2018-03-04 at 13_25_28](https://user-images.githubusercontent.com/29238672/36943442-9224bfd0-1faf-11e8-9b22-85732bcfc611.png)

**Comment by westonruter** [comment]
@otpidusprime do you have any posts published? Have you enable AMP support in the admin for the post types that you use on your site?

**Comment by otpidusprime** [comment]
@westonruter That is actually a site of the user that I am currently helping with.
Not sure if I should put the ticket number here as this issue thread is public.

However, I can say that there are no posts published on the site. Only some pages.

**Comment by westonruter** [comment]
@otpidusprime ok, then it makes sense that this link would not work. 

The URL that is used for this tooltip comes from `amp_admin_get_preview_permalink()`:

https://github.com/Automattic/amp-wp/blob/fc6d81cae20b164f8fea60b7080bb245f1d22497/includes/admin/functions.php#L38-L70

You can see that it looks for the default post type of `post`, which you don't have any of.

So what you should be able to do is navigate to a page in the preview and then toggle AMP on. Otherwise, if you want the tooltip to have the shortcut then you should be able to do:

```php
add_filter( 'amp_customizer_post_type', function() {
    return 'page';
} );
```

That will cause pages to be queried instead of posts. Naturally you'll need to opt-in to `page` post type being supported in the admin.

**Comment by westonruter** [comment]
Looking at one example page: https://globaltripinfo.co/searchactivity/

If I look at the source code for the page, I do not see an `amphtml` link anywhere. I also see that it is a custom page template. When a page has a custom page template you have to opt-in to AMP for that page:

![image](https://user-images.githubusercontent.com/134745/37047536-1602dbcc-2120-11e8-97fd-72e951efe7a6.png)

Once you do that, the AMP version should be available. But note that you'll need to create the AMP-specific templates to go along with it. (In the upcoming 0.7 version of the plugin, we're working toward the ability to have a single template served for both AMP and non-AMP.)

**Comment by otpidusprime** [comment]
Alright! Will give this a go and update you on this.
Thank you so much for the prompt responses till now :)
